[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "libxkbcommon",
  "mesa",
  "expat",
  "glib",
  "dbus",
  "pango",
  "cairo",
  "freetype",
  "fontconfig",
  "alsa-lib"
]
