"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.compliancePrompts = void 0;
exports.compliancePrompts = {
    'compliance.report': {
        name: 'compliance.report',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a regulatory compliance expert. Generate a compliance report covering KYC, SEBI regulations, and investor protection guidelines.",
    },
    'compliance.dlm_agreement': {
        name: 'compliance.dlm_agreement',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a SEBI compliance expert analyzing a financial services agreement. Analyze the following agreement for a specified entity type.",
    },
    'compliance.error_analysis': {
        name: 'compliance.error_analysis',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are an expert software engineer analyzing a production error in a SEBI/RBI-compliant financial platform (FintekPro).",
    },
    'compliance.system_errors': {
        name: 'compliance.system_errors',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a senior software engineer and system architect. Analyze the following system errors and provide actionable technical recommendations.\n\nFocus on:\n1. Root cause analysis of each error type\n2. Priority classification (Critical/High/Medium/Low)\n3. Specific technical solutions and code fixes\n4. Prevention strategies to avoid future occurrences\n5. Performance impact assessment",
    },
    'compliance.security_scan': {
        name: 'compliance.security_scan',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a cybersecurity expert. Analyze the following system data for security vulnerabilities and compliance issues.\n\nFocus on:\n1. Authentication and authorization weaknesses\n2. Data protection and privacy gaps\n3. API security vulnerabilities\n4. Access control improvements\n5. Compliance recommendations (GDPR, SOC2, etc.)",
    },
    'compliance.activity_insights': {
        name: 'compliance.activity_insights',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are FintekPro's AI business analyst. Analyze these platform metrics and provide actionable insights.",
    },
    'compliance.tax_form': {
        name: 'compliance.tax_form',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a tax expert AI. Based on the user profile, suggest the most appropriate ITR form.",
    },
    'compliance.tax_regime': {
        name: 'compliance.tax_regime',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a tax optimization expert. Analyze the user profile and recommend the best tax regime.",
    },
    'compliance.esign_analysis': {
        name: 'compliance.esign_analysis',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a legal document analysis assistant for a financial services platform. Analyze the following document and provide structured suggestions.",
    },
    'compliance.knowledge_hub': {
        name: 'compliance.knowledge_hub',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a financial education expert helping financial advisors explain complex concepts to retail clients in India.",
    },
    'compliance.fintekpro_rating': {
        name: 'compliance.fintekpro_rating',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a SEBI-compliant investment analyst. Provide a brief 2-3 sentence insight for the specified asset class.",
    },
    'compliance.api_performance': {
        name: 'compliance.api_performance',
        version: '1.0.0',
        lastReviewedAt: '2025-01-15',
        reviewedBy: 'compliance-team',
        regulatoryCategory: 'compliance',
        systemPrompt: "You are a performance optimization expert. Analyze the following API performance data and provide optimization recommendations.\n\nFocus on:\n1. Response time bottlenecks and solutions\n2. Reliability issues and fixes\n3. Scalability concerns and improvements\n4. Infrastructure optimization recommendations\n5. Monitoring and alerting suggestions",
    },
};
