import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, boolean, index, uniqueIndex, integer, jsonb, decimal, date } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").unique().notNull(),
  email: varchar("email"),
  mobile: varchar("mobile"),
  password: text("password").notNull(),
  firstName: varchar("first_name"),
  middleName: varchar("middle_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  isEmailVerified: boolean("is_email_verified").default(false),
  isMobileVerified: boolean("is_mobile_verified").default(false),
  panNumber: varchar("pan_number").unique(),
  aadharNumber: varchar("aadhar_number").unique(),
  passportNumber: varchar("passport_number"),
  drivingLicense: varchar("driving_license"),
  voterIdNumber: varchar("voter_id_number"),
  dateOfBirth: varchar("date_of_birth"),
  nationality: varchar("nationality"),
  fatherName: varchar("father_name"),
  motherName: varchar("mother_name"),
  spouseName: varchar("spouse_name"),
  maritalStatus: varchar("marital_status"),
  address: text("address"),
  city: varchar("city"),
  state: varchar("state"),
  pincode: varchar("pincode"),
  country: varchar("country"),
  occupation: varchar("occupation"),
  annualIncome: varchar("annual_income"),
  investmentExperience: varchar("investment_experience"),
  riskTolerance: varchar("risk_tolerance"),
  sourceOfWealth: varchar("source_of_wealth"),
  residentStatus: varchar("resident_status"),
  countryOfResidence: varchar("country_of_residence"),
  taxResidencyCountry: varchar("tax_residency_country"),
  fatcaStatus: varchar("fatca_status"),
  fatcaTinNumber: varchar("fatca_tin_number"),
  fatcaCountryOfTaxResidence: varchar("fatca_country_of_tax_residence"),
  pepStatus: varchar("pep_status"),
  pepDetails: text("pep_details"),
  isUbo: boolean("is_ubo").default(false),
  uboDetails: text("ubo_details"),
  bankAccountNumber: varchar("bank_account_number"),
  ifscCode: varchar("ifsc_code"),
  nomineeDetails: text("nominee_details"),
  nomineeRelation: varchar("nominee_relation"),
  euinNumber: varchar("euin_number"),
  enableCamsApi: boolean("enable_cams_api").default(false),
  enableKfintechApi: boolean("enable_kfintech_api").default(false),
  enableNsdlApi: boolean("enable_nsdl_api").default(false),
  enableCdslApi: boolean("enable_cdsl_api").default(false),
  nsdlDpId: varchar("nsdl_dp_id"),
  nsdlClientId: varchar("nsdl_client_id"),
  cdslBoId: varchar("cdsl_bo_id"),
  cdslDpId: varchar("cdsl_dp_id"),
  panVerificationConsent: boolean("pan_verification_consent").default(false),
  panConsentGivenAt: timestamp("pan_consent_given_at"),
  panConsentIpAddress: varchar("pan_consent_ip_address"),
  panConsentUserAgent: text("pan_consent_user_agent"),
  panConsentVersion: varchar("pan_consent_version").default("1.0"),
  preferredCamsRegistration: boolean("preferred_cams_registration").default(false),
  preferredKfintechRegistration: boolean("preferred_kfintech_registration").default(false),
  preferredNsdlRegistration: boolean("preferred_nsdl_registration").default(false),
  preferredCdslRegistration: boolean("preferred_cdsl_registration").default(false),
  agentId: varchar("agent_id"),
  arnCode: varchar("arn_code"),
  distributorId: varchar("distributor_id"),
  complianceOfficer: varchar("compliance_officer"),
  clientType: varchar("client_type"),
  companyName: varchar("company_name"),
  entityType: varchar("entity_type"),
  entityRegistrationNumber: varchar("entity_registration_number"),
  incorporationDate: varchar("incorporation_date"),
  businessNature: varchar("business_nature"),
  countryOfCitizenship: varchar("country_of_citizenship"),
  isUSPerson: boolean("is_us_person").default(false),
  isEUResident: boolean("is_eu_resident").default(false),
  gdprConsent: boolean("gdpr_consent").default(false),
  gdprConsentDate: timestamp("gdpr_consent_date"),
  dataProcessingConsent: boolean("data_processing_consent").default(false),
  marketingConsent: boolean("marketing_consent").default(false),
  investorType: varchar("investor_type"),
  investorCategory: varchar("investor_category"),
  financialSituation: varchar("financial_situation"),
  investmentObjective: varchar("investment_objective"),
  profileCompleteness: integer("profile_completeness").default(0),
  isProfileCompleted: boolean("is_profile_completed").default(false),
  profileCompletedAt: timestamp("profile_completed_at"),
  lastUpdated: timestamp("last_updated").defaultNow(),
  digilockerAddress: text("digilocker_address"),
  digilockerDOB: varchar("digilocker_dob"),
  digilockerGender: varchar("digilocker_gender"),
  digilockerFullName: varchar("digilocker_full_name"),
  aadhaarLastFour: varchar("aadhaar_last_four"),
  nameMatchScore: integer("name_match_score"),
  nameReconciliationStatus: varchar("name_reconciliation_status"),
  nameReconciliationNote: text("name_reconciliation_note"),
  panVerifiedViaSmartKyc: boolean("pan_verified_via_smart_kyc").default(false),
  panVerificationDate: timestamp("pan_verification_date"),
  aadhaarVerifiedViaSmartKyc: boolean("aadhaar_verified_via_smart_kyc").default(false),
  aadhaarVerificationDate: timestamp("aadhaar_verification_date"),
  smartKycCompletedAt: timestamp("smart_kyc_completed_at"),
  roles: varchar("roles").array().default(sql`ARRAY['user']`),
  isActive: boolean("is_active").default(true),
  appointmentStatus: varchar("appointment_status").default("active"),
  appointmentInitiatedBy: varchar("appointment_initiated_by"),
  appointmentInitiatorRole: varchar("appointment_initiator_role"),
  appointmentApprovedBy: varchar("appointment_approved_by"),
  appointmentApprovedAt: timestamp("appointment_approved_at"),
  appointmentRejectionReason: text("appointment_rejection_reason"),
  appointmentCostCentreId: varchar("appointment_cost_centre_id"),
  lastLoginAt: timestamp("last_login_at"),
  previousLoginAt: timestamp("previous_login_at"),
  loginCount: integer("login_count").default(0),
  navPosition: varchar("nav_position").default("left"),
  planTier: varchar("plan_tier").default("free").notNull(),
  planExpiresAt: timestamp("plan_expires_at"),
  cashfreeSubscriptionId: varchar("cashfree_subscription_id"),
  kycStatus: varchar("kyc_status"),
  ckycStatus: varchar("ckyc_status"),
  twoFactorEnabled: boolean("two_factor_enabled").default(false),
  twoFactorSecret: text("two_factor_secret"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  irisInvestorId: varchar("iris_investor_id"),
  alpacaAccountId: varchar("alpaca_account_id"),
  alpacaAccountType: varchar("alpaca_account_type").default("individual"), // 'individual', 'custodial', 'omnibus'
  referralCode: varchar("referral_code").unique(),
  isPinSet: boolean("is_pin_set").default(false),
  loginPin: text("login_pin"),
  shareableProfileEnabled: boolean("shareable_profile_enabled").default(false),
  // Agent geo coverage — used by Lead Assignment Engine for geo-priority routing
  operatingCities: jsonb("operating_cities").$type<string[]>().default([]),
  operatingStates: jsonb("operating_states").$type<string[]>().default([]),
}, (table) => [
  index("idx_users_email").on(table.email),
  index("idx_users_mobile").on(table.mobile),
  index("idx_users_pan_number").on(table.panNumber),
]);

export const userTrustedDevices = pgTable("user_trusted_devices", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  deviceTokenHash: text("device_token_hash").notNull(),
  deviceName: varchar("device_name"),
  userAgent: text("user_agent"),
  ipAddress: varchar("ip_address"),
  trustedAt: timestamp("trusted_at").defaultNow(),
  lastSeenAt: timestamp("last_seen_at").defaultNow(),
  revokedAt: timestamp("revoked_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => [
  uniqueIndex("idx_user_trusted_devices_token").on(table.deviceTokenHash),
  index("idx_user_trusted_devices_user").on(table.userId),
  index("idx_user_trusted_devices_revoked").on(table.revokedAt),
]);

export const userProfiles = pgTable("user_profiles", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").references(() => users.id).notNull().unique(),
  clientType: varchar("client_type").default("individual"),
  entityType: varchar("entity_type"),
  firstName: varchar("first_name"),
  middleName: varchar("middle_name"),
  lastName: varchar("last_name"),
  gender: varchar("gender"),
  companyName: varchar("company_name"),
  entityRegistrationNumber: varchar("entity_registration_number"),
  incorporationDate: date("incorporation_date"),
  businessNature: varchar("business_nature"),
  companyPanNumber: varchar("company_pan_number"),
  authorizedPersons: jsonb("authorized_persons").default([]),
  boardOfDirectors: jsonb("board_of_directors").default([]),
  beneficialOwners: jsonb("beneficial_owners").default([]),
  residentStatus: varchar("resident_status").default("resident_indian"),
  nriSubType: varchar("nri_sub_type"),
  countryOfResidence: varchar("country_of_residence").default("India"),
  countryOfCitizenship: varchar("country_of_citizenship").default("India"),
  passportCountry: varchar("passport_country"),
  visaType: varchar("visa_type"),
  permanentResidenceStatus: varchar("permanent_residence_status"),
  nriExchangeRate: varchar("nri_exchange_rate"),
  nriRepatriationType: varchar("nri_repatriation_type"),
  overseasBankDetails: jsonb("overseas_bank_details"),
  localGuardianDetails: text("local_guardian_details"),
  panNumber: varchar("pan_number"),
  aadharNumber: varchar("aadhar_number"),
  passportNumber: varchar("passport_number"),
  drivingLicense: varchar("driving_license"),
  voterIdNumber: varchar("voter_id_number"),
  dateOfBirth: varchar("date_of_birth"),
  nationality: varchar("nationality"),
  fatherName: varchar("father_name"),
  motherName: varchar("mother_name"),
  spouseName: varchar("spouse_name"),
  maritalStatus: varchar("marital_status"),
  address: text("address"),
  city: varchar("city"),
  state: varchar("state"),
  pincode: varchar("pincode"),
  country: varchar("country"),
  occupation: varchar("occupation"),
  annualIncome: decimal("annual_income", { precision: 15, scale: 2 }),
  investmentExperience: varchar("investment_experience"),
  riskTolerance: varchar("risk_tolerance"),
  bankAccountNumber: varchar("bank_account_number"),
  ifscCode: varchar("ifsc_code"),
  nomineeDetails: text("nominee_details"),
  nomineeRelation: varchar("nominee_relation"),
  euinNumber: varchar("euin_number"),
  arnCode: varchar("arn_code"),
  amcCode: varchar("amc_code"),
  distributorId: varchar("distributor_id"),
  isAgent: boolean("is_agent").default(false),
  agentType: varchar("agent_type"),
  enableCamsApi: boolean("enable_cams_api").default(false),
  enableKfintechApi: boolean("enable_kfintech_api").default(false),
  enableNsdlApi: boolean("enable_nsdl_api").default(false),
  enableCdslApi: boolean("enable_cdsl_api").default(false),
  preferredCamsRegistration: boolean("preferred_cams_registration").default(false),
  preferredKfintechRegistration: boolean("preferred_kfintech_registration").default(false),
  preferredNsdlRegistration: boolean("preferred_nsdl_registration").default(false),
  preferredCdslRegistration: boolean("preferred_cdsl_registration").default(false),
  fatcaStatus: varchar("fatca_status"),
  fatcaDeclarationDate: timestamp("fatca_declaration_date"),
  fatcaTinNumber: varchar("fatca_tin_number"),
  fatcaCountryOfTaxResidence: varchar("fatca_country_of_tax_residence"),
  fatcaReasonCode: varchar("fatca_reason_code"),
  fatcaW8BenStatus: varchar("fatca_w8_ben_status"),
  fatcaW9Status: varchar("fatca_w9_status"),
  fatcaTaxpayerIdType: varchar("fatca_taxpayer_id_type"),
  pepStatus: varchar("pep_status").default("N"),
  pepRelatedPersonStatus: varchar("pep_related_person_status").default("N"),
  pepDetails: text("pep_details"),
  pepCountry: varchar("pep_country"),
  pepPosition: varchar("pep_position"),
  pepRelationshipType: varchar("pep_relationship_type"),
  visaStatus: varchar("visa_status"),
  amlStatus: varchar("aml_status").default("clear"),
  amlLastChecked: timestamp("aml_last_checked"),
  amlRiskScore: integer("aml_risk_score").default(0),
  sanctionListStatus: varchar("sanction_list_status").default("clear"),
  sanctionListLastChecked: timestamp("sanction_list_last_checked"),
  profileCompleteness: integer("profile_completeness").default(0),
  isProfileCompleted: boolean("is_profile_completed").default(false),
  profileCompletedAt: timestamp("profile_completed_at"),
  videoKycStatus: varchar("video_kyc_status"),
  videoKycExpiryDate: timestamp("video_kyc_expiry_date"),
  kycTier: varchar("kyc_tier").default("standard"),
  kycLevel: varchar("kyc_level").default("0"),
  panVerifiedViaSandbox: boolean("pan_verified_via_sandbox").default(false),
  panSandboxStatus: varchar("pan_sandbox_status"),
  panVerifiedViaSmartKyc: boolean("pan_verified_via_smart_kyc").default(false),
  aadhaarVerifiedViaSmartKyc: boolean("aadhaar_verified_via_smart_kyc").default(false),
  kraVerifiedViaProtean: boolean("kra_verified_via_protean").default(false),
  videoKycCompleted: boolean("video_kyc_completed").default(false),
  videoKycCompletedDate: timestamp("video_kyc_completed_date"),
  videoKycCompletedAt: timestamp("video_kyc_completed_at"),
  faceToFaceVerificationCompleted: boolean("face_to_face_verification_completed").default(false),
  faceToFaceVerificationDate: timestamp("face_to_face_verification_date"),
  ckycFetchedViaAuthBridge: boolean("ckyc_fetched_via_auth_bridge").default(false),
  ckycAuthBridgeStatus: varchar("ckyc_auth_bridge_status"),
  ckycAuthBridgeResponse: jsonb("ckyc_auth_bridge_response"),
  kycLevelUpgradedAt: timestamp("kyc_level_upgraded_at"),
  kycTierUpgradedAt: timestamp("kyc_tier_upgraded_at"),
  isHighRiskCustomer: boolean("is_high_risk_customer").default(false),
  netWorthAmount: decimal("net_worth_amount", { precision: 15, scale: 2 }),
  investorType: varchar("investor_type"),
  accreditedInvestorStatus: varchar("accredited_investor_status").default("none"),
  accreditedInvestorExpiryDate: timestamp("accredited_investor_expiry_date"),
  accreditedInvestorType: varchar("accredited_investor_type"),
  annualIncomeAmount: decimal("annual_income_amount", { precision: 15, scale: 2 }),
  incomeProofDocuments: jsonb("income_proof_documents").default([]),
  netWorthExcludingResidence: decimal("net_worth_excluding_residence", { precision: 15, scale: 2 }),
  caCertificateUrl: varchar("ca_certificate_url"),
  portfolioValueAmount: decimal("portfolio_value_amount", { precision: 15, scale: 2 }),
  portfolioStatementUrl: varchar("portfolio_statement_url"),
  professionalQualification: varchar("professional_qualification"),
  professionalQualificationVerified: boolean("professional_qualification_verified").default(false),
  professionalExperienceYears: integer("professional_experience_years"),
  minorIdentity: jsonb("minor_identity"), // For custodial accounts: {given_name, family_name, date_of_birth, tax_id, tax_id_type, country_of_citizenship}
  
  // Financial Profile for Options Approval
  netWorth: decimal("net_worth", { precision: 15, scale: 2 }),
  liquidNetWorth: decimal("liquid_net_worth", { precision: 15, scale: 2 }),
  liquidityNeeds: varchar("liquidity_needs"), // 'none', 'low', 'medium', 'high'
  investmentRiskTolerance: varchar("investment_risk_tolerance"), // 'low', 'medium', 'high'
  investmentObjective: varchar("investment_objective"), // 'speculation', 'income', 'capital_appreciation'
  investmentTimeHorizon: varchar("investment_time_horizon"), // 'short', 'medium', 'long'
  numberOfDependents: integer("number_of_dependents"),

  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type UserTrustedDevice = typeof userTrustedDevices.$inferSelect;
export type InsertUserTrustedDevice = typeof userTrustedDevices.$inferInsert;

export const userBankAccounts = pgTable("user_bank_accounts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").references(() => users.id),
  prospectId: varchar("prospect_id"),
  createdByAgentId: varchar("created_by_agent_id").references(() => users.id),
  bankName: varchar("bank_name").notNull(),
  accountNumber: varchar("account_number").notNull(),
  ifscCode: varchar("ifsc_code").notNull(),
  branchName: varchar("branch_name"),
  accountType: varchar("account_type").default("savings"),
  accountHolderName: varchar("account_holder_name"),
  isDefaultForMutualFunds: boolean("is_default_for_mutual_funds").default(false),
  isPrimary: boolean("is_primary").default(false),
  isActive: boolean("is_active").default(true),
  isVerified: boolean("is_verified").default(false),
  verificationStatus: varchar("verification_status").default("pending"),
  verificationDate: timestamp("verification_date"),
  pennyDropTransactionId: varchar("penny_drop_transaction_id"),
  pennyDropAmount: decimal("penny_drop_amount", { precision: 10, scale: 2 }),
  nameMatchScore: integer("name_match_score"),
  bankAccountStatus: varchar("bank_account_status"),
  verificationMethod: varchar("verification_method").default("pending"),
  verificationAttempts: integer("verification_attempts").default(0),
  lastVerificationAttempt: timestamp("last_verification_attempt"),
  providerResponse: jsonb("provider_response"),
  verifiedAccountHolderName: varchar("verified_account_holder_name"),
  regulatoryMetadata: jsonb("regulatory_metadata"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const userDematAccounts = pgTable("user_demat_accounts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").references(() => users.id),
  prospectId: varchar("prospect_id"),
  createdByAgentId: varchar("created_by_agent_id").references(() => users.id),
  dematAccountNumber: varchar("demat_account_number").notNull(),
  dematDpId: varchar("demat_dp_id").notNull(),
  dematDpName: varchar("demat_dp_name").notNull(),
  depositoryType: varchar("depository_type").notNull(),
  accountHolderName: varchar("account_holder_name").notNull(),
  nsdlClientId: varchar("nsdl_client_id"),
  cdslBoId: varchar("cdsl_bo_id"),
  tradingAccountNumber: varchar("trading_account_number"),
  brokerName: varchar("broker_name"),
  panNumber: varchar("pan_number"),
  isDefaultForEquityTransactions: boolean("is_default_for_equity_transactions").default(false),
  isDefaultForMutualFundTransactions: boolean("is_default_for_mutual_fund_transactions").default(false),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const platformSubscriptions = pgTable("platform_subscriptions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  planTier: varchar("plan_tier").notNull(),
  billingCycle: varchar("billing_cycle").notNull(),
  amountPaise: integer("amount_paise").notNull(),
  currency: varchar("currency").default("INR").notNull(),
  cashfreeOrderId: varchar("cashfree_order_id"),
  cashfreePaymentId: varchar("cashfree_payment_id"),
  cashfreePaymentSessionId: varchar("cashfree_payment_session_id"),
  status: varchar("status").default("pending").notNull(),
  startsAt: timestamp("starts_at"),
  expiresAt: timestamp("expires_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});


// --- Alpaca Integrations Tables ---

export const alpacaAccounts = pgTable("alpaca_accounts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  alpacaAccountId: varchar("alpaca_account_id").notNull().unique(),
  status: varchar("status").notNull(),
  accountNumber: varchar("account_number"),
  currency: varchar("currency").default("USD"),
  cryptoStatus: varchar("crypto_status"),
  buyingPower: decimal("buying_power", { precision: 15, scale: 2 }),
  cash: decimal("cash", { precision: 15, scale: 2 }),
  portfolioValue: decimal("portfolio_value", { precision: 15, scale: 2 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const alpacaOrders = pgTable("alpaca_orders", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  alpacaAccountId: varchar("alpaca_account_id").notNull(),
  providerOrderId: varchar("provider_order_id").notNull().unique(),
  clientOrderId: varchar("client_order_id").notNull().unique(),
  symbol: varchar("symbol").notNull(),
  qty: decimal("qty", { precision: 15, scale: 4 }),
  notional: decimal("notional", { precision: 15, scale: 2 }),
  side: varchar("side").notNull(), // 'buy' | 'sell'
  type: varchar("type").notNull(), // 'market' | 'limit'
  timeInForce: varchar("time_in_force").notNull(), // 'day' | 'gtc'
  status: varchar("status").notNull(), // 'new', 'partially_filled', 'filled', 'done_for_day', 'canceled', 'expired', 'replaced', 'pending_cancel', 'pending_replace', 'accepted', 'pending_new', 'accepted_for_bidding', 'stopped', 'rejected', 'suspended', 'calculated'
  filledQty: decimal("filled_qty", { precision: 15, scale: 4 }),
  filledAvgPrice: decimal("filled_avg_price", { precision: 15, scale: 2 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const alpacaPositions = pgTable("alpaca_positions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  alpacaAccountId: varchar("alpaca_account_id").notNull(),
  symbol: varchar("symbol").notNull(),
  qty: decimal("qty", { precision: 15, scale: 4 }).notNull(),
  avgEntryPrice: decimal("avg_entry_price", { precision: 15, scale: 2 }).notNull(),
  currentPrice: decimal("current_price", { precision: 15, scale: 2 }).notNull(),
  marketValue: decimal("market_value", { precision: 15, scale: 2 }).notNull(),
  unrealizedPl: decimal("unrealized_pl", { precision: 15, scale: 2 }).notNull(),
  unrealizedPlpc: decimal("unrealized_plpc", { precision: 15, scale: 4 }).notNull(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const alpacaTradeLogs = pgTable("alpaca_trade_logs", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  alpacaAccountId: varchar("alpaca_account_id").notNull(),
  symbol: varchar("symbol").notNull(),
  side: varchar("side").notNull(),
  quantity: decimal("quantity", { precision: 15, scale: 4 }),
  notional: decimal("notional", { precision: 15, scale: 2 }),
  status: varchar("status").notNull(), // 'success', 'failed', 'rejected', 'queued'
  providerOrderId: varchar("provider_order_id"),
  commission: decimal("commission", { precision: 12, scale: 2 }).default("0.00"),
  errorMessage: text("error_message"),
  timestamp: timestamp("timestamp").defaultNow(),
});

// Zod schemas for Alpaca Tables
export const insertAlpacaAccountSchema = createInsertSchema(alpacaAccounts).omit({ id: true, createdAt: true, updatedAt: true });
export const insertAlpacaOrderSchema = createInsertSchema(alpacaOrders).omit({ id: true, createdAt: true, updatedAt: true });
export const insertAlpacaPositionSchema = createInsertSchema(alpacaPositions).omit({ id: true, updatedAt: true });
export const insertAlpacaTradeLogSchema = createInsertSchema(alpacaTradeLogs).omit({ id: true, timestamp: true });
