import { DriftReport } from "../../services/drift";
import { TaxEstimationContext } from "../../services/tax";

/**
 * Profit-guard context enriched per-holding SELL action.
 * Surfaces the notional profit at risk and tax/deferral analysis
 * so the advisor UI can show a precise "sell now vs defer" breakdown.
 */
export interface ProfitGuardContext {
  /** Actual unrealized gain at risk (₹). Null if lot data unavailable — falls back to estimate. */
  unrealizedGainRs: number | null;
  /**
   * Estimated tax if the SELL executes today.
   * STCG = 20% (equity < 12m) | LTCG = 12.5% (equity ≥ 12m).
   */
  taxIfSoldNow: number;
  /**
   * Estimated tax if the SELL is deferred until the LTCG threshold is crossed.
   * = 0 if already in LTCG territory. Relevant only when holdingPeriodDays < threshold.
   */
  taxIfDeferredToLtcg: number;
  /**
   * = taxIfSoldNow − taxIfDeferredToLtcg.
   * Positive value → defer recommended (deferral saves this much in tax).
   */
  taxSavingByDeferral: number;
  /** Exit load cost (₹). 0 for stocks/ETFs; non-zero for early MF redemptions. */
  exitLoadRs: number;
  /** Holding period in calendar days (based on earliest lot purchase date). */
  holdingPeriodDays: number | null;
  /**
   * Engine recommendation for this specific SELL action.
   * sell_now     → no profit-guard triggered
   * defer_to_ltcg → within maturity window; defer to save STCG→LTCG tax
   * partial_sell  → sell only the portion already in LTCG; defer the rest
   * cash_deploy   → friction exceeds benefit; use new SIP instead of selling
   */
  recommendation: "sell_now" | "defer_to_ltcg" | "partial_sell" | "cash_deploy";
  /** Human-readable rationale shown to advisor and client. */
  reasoning: string;
}

export interface RebalanceAction {
  action: "BUY" | "SELL";
  asset: string;
  quantity_proxy: number; // Abstraction for fractional shares / lot size logic
  reason: string;
  /** Only present on SELL actions — profit-guard analysis for this holding. */
  profitGuard?: ProfitGuardContext;
}

export interface RebalancePlan {
  plan_id: string;
  actions: RebalanceAction[];
  estimated_cost: number;
}

// ── Finance Act 2024 constants (mirrors rebalancing-engine.ts) ─────────────────
const EQUITY_STCG_RATE = 0.20;  // 20% flat (s.111A, amended Jul 2024)
const EQUITY_LTCG_RATE = 0.125; // 12.5% flat (s.112A, amended Jul 2024)
// LTCG holding thresholds in days
const EQUITY_LTCG_DAYS  = 365;
const DEBT_LTCG_DAYS    = 730; // 2 years for debt (Finance Act 2024)
const GOLD_REIT_LTCG_DAYS = 730; // 2 years for Gold/REIT/InvIT

export class RebalanceOptimizer {
  /**
   * Translates the Drift matrix generated by the DriftDetectionEngine into an
   * absolute BUY/SELL sequence plan targeting neutralized allocations.
   *
   * Phase 2 improvement: each SELL action now includes a profitGuard block with:
   *   - Actual unrealized gain (from lot data if available, else ±15% proxy)
   *   - Correct STCG/LTCG classification based on actual holding period
   *   - Tax saving from deferring to LTCG threshold
   *   - Exit load cost
   *   - Actionable recommendation: sell_now | defer_to_ltcg | partial_sell | cash_deploy
   *
   * @param driftData           - Drift report from DriftDetectionEngine
   * @param totalPortfolioValue - Total portfolio value in ₹
   */
  public generateOptimizedPlan(
    driftData: DriftReport,
    totalPortfolioValue: number,
  ): { plan: RebalancePlan; taxContexts: TaxEstimationContext[] } {
    const actions: RebalanceAction[] = [];
    const taxContexts: TaxEstimationContext[] = [];
    let transactionFees = 0;

    // A standard proxy transaction fee (e.g. standard brokerage flat fee)
    const TX_FEE_PROXY = 2.5;

    // Sort by largest absolute drift magnitude to prioritize heaviest trades first
    const sortedDrift = driftData.drifting_assets.sort(
      (a, b) => Math.abs(b.delta) - Math.abs(a.delta),
    );

    for (const drift of sortedDrift) {
      if (Math.abs(drift.delta) < 0.01) continue; // Skip micro-fractions < 1%

      const monetaryShift = Math.abs(drift.delta) * totalPortfolioValue;

      if (drift.delta > 0) {
        // Current > Target → SELL (overweight)

        // ── Profit-guard: determine actual holding period and gains ──────────────
        // drift.holdingPeriodDays and drift.unrealizedGain are populated by the
        // DriftEngine when lot data is available (Phase 2+). Fall back to estimates
        // if lot enrichment is unavailable (Phase 1 compat).
        const holdingPeriodDays: number | null = (drift as any).holdingPeriodDays ?? null;
        const actualGain: number | null       = (drift as any).unrealizedGain    ?? null;
        const exitLoadRs: number              = (drift as any).exitLoadRs         ?? 0;
        const assetClass: string              = (drift as any).assetClass         ?? "equity";

        // Determine LTCG threshold for this asset class
        const ltcgDays =
          assetClass === "debt" ? DEBT_LTCG_DAYS :
          ["gold", "reit", "invit"].includes(assetClass) ? GOLD_REIT_LTCG_DAYS :
          EQUITY_LTCG_DAYS;

        // Determine STCG vs LTCG using actual holding period if known
        const isLongTerm =
          holdingPeriodDays != null
            ? holdingPeriodDays >= ltcgDays
            : false; // Conservative fallback: assume STCG until lot data confirms LTCG

        // Actual or proxy gain
        // Phase 1 proxy: 15% of trade value (conservative)
        // Phase 2+: use unrealizedGain from holdingLotsV2 via DriftEngine enrichment
        const taxableGain = actualGain !== null ? actualGain : monetaryShift * 0.15;

        // Tax if sold NOW (correct STCG/LTCG per Finance Act 2024)
        const stcgRate = assetClass === "equity" ? EQUITY_STCG_RATE : 0.30; // slab 30%
        const ltcgRate = EQUITY_LTCG_RATE; // 12.5% across equity/debt/gold post-Jul 2024
        const taxIfSoldNow = taxableGain * (isLongTerm ? ltcgRate : stcgRate);

        // Tax if deferred to LTCG threshold (only applicable when currently STCG)
        const taxIfDeferredToLtcg = isLongTerm ? taxIfSoldNow : taxableGain * ltcgRate;

        // Tax saving from deferral (0 if already LTCG)
        const taxSavingByDeferral = Math.max(0, taxIfSoldNow - taxIfDeferredToLtcg);

        // Days remaining to LTCG threshold (0 if already crossed)
        const daysToLtcg =
          holdingPeriodDays != null
            ? Math.max(0, ltcgDays - holdingPeriodDays)
            : null;

        // Profit-guard: pick recommendation
        // LTCG maturity window: 60 days before 1yr/2yr mark → defer
        const MATURITY_BUFFER_DAYS = 60;
        const withinMaturityWindow =
          daysToLtcg != null && daysToLtcg > 0 && daysToLtcg <= MATURITY_BUFFER_DAYS;

        // Friction-to-benefit: if tax+exit_load > 70% of drift benefit → cash deploy
        const frictionCost  = taxIfSoldNow + exitLoadRs;
        const rebalBenefit  = monetaryShift * 0.075; // proxy: 7.5% alpha recovery on drift
        const frictionRatio = rebalBenefit > 0 ? frictionCost / rebalBenefit : 0;
        const highFriction  = frictionRatio > 0.70;

        let recommendation: ProfitGuardContext["recommendation"];
        let reasoning: string;

        if (withinMaturityWindow && taxSavingByDeferral > 0) {
          recommendation = "defer_to_ltcg";
          reasoning = `Holding matures to LTCG in ${daysToLtcg} day(s). Deferring saves ₹${Math.round(taxSavingByDeferral).toLocaleString("en-IN")} in tax (STCG ${stcgRate * 100}% → LTCG ${ltcgRate * 100}%).`;
        } else if (highFriction) {
          recommendation = "cash_deploy";
          reasoning = `Friction cost (tax ₹${Math.round(taxIfSoldNow).toLocaleString("en-IN")} + exit load ₹${Math.round(exitLoadRs).toLocaleString("en-IN")}) = ${Math.round(frictionRatio * 100)}% of rebalancing benefit. Direct new SIP into underweight assets instead.`;
        } else if (exitLoadRs > 0) {
          recommendation = "partial_sell";
          reasoning = `Exit load ₹${Math.round(exitLoadRs).toLocaleString("en-IN")} applies. Consider partial sell of LTCG lots only; defer STCG portion until load-free.`;
        } else {
          recommendation = "sell_now";
          reasoning = isLongTerm
            ? `Holding is in LTCG territory (${holdingPeriodDays} days held). Tax = ${ltcgRate * 100}% on ₹${Math.round(taxableGain).toLocaleString("en-IN")} gain. Proceed.`
            : `Sell now — friction cost is within acceptable range (${Math.round(frictionRatio * 100)}% of benefit).`;
        }

        const profitGuard: ProfitGuardContext = {
          unrealizedGainRs: actualGain !== null ? Math.round(actualGain) : null,
          taxIfSoldNow:      Math.round(taxIfSoldNow),
          taxIfDeferredToLtcg: Math.round(taxIfDeferredToLtcg),
          taxSavingByDeferral: Math.round(taxSavingByDeferral),
          exitLoadRs:        Math.round(exitLoadRs),
          holdingPeriodDays,
          recommendation,
          reasoning,
        };

        actions.push({
          action: "SELL",
          asset: drift.asset,
          quantity_proxy: Math.round(monetaryShift),
          reason: `Asset overweight by ${(drift.delta * 100).toFixed(2)}%`,
          profitGuard,
        });

        // Tax context: now uses actual STCG/LTCG flag and real gain estimate
        taxContexts.push({
          action: "SELL",
          asset: drift.asset,
          quantity: Math.round(monetaryShift),
          estimated_gain_val: Math.round(taxableGain),
          is_long_term: isLongTerm, // ← was always false; now correctly derived
        });

        transactionFees += TX_FEE_PROXY;
      } else {
        // Current < Target → BUY (underweight)
        actions.push({
          action: "BUY",
          asset: drift.asset,
          quantity_proxy: Math.round(monetaryShift),
          reason: `Asset underweight by ${(drift.delta * -100).toFixed(2)}%`,
        });

        transactionFees += TX_FEE_PROXY;
      }
    }

    const plan: RebalancePlan = {
      plan_id: `rebal_${Date.now().toString(36)}_${process.hrtime.bigint().toString(36).slice(-6)}`,
      actions: actions,
      estimated_cost: transactionFees,
    };

    return { plan, taxContexts };
  }
}

export const rebalanceOptimizer = new RebalanceOptimizer();
