import { DriftReport } from "../../services/drift";
import { TaxEstimationContext } from "../../services/tax";

/**
 * Profit-guard context enriched per-holding SELL action.
 * Surfaces the notional profit at risk and tax/deferral analysis
 * so the advisor UI can show a precise "sell now vs defer" breakdown.
 */
export interface ProfitGuardContext {
  /** Actual unrealized gain at risk (₹). Null if lot data unavailable — falls back to estimate. */
  unrealizedGainRs: number | null;
  /**
   * Estimated tax if the SELL executes today.
   * STCG = 20% (equity < 12m) | LTCG = 12.5% (equity ≥ 12m).
   */
  taxIfSoldNow: number;
  /**
   * Estimated tax if the SELL is deferred until the LTCG threshold is crossed.
   * = 0 if already in LTCG territory. Relevant only when holdingPeriodDays < threshold.
   */
  taxIfDeferredToLtcg: number;
  /**
   * = taxIfSoldNow − taxIfDeferredToLtcg.
   * Positive value → defer recommended (deferral saves this much in tax).
   */
  taxSavingByDeferral: number;
  /** Exit load cost (₹). 0 for stocks/ETFs; non-zero for early MF redemptions. */
  exitLoadRs: number;
  /** Holding period in calendar days (based on earliest lot purchase date). */
  holdingPeriodDays: number | null;
  /**
   * Engine recommendation for this specific SELL action.
   * sell_now     → no profit-guard triggered
   * defer_to_ltcg → within maturity window; defer to save STCG→LTCG tax
   * partial_sell  → sell only the portion already in LTCG; defer the rest
   * cash_deploy   → friction exceeds benefit; use new SIP instead of selling
   */
  recommendation: "sell_now" | "defer_to_ltcg" | "partial_sell" | "cash_deploy";
  /** Human-readable rationale shown to advisor and client. */
  reasoning: string;
}

export interface RebalanceAction {
  action: "BUY" | "SELL";
  asset: string;
  quantity_proxy: number; // Abstraction for fractional shares / lot size logic
  reason: string;
  /** Only present on SELL actions — profit-guard analysis for this holding. */
  profitGuard?: ProfitGuardContext;
}

export interface TaxLossHarvestOpportunity {
  asset: string;
  unrealizedLossRs: number;
  holdingPeriodDays: number | null;
  lossType: "STCL" | "LTCL";
  canOffset: "STCG_AND_LTCG" | "LTCG_ONLY";
  eligibleOffsetAmountRs: number;
  potentialTaxSavedRs: number;
  recommendation: "harvest_loss_now" | "hold";
  reasoning: string;
}

export interface PassiveInflowAllocation {
  asset: string;
  category: string;
  currentWeight: number; // in %
  targetWeight: number;  // in %
  deficitWeight: number; // in %
  allocatedInflowRs: number;
  newWeightAfterInflow: number; // in %
}

export interface PassiveInflowPlan {
  inflowAmountRs: number;
  allocations: PassiveInflowAllocation[];
  initialDriftScore: number;
  projectedDriftScore: number;
  driftReductionPct: number;
  taxSavedVsSellingRs: number;
  zeroSellExecuted: true;
}

export interface RebalancePlan {
  plan_id: string;
  actions: RebalanceAction[];
  estimated_cost: number;
  totalTaxIfSoldNow?: number;
  taxLossHarvestOpportunities?: TaxLossHarvestOpportunity[];
  netTaxPayableAfterHarvest?: number;
  passiveInflowPlan?: PassiveInflowPlan;
}

// ── Finance Act 2024 constants (mirrors rebalancing-engine.ts) ─────────────────
const EQUITY_STCG_RATE = 0.20;  // 20% flat (s.111A, amended Jul 2024)
const EQUITY_LTCG_RATE = 0.125; // 12.5% flat (s.112A, amended Jul 2024)
// LTCG holding thresholds in days
const EQUITY_LTCG_DAYS  = 365;
const DEBT_LTCG_DAYS    = 730; // 2 years for debt (Finance Act 2024)
const GOLD_REIT_LTCG_DAYS = 730; // 2 years for Gold/REIT/InvIT

export class RebalanceOptimizer {
  /**
   * Translates the Drift matrix generated by the DriftDetectionEngine into an
   * absolute BUY/SELL sequence plan targeting neutralized allocations.
   *
   * Phase 2 improvement: each SELL action now includes a profitGuard block with:
   *   - Actual unrealized gain (from lot data if available, else ±15% proxy)
   *   - Correct STCG/LTCG classification based on actual holding period
   *   - Tax saving from deferring to LTCG threshold
   *   - Exit load cost
   *   - Actionable recommendation: sell_now | defer_to_ltcg | partial_sell | cash_deploy
   *
   * @param driftData           - Drift report from DriftDetectionEngine
   * @param totalPortfolioValue - Total portfolio value in ₹
   */
  public generateOptimizedPlan(
    driftData: DriftReport,
    totalPortfolioValue: number,
  ): { plan: RebalancePlan; taxContexts: TaxEstimationContext[] } {
    const actions: RebalanceAction[] = [];
    const taxContexts: TaxEstimationContext[] = [];
    let transactionFees = 0;

    // A standard proxy transaction fee (e.g. standard brokerage flat fee)
    const TX_FEE_PROXY = 2.5;

    // Sort by largest absolute drift magnitude to prioritize heaviest trades first
    const sortedDrift = driftData.drifting_assets.sort(
      (a, b) => Math.abs(b.delta) - Math.abs(a.delta),
    );

    for (const drift of sortedDrift) {
      if (Math.abs(drift.delta) < 0.01) continue; // Skip micro-fractions < 1%

      const monetaryShift = Math.abs(drift.delta) * totalPortfolioValue;

      if (drift.delta > 0) {
        // Current > Target → SELL (overweight)

        // ── Profit-guard: determine actual holding period and gains ──────────────
        // drift.holdingPeriodDays and drift.unrealizedGain are populated by the
        // DriftEngine when lot data is available (Phase 2+). Fall back to estimates
        // if lot enrichment is unavailable (Phase 1 compat).
        const holdingPeriodDays: number | null = (drift as any).holdingPeriodDays ?? null;
        const actualGain: number | null       = (drift as any).unrealizedGain    ?? null;
        const exitLoadRs: number              = (drift as any).exitLoadRs         ?? 0;
        const assetClass: string              = (drift as any).assetClass         ?? "equity";

        // Determine LTCG threshold for this asset class
        const ltcgDays =
          assetClass === "debt" ? DEBT_LTCG_DAYS :
          ["gold", "reit", "invit"].includes(assetClass) ? GOLD_REIT_LTCG_DAYS :
          EQUITY_LTCG_DAYS;

        // Determine STCG vs LTCG using actual holding period if known
        const isLongTerm =
          holdingPeriodDays != null
            ? holdingPeriodDays >= ltcgDays
            : false; // Conservative fallback: assume STCG until lot data confirms LTCG

        // Actual or proxy gain
        // Phase 1 proxy: 15% of trade value (conservative)
        // Phase 2+: use unrealizedGain from holdingLotsV2 via DriftEngine enrichment
        const taxableGain = actualGain !== null ? actualGain : monetaryShift * 0.15;

        // Tax if sold NOW (correct STCG/LTCG per Finance Act 2024)
        const stcgRate = assetClass === "equity" ? EQUITY_STCG_RATE : 0.30; // slab 30%
        const ltcgRate = EQUITY_LTCG_RATE; // 12.5% across equity/debt/gold post-Jul 2024
        const taxIfSoldNow = taxableGain * (isLongTerm ? ltcgRate : stcgRate);

        // Tax if deferred to LTCG threshold (only applicable when currently STCG)
        const taxIfDeferredToLtcg = isLongTerm ? taxIfSoldNow : taxableGain * ltcgRate;

        // Tax saving from deferral (0 if already LTCG)
        const taxSavingByDeferral = Math.max(0, taxIfSoldNow - taxIfDeferredToLtcg);

        // Days remaining to LTCG threshold (0 if already crossed)
        const daysToLtcg =
          holdingPeriodDays != null
            ? Math.max(0, ltcgDays - holdingPeriodDays)
            : null;

        // Profit-guard: pick recommendation
        // LTCG maturity window: 60 days before 1yr/2yr mark → defer
        const MATURITY_BUFFER_DAYS = 60;
        const withinMaturityWindow =
          daysToLtcg != null && daysToLtcg > 0 && daysToLtcg <= MATURITY_BUFFER_DAYS;

        // Friction-to-benefit: if tax+exit_load > 70% of drift benefit → cash deploy
        const frictionCost  = taxIfSoldNow + exitLoadRs;
        const rebalBenefit  = monetaryShift * 0.075; // proxy: 7.5% alpha recovery on drift
        const frictionRatio = rebalBenefit > 0 ? frictionCost / rebalBenefit : 0;
        const highFriction  = frictionRatio > 0.70;

        let recommendation: ProfitGuardContext["recommendation"];
        let reasoning: string;

        if (withinMaturityWindow && taxSavingByDeferral > 0) {
          recommendation = "defer_to_ltcg";
          reasoning = `Holding matures to LTCG in ${daysToLtcg} day(s). Deferring saves ₹${Math.round(taxSavingByDeferral).toLocaleString("en-IN")} in tax (STCG ${stcgRate * 100}% → LTCG ${ltcgRate * 100}%).`;
        } else if (highFriction) {
          recommendation = "cash_deploy";
          reasoning = `Friction cost (tax ₹${Math.round(taxIfSoldNow).toLocaleString("en-IN")} + exit load ₹${Math.round(exitLoadRs).toLocaleString("en-IN")}) = ${Math.round(frictionRatio * 100)}% of rebalancing benefit. Direct new SIP into underweight assets instead.`;
        } else if (exitLoadRs > 0) {
          recommendation = "partial_sell";
          reasoning = `Exit load ₹${Math.round(exitLoadRs).toLocaleString("en-IN")} applies. Consider partial sell of LTCG lots only; defer STCG portion until load-free.`;
        } else {
          recommendation = "sell_now";
          reasoning = isLongTerm
            ? `Holding is in LTCG territory (${holdingPeriodDays} days held). Tax = ${ltcgRate * 100}% on ₹${Math.round(taxableGain).toLocaleString("en-IN")} gain. Proceed.`
            : `Sell now — friction cost is within acceptable range (${Math.round(frictionRatio * 100)}% of benefit).`;
        }

        const profitGuard: ProfitGuardContext = {
          unrealizedGainRs: actualGain !== null ? Math.round(actualGain) : null,
          taxIfSoldNow:      Math.round(taxIfSoldNow),
          taxIfDeferredToLtcg: Math.round(taxIfDeferredToLtcg),
          taxSavingByDeferral: Math.round(taxSavingByDeferral),
          exitLoadRs:        Math.round(exitLoadRs),
          holdingPeriodDays,
          recommendation,
          reasoning,
        };

        actions.push({
          action: "SELL",
          asset: drift.asset,
          quantity_proxy: Math.round(monetaryShift),
          reason: `Asset overweight by ${(drift.delta * 100).toFixed(2)}%`,
          profitGuard,
        });

        // Tax context: now uses actual STCG/LTCG flag and real gain estimate
        taxContexts.push({
          action: "SELL",
          asset: drift.asset,
          quantity: Math.round(monetaryShift),
          estimated_gain_val: Math.round(taxableGain),
          is_long_term: isLongTerm, // ← was always false; now correctly derived
        });

        transactionFees += TX_FEE_PROXY;
      } else {
        // Current < Target → BUY (underweight)
        actions.push({
          action: "BUY",
          asset: drift.asset,
          quantity_proxy: Math.round(monetaryShift),
          reason: `Asset underweight by ${(drift.delta * -100).toFixed(2)}%`,
        });

        transactionFees += TX_FEE_PROXY;
      }
    }

    // ── Compute Total Tax and Tax-Loss Harvesting Opportunities ─────────────
    const totalTaxIfSoldNow = actions.reduce(
      (sum, act) => sum + (act.profitGuard?.taxIfSoldNow ?? 0),
      0,
    );

    const taxLossHarvestOpportunities: TaxLossHarvestOpportunity[] = [];
    let totalTaxSavedFromHarvest = 0;

    for (const drift of sortedDrift) {
      const actualGain: number | null = (drift as any).unrealizedGain ?? null;
      const holdingPeriodDays: number | null = (drift as any).holdingPeriodDays ?? null;
      const assetClass: string = (drift as any).assetClass ?? "equity";
      const ltcgDays = assetClass === "debt" ? DEBT_LTCG_DAYS : ["gold", "reit"].includes(assetClass) ? GOLD_REIT_LTCG_DAYS : EQUITY_LTCG_DAYS;
      const isLongTerm = holdingPeriodDays != null ? holdingPeriodDays >= ltcgDays : false;

      // Check if holding has an unrealized loss
      if (actualGain != null && actualGain < 0) {
        const loss = Math.abs(actualGain);
        const lossType: "STCL" | "LTCL" = isLongTerm ? "LTCL" : "STCL";
        const canOffset: "STCG_AND_LTCG" | "LTCG_ONLY" = isLongTerm ? "LTCG_ONLY" : "STCG_AND_LTCG";
        const taxRate = isLongTerm ? EQUITY_LTCG_RATE : EQUITY_STCG_RATE;
        const potentialTaxSaved = Math.round(loss * taxRate);

        totalTaxSavedFromHarvest += potentialTaxSaved;

        taxLossHarvestOpportunities.push({
          asset: drift.asset,
          unrealizedLossRs: Math.round(loss),
          holdingPeriodDays,
          lossType,
          canOffset,
          eligibleOffsetAmountRs: Math.round(loss),
          potentialTaxSavedRs: potentialTaxSaved,
          recommendation: "harvest_loss_now",
          reasoning: isLongTerm
            ? `LTCL of ₹${Math.round(loss).toLocaleString("en-IN")} can offset LTCG gains at 12.5% under Sec. 70(3).`
            : `STCL of ₹${Math.round(loss).toLocaleString("en-IN")} can offset both STCG (20%) and LTCG (12.5%) under Sec. 70(2).`,
        });
      }
    }

    const netTaxPayableAfterHarvest = Math.max(0, totalTaxIfSoldNow - totalTaxSavedFromHarvest);

    // Generate passive inflow plan for standard ₹1,00,000 inflow recommendation
    const passiveInflowPlan = this.generatePassiveInflowPlan(
      driftData,
      totalPortfolioValue,
      Math.min(200_000, Math.max(25_000, Math.round(totalPortfolioValue * 0.10))),
    );

    const plan: RebalancePlan = {
      plan_id: `rebal_${Date.now().toString(36)}_${process.hrtime.bigint().toString(36).slice(-6)}`,
      actions: actions,
      estimated_cost: transactionFees,
      totalTaxIfSoldNow: Math.round(totalTaxIfSoldNow),
      taxLossHarvestOpportunities,
      netTaxPayableAfterHarvest: Math.round(netTaxPayableAfterHarvest),
      passiveInflowPlan,
    };

    return { plan, taxContexts };
  }

  /**
   * Generates a "Tax-Zero" Passive Inflow Plan.
   * Directs 100% of new capital (SIP or lumpsum) solely into underweight assets,
   * neutralizing drift without triggering any SELL transactions (zero tax, zero exit load).
   *
   * @param driftData           - Current portfolio drift matrix
   * @param totalPortfolioValue - Current portfolio value (₹)
   * @param inflowAmountRs      - Incoming new capital to deploy (₹)
   */
  public generatePassiveInflowPlan(
    driftData: DriftReport,
    totalPortfolioValue: number,
    inflowAmountRs: number,
  ): PassiveInflowPlan {
    const underweightAssets = driftData.drifting_assets.filter(d => d.delta < 0);
    const totalDeficitWeight = underweightAssets.reduce(
      (sum, d) => sum + Math.abs(d.delta),
      0,
    ) || 1;

    const allocations: PassiveInflowAllocation[] = [];
    let initialDriftSum = 0;
    let projectedDriftSum = 0;
    const newTotalValue = totalPortfolioValue + inflowAmountRs;

    for (const drift of driftData.drifting_assets) {
      const curWeight = (drift.current ?? (drift.target + drift.delta)) * 100;
      const targetWeight = drift.target * 100;
      initialDriftSum += Math.abs(curWeight - targetWeight);

      if (drift.delta < 0) {
        // Underweight asset: allocate proportional share of inflow
        const deficitWeight = Math.abs(drift.delta) * 100;
        const share = Math.abs(drift.delta) / totalDeficitWeight;
        const allocatedInflowRs = Math.round(share * inflowAmountRs);
        const curHoldingValue = (curWeight / 100) * totalPortfolioValue;
        const newHoldingValue = curHoldingValue + allocatedInflowRs;
        const newWeightAfterInflow = parseFloat(((newHoldingValue / newTotalValue) * 100).toFixed(2));

        allocations.push({
          asset: drift.asset,
          category: (drift as any).assetClass ?? "equity",
          currentWeight: parseFloat(curWeight.toFixed(2)),
          targetWeight: parseFloat(targetWeight.toFixed(2)),
          deficitWeight: parseFloat(deficitWeight.toFixed(2)),
          allocatedInflowRs,
          newWeightAfterInflow,
        });

        projectedDriftSum += Math.abs(newWeightAfterInflow - targetWeight);
      } else {
        // Overweight asset: receives 0 inflow, diluted naturally by expanding base
        const curHoldingValue = (curWeight / 100) * totalPortfolioValue;
        const newWeightAfterInflow = (curHoldingValue / newTotalValue) * 100;
        projectedDriftSum += Math.abs(newWeightAfterInflow - targetWeight);
      }
    }

    const initialDriftScore = Math.min(100, Math.round(initialDriftSum * 5));
    const projectedDriftScore = Math.min(100, Math.max(0, Math.round(projectedDriftSum * 5)));
    const driftReductionPct = initialDriftScore > 0
      ? Math.round(((initialDriftScore - projectedDriftScore) / initialDriftScore) * 100)
      : 100;

    // Estimated tax avoided by not selling overweight assets (proxy 15% gain @ 12.5% LTCG)
    const totalOverweightValue = driftData.drifting_assets
      .filter(d => d.delta > 0)
      .reduce((sum, d) => sum + d.delta * totalPortfolioValue, 0);
    const taxSavedVsSellingRs = Math.round(totalOverweightValue * 0.15 * EQUITY_LTCG_RATE);

    return {
      inflowAmountRs,
      allocations,
      initialDriftScore,
      projectedDriftScore,
      driftReductionPct,
      taxSavedVsSellingRs,
      zeroSellExecuted: true,
    };
  }
}

export const rebalanceOptimizer = new RebalanceOptimizer();
