import { DriftReport } from "../../services/drift";
import { TaxEstimationContext } from "../../services/tax";

export interface RebalanceAction {
	action: "BUY" | "SELL";
	asset: string;
	quantity_proxy: number; // Abstraction for fractional shares / lot size logic
	reason: string;
}

export interface RebalancePlan {
	plan_id: string;
	actions: RebalanceAction[];
	estimated_cost: number;
}

export class RebalanceOptimizer {
	/**
	 * Translates the Drift matrix generated by the DriftDetectionEngine into an absolute BUY/SELL sequence plan natively targeting neutralized allocations.
	 */
	public generateOptimizedPlan(
		driftData: DriftReport,
		totalPortfolioValue: number,
	): { plan: RebalancePlan; taxContexts: TaxEstimationContext[] } {
		const actions: RebalanceAction[] = [];
		const taxContexts: TaxEstimationContext[] = [];
		let transactionFees = 0;

		// A standard proxy transaction fee (e.g. standard brokerage flat fee)
		const TX_FEE_PROXY = 2.5;

		// Sort by largest absolute drift magnitude to prioritize heaviest trades first
		const sortedDrift = driftData.drifting_assets.sort(
			(a, b) => Math.abs(b.delta) - Math.abs(a.delta),
		);

		for (const drift of sortedDrift) {
			if (Math.abs(drift.delta) < 0.01) continue; // Skip micro-fractions < 1%

			const monetaryShift = Math.abs(drift.delta) * totalPortfolioValue;

			if (drift.delta > 0) {
				// Current > Target (Overweight -> SELL)
				actions.push({
					action: "SELL",
					asset: drift.asset,
					quantity_proxy: Math.round(monetaryShift), // Mocking $ values as quantity abstraction for Phase 1
					reason: `Asset overweight by ${(drift.delta * 100).toFixed(2)}%`,
				});

				// Add to Tax Context pool. Randomly assigning mock Long/Short term gains for calculation
				taxContexts.push({
					action: "SELL",
					asset: drift.asset,
					quantity: Math.round(monetaryShift),
					estimated_gain_val: monetaryShift * 0.15, // Mocking a 15% profit extraction on the sold amount
					// is_long_term derived from holding period: > 12 months = long-term
					is_long_term: false, // Conservative: classify as short-term (STCG) until actual purchase date is known
				});

				transactionFees += TX_FEE_PROXY;
			} else {
				// Current < Target (Underweight -> BUY)
				actions.push({
					action: "BUY",
					asset: drift.asset,
					quantity_proxy: Math.round(monetaryShift),
					reason: `Asset underweight by ${(drift.delta * -100).toFixed(2)}%`,
				});

				transactionFees += TX_FEE_PROXY;
			}
		}

		const plan: RebalancePlan = {
			plan_id: `rebal_${Date.now().toString(36)}_${process.hrtime.bigint().toString(36).slice(-6)}`,
			actions: actions,
			estimated_cost: transactionFees,
		};

		return { plan, taxContexts };
	}
}

export const rebalanceOptimizer = new RebalanceOptimizer();
