import { z } from "zod";

// ============================================================
// BROWSER-SAFE FORM SCHEMAS
// This file is loaded by the Vite browser build instead of the
// full shared/schema.ts (which includes 32K+ lines of drizzle
// ORM table definitions not needed in the browser).
//
// Rule: Only plain zod schemas here — NO drizzle-orm imports.
// TypeScript types are re-exported as type-only (zero bundle impact).
// ============================================================

// ---- Runtime Zod schemas (5 forms that use these directly) ----

export const insertPartnerSchema = z.object({
  companyName: z.string(),
  contactEmail: z.string(),
  password: z.string(),
  partnerType: z.string(),
  contactPhone: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
  isActive: z.boolean().optional().nullable(),
  isVerified: z.boolean().optional().nullable(),
  permissions: z.unknown().optional().nullable(),
  businessLicense: z.string().optional().nullable(),
  taxId: z.string().optional().nullable(),
  gstin: z.string().optional().nullable(),
  cin: z.string().optional().nullable(),
  commissionRate: z.string().optional().nullable(),
  productTypes: z.array(z.string()).optional().nullable(),
  arnCode: z.string().optional().nullable(),
  euinNumber: z.string().optional().nullable(),
  pospNumber: z.string().optional().nullable(),
  riaNumber: z.string().optional().nullable(),
  dsaCode: z.string().optional().nullable(),
  panNumber: z.string().optional().nullable(),
  aadharNumber: z.string().optional().nullable(),
  bankAccountNumber: z.string().optional().nullable(),
  ifscCode: z.string().optional().nullable(),
  bankAccountHolderName: z.string().optional().nullable(),
  upiId: z.string().optional().nullable(),
  cashfreeVendorId: z.string().optional().nullable(),
  cashfreeVendorStatus: z.string().optional().nullable(),
  cashfreeBankVerified: z.boolean().optional().nullable(),
  cashfreeRegisteredAt: z.date().optional().nullable(),
  commissionTier: z.string().optional().nullable(),
  volumeBonusEnabled: z.boolean().optional().nullable(),
  volumeBonusRate: z.string().optional().nullable(),
  volumeThreshold: z.string().optional().nullable(),
  settlementFrequency: z.string().optional().nullable(),
  settlementDay: z.number().optional().nullable(),
  minSettlementAmount: z.string().optional().nullable(),
  totalClientsReferred: z.number().optional().nullable(),
  activeClientsCount: z.number().optional().nullable(),
  totalCommissionsEarned: z.string().optional().nullable(),
  totalCommissionsPaid: z.string().optional().nullable(),
  pendingCommissions: z.string().optional().nullable(),
  lastSettlementDate: z.date().optional().nullable(),
  icaiMembershipNumber: z.string().optional().nullable(),
  icaiMembershipType: z.string().optional().nullable(),
  caFirmName: z.string().optional().nullable(),
  caFirmRegistrationNumber: z.string().optional().nullable(),
  caSpecializations: z.array(z.string()).optional().nullable(),
  caExperienceYears: z.number().optional().nullable(),
  caQualificationYear: z.number().optional().nullable(),
  caCity: z.string().optional().nullable(),
  caState: z.string().optional().nullable(),
  caAvailability: z.string().optional().nullable(),
  caMaxCasesPerMonth: z.number().optional().nullable(),
  caCurrentActiveCases: z.number().optional().nullable(),
  caCompletedCases: z.number().optional().nullable(),
  caAverageRating: z.string().optional().nullable(),
  caTotalRatings: z.number().optional().nullable(),
  caResponseTime: z.string().optional().nullable(),
  caVerificationStatus: z.string().optional().nullable(),
  caVerifiedAt: z.date().optional().nullable(),
  caVerifiedBy: z.string().optional().nullable(),
  caProfilePhoto: z.string().optional().nullable(),
  caBio: z.string().optional().nullable(),
  parentPartnerId: z.string().optional().nullable(),
  partnerLevel: z.string().optional().nullable(),
  hierarchyPartnerType: z.string().optional().nullable(),
  hierarchyStatus: z.string().optional().nullable(),
  kycStatus: z.string().optional().nullable(),
  approvalStatus: z.string().optional().nullable(),
  agreementId: z.string().optional().nullable(),
  maxDepth: z.number().optional().nullable(),
  createdBy: z.string().optional().nullable(),
});

export const insertAgentSchema = z.object({
  fullName: z.string(),
  email: z.string(),
  userId: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  employeeId: z.string().optional().nullable(),
  arnCode: z.string().optional().nullable(),
  euinNumber: z.string().optional().nullable(),
  pospNumber: z.string().optional().nullable(),
  dsaCode: z.string().optional().nullable(),
  panNumber: z.string().optional().nullable(),
  aadharNumber: z.string().optional().nullable(),
  bankAccountNumber: z.string().optional().nullable(),
  ifscCode: z.string().optional().nullable(),
  upiId: z.string().optional().nullable(),
  agentType: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  isActive: z.boolean().optional().nullable(),
  activeClients: z.number().optional().nullable(),
  totalClients: z.number().optional().nullable(),
  totalRevenue: z.string().optional().nullable(),
  monthlyRevenue: z.string().optional().nullable(),
  totalCommissionsEarned: z.string().optional().nullable(),
  reportingTo: z.string().optional().nullable(),
  teamSize: z.number().optional().nullable(),
  hierarchyLevel: z.number().optional().nullable(),
  joiningDate: z.date().optional().nullable(),
  terminationDate: z.date().optional().nullable(),
  contractType: z.string().optional().nullable(),
  commissionTier: z.string().optional().nullable(),
  baseCommissionRate: z.string().optional().nullable(),
  marketingName: z.string().optional().nullable(),
  marketingDesignation: z.string().optional().nullable(),
  marketingEmail: z.string().optional().nullable(),
  marketingPhone: z.string().optional().nullable(),
});

export const insertSupplierSchema = z.object({
  name: z.string(),
  contactEmail: z.string().optional().nullable(),
  contactPhone: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  productCategories: z.array(z.string()).optional().nullable(),
  performanceRating: z.string().optional().nullable(),
  commissionRate: z.string().optional().nullable(),
  isActive: z.boolean().optional().nullable(),
});

export const insertSellListingSchema = z.object({
  sellerUserId: z.string(),
  companyId: z.string(),
  quantity: z.number(),
  askPrice: z.string(),
  landingPrice: z.string(),
  floorPrice: z.string(),
  status: z.string().optional().nullable(),
  quantityRemaining: z.number().optional().nullable(),
  validUntil: z.date().optional().nullable(),
  autoRenew: z.boolean().optional().nullable(),
  lockInPeriod: z.number().optional().nullable(),
  minimumLotSize: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  kycVerified: z.boolean().optional().nullable(),
  dematVerified: z.boolean().optional().nullable(),
});

export const insertBuyRequestSchema = z.object({
  buyerUserId: z.string(),
  companyId: z.string(),
  quantity: z.number(),
  maxPrice: z.string(),
  targetPrice: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  quantityFilled: z.number().optional().nullable(),
  validUntil: z.date().optional().nullable(),
  preferredLotSize: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  kycVerified: z.boolean().optional().nullable(),
  fundsVerified: z.boolean().optional().nullable(),
});

// ---- TypeScript type re-exports (erased at compile time, zero bundle cost) ----
export type {
  User,
  Portfolio,
  PortfolioHolding,
  AssetAllocation,
  EpfHolding,
  PpfHolding,
  EpsHolding,
  InsuranceHolding,
  NpsAccount,
  ApyAccount,
  FinancialObligation,
  KycFormProgress,
  UnifiedCartItem,
  InsertUnifiedCartItem,
  ProductCategory,
  CartItemStatus,
  CartItemSource,
  UnlistedCompany,
  CompanyFinancials,
  CompanyRatios,
  UnlistedPriceHistory,
  UnlistedDeal,
  SellListing,
  BuyRequest,
  UserAlert,
  AlertHistory,
  AlertTemplate,
  FamilyGroup,
  FamilyMember,
  InsertFamilyMember,
  InsertFamilyDiscussion,
  InsertFamilyGoalContribution,
  UnifiedOrder,
  IpoCompany,
  IpoNews,
  AgentProfile,
  AgentStats,
  AgentPartner,
  AiRecommendationTracking,
  Partner,
  Agent,
  Supplier,
  InsertPartner,
  InsertAgent,
  InsertSupplier,
  InsertSellListing,
  InsertBuyRequest,
} from "./schema";
