import { AlertTriangle, Info, Shield as LucideShield } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from "@/components/ui/accordion";

interface AIAdvisoryDisclosureProps {
	variant?: "compact" | "full" | "inline";
	showSEBIReference?: boolean;
	className?: string;
}

export function AIAdvisoryDisclosure({
	variant = "compact",
	showSEBIReference = true,
	className = "",
}: AIAdvisoryDisclosureProps) {
	if (variant === "inline") {
		return (
			<div
				className={`flex items-center gap-2 text-xs text-muted-foreground ${className}`}
			>
				<AlertTriangle className="h-3 w-3 text-amber-500" />
				<span>
					AI-generated recommendation. Not personalized investment advice. Past
					performance doesn't guarantee future results.
				</span>
			</div>
		);
	}

	if (variant === "compact") {
		return (
			<Alert
				variant="default"
				className={`bg-amber-50 dark:bg-amber-950 border-amber-200 dark:border-amber-800 ${className}`}
			>
				<AlertTriangle className="h-4 w-4 text-amber-600" />
				<AlertTitle className="text-amber-800 dark:text-amber-300 text-sm">
					AI-Generated Recommendation
				</AlertTitle>
				<AlertDescription className="text-amber-700 dark:text-amber-400 text-xs">
					This recommendation is generated by AI/ML models and does not
					constitute personalized investment advice. Investment in securities
					market are subject to market risks. Read all related documents
					carefully before investing.
					{showSEBIReference && (
						<span className="block mt-1 text-[10px] text-amber-600 dark:text-amber-500">
							Ref: SEBI AI/ML Guidelines 2024
						</span>
					)}
				</AlertDescription>
			</Alert>
		);
	}

	return (
		<Accordion type="single" collapsible className={className}>
			<AccordionItem
				value="ai-disclosure"
				className="border-amber-200 dark:border-amber-800"
			>
				<AccordionTrigger className="text-sm hover:no-underline py-2">
					<div className="flex items-center gap-2">
						<LucideShield className="h-4 w-4 text-amber-600" />
						<span className="text-amber-800 dark:text-amber-300">
							AI Advisory Risk Disclosure
						</span>
					</div>
				</AccordionTrigger>
				<AccordionContent>
					<div className="space-y-3 text-sm text-muted-foreground bg-amber-50 dark:bg-amber-950 p-4 rounded-lg">
						<div className="flex items-start gap-2">
							<Info className="h-4 w-4 mt-0.5 text-amber-600 flex-shrink-0" />
							<div>
								<p className="font-medium text-amber-800 dark:text-amber-300">
									About AI-Generated Recommendations
								</p>
								<p className="mt-1">
									This recommendation has been generated using Artificial
									Intelligence and Machine Learning models. These models analyze
									historical data, market trends, and various financial
									indicators to suggest investment options.
								</p>
							</div>
						</div>

						<div className="flex items-start gap-2">
							<AlertTriangle className="h-4 w-4 mt-0.5 text-amber-600 flex-shrink-0" />
							<div>
								<p className="font-medium text-amber-800 dark:text-amber-300">
									Important Disclaimers
								</p>
								<ul className="mt-1 list-disc list-inside space-y-1">
									<li>
										AI recommendations are not personalized investment advice
									</li>
									<li>Past performance does not guarantee future results</li>
									<li>
										Investments in securities market are subject to market risks
									</li>
									<li>
										Please read all scheme related documents carefully before
										investing
									</li>
									<li>
										Consult a SEBI-registered investment adviser for
										personalized advice
									</li>
								</ul>
							</div>
						</div>

						<div className="flex items-start gap-2">
							<LucideShield className="h-4 w-4 mt-0.5 text-amber-600 flex-shrink-0" />
							<div>
								<p className="font-medium text-amber-800 dark:text-amber-300">
									Model Limitations
								</p>
								<ul className="mt-1 list-disc list-inside space-y-1">
									<li>
										AI models may not account for all market conditions or black
										swan events
									</li>
									<li>
										Recommendations are based on available data which may be
										incomplete
									</li>
									<li>
										Models are periodically retrained and results may vary
									</li>
								</ul>
							</div>
						</div>

						{showSEBIReference && (
							<p className="text-xs text-amber-600 dark:text-amber-500 border-t border-amber-200 dark:border-amber-800 pt-2">
								This disclosure is provided in compliance with SEBI Consultation
								Paper on AI/ML 2024 and SEBI (Investment Advisers) Regulations,
								2013.
							</p>
						)}
					</div>
				</AccordionContent>
			</AccordionItem>
		</Accordion>
	);
}

export function AIRecommendationBadge({
	className = "",
}: { className?: string }) {
	return (
		<div
			className={`inline-flex items-center gap-1 px-2 py-0.5 bg-amber-100 dark:bg-amber-900 text-amber-800 dark:text-amber-300 text-xs rounded-full ${className}`}
		>
			<AlertTriangle className="h-3 w-3" />
			<span>AI Generated</span>
		</div>
	);
}

export default AIAdvisoryDisclosure;
