// @ts-nocheck
/**
 * Algo Signal Engine — FintekPro US Trading DSS
 *
 * Purpose:  Compute FASP-AI v1.0 compliant trading signals for US equities.
 * Strategy: Composite (SMA Crossover + RSI Mean Reversion + Momentum), weighted.
 * Inputs:   Symbol list, risk profile, investment horizon, user ID
 * Outputs:  AlgoSignal records persisted to algo_signals table
 *
 * FASP-AI v1.0 constraints:
 *   - AI is Decision Support ONLY. No autonomous execution.
 *   - Every signal includes confidence_score, factors, model_version, timestamp.
 *   - Signals < 60% confidence downgrade to "watch" (no actionable direction).
 *   - Mandatory risk disclaimer on every output.
 *   - All generation events logged via auditLog().
 */
// NOTE: @ts-nocheck maintained for compatibility — targeted type fixes tracked in CC-1 backlog
import { db } from "../db";
import { algoSignals, users } from "@shared/schema";
import { eq, and, inArray, lt, desc, sql } from "drizzle-orm";
import { alpacaMarketDataService } from "./alpaca-market-data-service";
import { auditLog } from "../middleware/audit-trail";
import { logger } from "../logger";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SignalFactors {
	currentPrice: number;
	sma20: number;
	sma50: number;
	rsi14: number;
	volumeRatio: number; // current 5d avg volume / 20d avg volume
	momentum20d: number; // % price change over 20 days
	high20d: number;
	low20d: number;
	atr14: number; // Average True Range — used for target/stop calc
	// individual strategy scores
	smaScore: number; // -1 to +1
	rsiScore: number; // -1 to +1
	momentumScore: number; // -1 to +1
}

export interface SignalResult {
	symbol: string;
	companyName?: string;
	strategy: string;
	signal: "buy" | "sell" | "watch" | "hold";
	confidenceScore: number; // 0–100
	entryPrice: number;
	targetPrice: number;
	stopLossPrice: number;
	suggestedNotional: number; // USD, risk-based sizing
	factors: SignalFactors;
	modelVersion: string;
	disclaimer: string;
	expiresAt: Date;
}

export type RiskProfile =
	| "conservative"
	| "moderate"
	| "aggressive"
	| "very_aggressive";
export type InvestmentHorizon = "short" | "medium" | "long";

const MODEL_VERSION = "algo-v1.0";

const DISCLAIMER =
	"⚠️ This signal is generated by an automated algorithm and is for informational purposes only. " +
	"It does NOT constitute financial advice, a recommendation to buy or sell, or a guarantee of returns. " +
	"Past performance of this signal model does not guarantee future results. " +
	"Market conditions can change rapidly. Always consider your risk profile and consult a SEBI-registered " +
	"Investment Advisor before acting on any signal. Capital is at risk.";

// Risk-based notional position sizing (USD)
const NOTIONAL_BY_RISK: Record<RiskProfile, number> = {
	conservative: 500,
	moderate: 1000,
	aggressive: 2000,
	very_aggressive: 3000,
};

// ─── Core Engine ─────────────────────────────────────────────────────────────

class AlgoSignalEngine {
	private readonly MODEL = MODEL_VERSION;

	/**
	 * Generate signals for a list of symbols.
	 * Persists results to algo_signals table.
	 *
	 * @param symbols      List of US ticker symbols (e.g. ["AAPL", "MSFT"])
	 * @param userId       FintekPro user ID (for per-user signals)
	 * @param riskProfile  User's risk tolerance
	 * @param horizon      Investment horizon
	 * @returns            Generated signal records (unsaved IDs — query DB after)
	 */
	async generateSignals(
		symbols: string[],
		userId: number,
		riskProfile: RiskProfile = "moderate",
		horizon: InvestmentHorizon = "medium",
	): Promise<SignalResult[]> {
		const startMs = Date.now();
		const upperSymbols = [
			...new Set(symbols.map((s) => s.toUpperCase())),
		].slice(0, 20); // cap at 20

		logger.info("[AlgoEngine] Generating signals", {
			userId,
			symbols: upperSymbols,
			riskProfile,
		});

		// Expire any stale pending signals for this user+symbols
		await this._expireStaleSignals(userId, upperSymbols);

		// Fetch 60 days of daily bars (needs SMA-50)
		const end = new Date();
		const start = new Date(end.getTime() - 65 * 24 * 60 * 60 * 1000);
		const barsMap = await alpacaMarketDataService.getBars(
			upperSymbols,
			"1Day",
			start.toISOString().split("T")[0],
			end.toISOString().split("T")[0],
			70,
		);

		const results: SignalResult[] = [];

		for (const symbol of upperSymbols) {
			try {
				const bars = barsMap.get(symbol) || [];
				if (bars.length < 21) {
					logger.warn(
						`[AlgoEngine] Insufficient bars for ${symbol}: ${bars.length}`,
					);
					continue;
				}

				const result = this._computeSignal(symbol, bars, riskProfile);
				if (!result) continue;

				// Persist to DB
				await db.insert(algoSignals).values({
					userId,
					symbol: result.symbol,
					strategy: result.strategy,
					signal: result.signal,
					confidenceScore: result.confidenceScore,
					suggestedNotional: String(result.suggestedNotional),
					entryPrice: String(result.entryPrice),
					targetPrice: String(result.targetPrice),
					stopLossPrice: String(result.stopLossPrice),
					factors: result.factors as any,
					modelVersion: result.modelVersion,
					riskProfile,
					investmentHorizon: horizon,
					status: "pending",
					disclaimer: result.disclaimer,
					expiresAt: result.expiresAt,
				});

				results.push(result);
			} catch (err: any) {
				logger.warn(`[AlgoEngine] Failed to compute signal for ${symbol}`, {
					error: err.message,
				});
			}
		}

		// Structured audit log (FASP-AI v1.0 requirement)
		await auditLog({
			action: "algo_signal_generated",
			category: "trading",
			outcome: results.length > 0 ? "success" : "failure",
			riskLevel: "low",
			details: {
				event: "ALGO_SIGNAL_GENERATED",
				user_id: userId,
				input_context: { symbols: upperSymbols, riskProfile, horizon },
				output_summary: {
					generated: results.length,
					signals: results.map((r) => ({
						symbol: r.symbol,
						signal: r.signal,
						confidence: r.confidenceScore,
					})),
				},
				model_version: this.MODEL,
				latency_ms: Date.now() - startMs,
				timestamp: new Date().toISOString(),
			},
		}).catch(() => {});

		return results;
	}

	/**
	 * List signals for a user with optional filters.
	 */
	async listSignals(
		userId: number,
		filters: {
			status?: string;
			symbol?: string;
			limit?: number;
			page?: number;
		} = {},
	) {
		const { status, symbol, limit = 20, page = 1 } = filters;
		const offset = (page - 1) * limit;

		const conditions = [eq(algoSignals.userId, userId)];
		if (status) conditions.push(eq(algoSignals.status, status));
		if (symbol) conditions.push(eq(algoSignals.symbol, symbol.toUpperCase()));

		const rows = await db
			.select()
			.from(algoSignals)
			.where(and(...conditions))
			// BUG-ALGO-2 FIX: orderBy DESC in SQL so page N is correctly ordered.
			// Previous code used orderBy ASC + in-memory .sort() DESC after .limit(),
			// which reversed only the current page — pages 2+ were wrong relative to page 1.
			.orderBy(desc(algoSignals.createdAt))
			.limit(limit)
			.offset(offset);

		return rows;
	}

	/**
	 * Approve a signal — mark as approved and optionally link an order ID.
	 */
	async approveSignal(signalId: number, userId: number, orderId?: string) {
		const [updated] = await db
			.update(algoSignals)
			.set({
				status: "approved",
				approvedAt: new Date(),
				orderId: orderId || null,
				updatedAt: new Date(),
			})
			.where(and(eq(algoSignals.id, signalId), eq(algoSignals.userId, userId)))
			.returning();

		if (!updated) throw new Error("Signal not found or not owned by user");

		await auditLog({
			action: "algo_signal_approved",
			category: "trading",
			outcome: "success",
			riskLevel: "medium",
			details: {
				event: "ALGO_SIGNAL_APPROVED",
				user_id: userId,
				signal_id: signalId,
				symbol: updated.symbol,
				signal: updated.signal,
				confidence: updated.confidenceScore,
				order_id: orderId,
				model_version: updated.modelVersion,
				timestamp: new Date().toISOString(),
			},
		}).catch(() => {});

		return updated;
	}

	/**
	 * Reject a signal — mark as rejected.
	 */
	async rejectSignal(signalId: number, userId: number) {
		const [updated] = await db
			.update(algoSignals)
			.set({
				status: "rejected",
				rejectedAt: new Date(),
				updatedAt: new Date(),
			})
			.where(and(eq(algoSignals.id, signalId), eq(algoSignals.userId, userId)))
			.returning();

		if (!updated) throw new Error("Signal not found or not owned by user");

		await auditLog({
			action: "algo_signal_rejected",
			category: "trading",
			outcome: "success",
			riskLevel: "low",
			details: {
				event: "ALGO_SIGNAL_REJECTED",
				user_id: userId,
				signal_id: signalId,
				symbol: updated.symbol,
				timestamp: new Date().toISOString(),
			},
		}).catch(() => {});

		return updated;
	}

	/**
	 * Performance: count signal outcomes for a user using SQL aggregation.
	 * BUG-ALGO-1 FIX: was a full table scan + 4× in-memory Array.filter().
	 * Now uses a single COUNT(*) FILTER query — O(1) DB cost regardless of history size.
	 */
	async getPerformance(userId: number) {
		// One SQL query — all aggregates in the DB
		const [row] = await db
			.select({
				total:         sql<number>`COUNT(*)::int`,
				approved:      sql<number>`COUNT(*) FILTER (WHERE status = 'approved')::int`,
				rejected:      sql<number>`COUNT(*) FILTER (WHERE status = 'rejected')::int`,
				pending:       sql<number>`COUNT(*) FILTER (WHERE status = 'pending')::int`,
				expired:       sql<number>`COUNT(*) FILTER (WHERE status = 'expired')::int`,
				buy_count:     sql<number>`COUNT(*) FILTER (WHERE signal = 'buy')::int`,
				sell_count:    sql<number>`COUNT(*) FILTER (WHERE signal = 'sell')::int`,
				watch_count:   sql<number>`COUNT(*) FILTER (WHERE signal = 'watch')::int`,
				hold_count:    sql<number>`COUNT(*) FILTER (WHERE signal = 'hold')::int`,
				avg_confidence: sql<number>`ROUND(AVG(confidence_score))::int`,
			})
			.from(algoSignals)
			.where(eq(algoSignals.userId, userId));

		return {
			total:         row.total,
			approved:      row.approved,
			rejected:      row.rejected,
			pending:       row.pending,
			expired:       row.expired,
			bySignal: {
				buy:   row.buy_count,
				sell:  row.sell_count,
				watch: row.watch_count,
				hold:  row.hold_count,
			},
			avgConfidence: row.avg_confidence ?? 0,
		};
	}

	// ─── Private: Core Signal Computation ──────────────────────────────────────

	private _computeSignal(
		symbol: string,
		bars: Array<{ c: number; h: number; l: number; v: number }>,
		riskProfile: RiskProfile,
	): SignalResult | null {
		if (bars.length < 21) return null;

		const closes = bars.map((b) => b.c);
		const highs = bars.map((b) => b.h);
		const lows = bars.map((b) => b.l);
		const volumes = bars.map((b) => b.v);

		const currentPrice = closes[closes.length - 1];

		// ── SMA calculations ────────────────────────────────────────────────────
		const sma20 = this._sma(closes, 20);
		const sma50 = bars.length >= 50 ? this._sma(closes, 50) : sma20;

		// ── RSI(14) ─────────────────────────────────────────────────────────────
		const rsi14 = this._rsi(closes, 14);

		// ── Volume ratio (5d avg / 20d avg) ─────────────────────────────────────
		const vol5 = this._sma(volumes, 5);
		const vol20 = this._sma(volumes, 20);
		const volumeRatio = vol20 > 0 ? +(vol5 / vol20).toFixed(3) : 1;

		// ── 20-day momentum (%) ─────────────────────────────────────────────────
		const price20dAgo = closes[Math.max(0, closes.length - 21)];
		const momentum20d =
			price20dAgo > 0
				? +(((currentPrice - price20dAgo) / price20dAgo) * 100).toFixed(2)
				: 0;

		// ── 20-day high/low ──────────────────────────────────────────────────────
		const recent20h = highs.slice(-20);
		const recent20l = lows.slice(-20);
		const high20d = Math.max(...recent20h);
		const low20d = Math.min(...recent20l);

		// ── ATR(14) — for target/stop sizing ─────────────────────────────────────
		const atr14 = this._atr(highs, lows, closes, 14);

		// ── Strategy scores (-1 = strong sell, 0 = neutral, +1 = strong buy) ────

		// SMA Crossover: SMA20 vs SMA50
		const smaDiff = sma50 > 0 ? (sma20 - sma50) / sma50 : 0;
		const smaScore = Math.max(-1, Math.min(1, smaDiff * 20)); // scale: 5% diff → ±1

		// RSI Mean Reversion
		let rsiScore = 0;
		if (rsi14 < 30)
			rsiScore = +(1 - rsi14 / 30).toFixed(3); // oversold → buy
		else if (rsi14 > 70) rsiScore = -((rsi14 - 70) / 30).toFixed(3); // overbought → sell

		// Momentum + Volume confirmation
		const momentumRaw = Math.max(-1, Math.min(1, momentum20d / 15)); // 15% → ±1
		const volBoost = volumeRatio > 1.3 ? 1.2 : volumeRatio < 0.7 ? 0.8 : 1.0;
		const momentumScore = +(momentumRaw * volBoost).toFixed(3);

		// ── Composite confidence ─────────────────────────────────────────────────
		// Weights: SMA=40%, RSI=30%, Momentum=30%
		const compositeRaw = smaScore * 0.4 + rsiScore * 0.3 + momentumScore * 0.3;
		const confidenceScore = Math.round(
			Math.min(100, Math.abs(compositeRaw) * 100),
		);
		const direction = compositeRaw >= 0 ? "buy" : "sell";

		// FASP-AI v1.0: downgrade low-confidence signals
		let signal: "buy" | "sell" | "watch" | "hold";
		if (confidenceScore < 40) {
			signal = "hold";
		} else if (confidenceScore < 60) {
			signal = "watch"; // no actionable direction
		} else {
			signal = direction;
		}

		// ── Price levels ─────────────────────────────────────────────────────────
		const atrMultiplier =
			riskProfile === "conservative"
				? 1.0
				: riskProfile === "aggressive"
					? 2.0
					: 1.5;
		const entryPrice = +currentPrice.toFixed(4);
		const targetPrice =
			signal === "buy"
				? +(currentPrice + atr14 * atrMultiplier * 2).toFixed(4)
				: +(currentPrice - atr14 * atrMultiplier * 2).toFixed(4);
		const stopLossPrice =
			signal === "buy"
				? +(currentPrice - atr14 * atrMultiplier).toFixed(4)
				: +(currentPrice + atr14 * atrMultiplier).toFixed(4);

		const suggestedNotional = NOTIONAL_BY_RISK[riskProfile];

		// NYSE close (4 PM ET = 21:30 UTC) today
		const expiresAt = new Date();
		expiresAt.setUTCHours(21, 30, 0, 0);
		if (expiresAt.getTime() < Date.now())
			expiresAt.setDate(expiresAt.getDate() + 1);

		const factors: SignalFactors = {
			currentPrice,
			sma20: +sma20.toFixed(4),
			sma50: +sma50.toFixed(4),
			rsi14: +rsi14.toFixed(2),
			volumeRatio,
			momentum20d,
			high20d: +high20d.toFixed(4),
			low20d: +low20d.toFixed(4),
			atr14: +atr14.toFixed(4),
			smaScore: +smaScore.toFixed(3),
			rsiScore: +rsiScore.toFixed(3),
			momentumScore: +momentumScore.toFixed(3),
		};

		return {
			symbol,
			strategy: "composite",
			signal,
			confidenceScore,
			entryPrice,
			targetPrice,
			stopLossPrice,
			suggestedNotional,
			factors,
			modelVersion: this.MODEL,
			disclaimer: DISCLAIMER,
			expiresAt,
		};
	}

	// ─── Maths helpers ──────────────────────────────────────────────────────────

	private _sma(arr: number[], period: number): number {
		const slice = arr.slice(-period);
		if (slice.length === 0) return 0;
		return slice.reduce((a, b) => a + b, 0) / slice.length;
	}

	private _rsi(closes: number[], period: number): number {
		if (closes.length < period + 1) return 50;
		let gains = 0,
			losses = 0;
		for (let i = closes.length - period; i < closes.length; i++) {
			const diff = closes[i] - closes[i - 1];
			if (diff >= 0) gains += diff;
			else losses -= diff;
		}
		const avgGain = gains / period;
		const avgLoss = losses / period;
		if (avgLoss === 0) return 100;
		const rs = avgGain / avgLoss;
		return +(100 - 100 / (1 + rs)).toFixed(2);
	}

	private _atr(
		highs: number[],
		lows: number[],
		closes: number[],
		period: number,
	): number {
		const trs: number[] = [];
		for (let i = 1; i < highs.length; i++) {
			const tr = Math.max(
				highs[i] - lows[i],
				Math.abs(highs[i] - closes[i - 1]),
				Math.abs(lows[i] - closes[i - 1]),
			);
			trs.push(tr);
		}
		return this._sma(trs, period);
	}

	private async _expireStaleSignals(userId: number, symbols: string[]) {
		// Mark old pending signals for these symbols as expired
		await db
			.update(algoSignals)
			.set({ status: "expired", updatedAt: new Date() })
			.where(
				and(
					eq(algoSignals.userId, userId),
					eq(algoSignals.status, "pending"),
					inArray(algoSignals.symbol, symbols),
				),
			)
			.catch(() => {}); // non-fatal
	}
}

// ─── Backtest Types ───────────────────────────────────────────────────────────

export interface AlgoBacktestConfig {
	symbol: string;
	startDate: string; // YYYY-MM-DD (max 2 years back — free Alpaca tier)
	endDate: string; // YYYY-MM-DD
	riskProfile: RiskProfile;
	initialCapital: number; // USD, default $10,000
	strategy: "composite" | "sma_crossover" | "rsi" | "momentum";
}

export interface BacktestTrade {
	entryDate: string;
	exitDate: string;
	signal: "buy" | "sell";
	entryPrice: number;
	exitPrice: number;
	returnPct: number;
	daysHeld: number;
	pnlUsd: number;
}

export interface EquityCurvePoint {
	date: string;
	portfolioValue: number;
	benchmarkValue: number; // buy-and-hold
	drawdown: number; // % from peak
}

export interface AlgoBacktestResult {
	symbol: string;
	strategy: string;
	startDate: string;
	endDate: string;
	initialCapital: number;
	summary: {
		totalTrades: number;
		winningTrades: number;
		losingTrades: number;
		winRate: number; // 0–100
		totalReturn: number; // %
		benchmarkReturn: number; // buy-and-hold %
		alpha: number; // vs benchmark
		cagr: number; // %
		sharpeRatio: number;
		maxDrawdown: number; // %
		avgHoldDays: number;
		profitFactor: number;
		totalBars: number;
	};
	equityCurve: EquityCurvePoint[];
	trades: BacktestTrade[];
	modelVersion: string;
	disclaimer: string;
	generatedAt: string;
}

// ─── Backtesting Engine (appended to AlgoSignalEngine class) ─────────────────
// NOTE: Exported as a separate engine instance that has access to all private methods
//       via composition with the signal engine's maths utilities.

class AlgoBacktestEngine {
	// Proxy maths helpers (same as AlgoSignalEngine — kept DRY by composition)
	private _sma(arr: number[], period: number): number {
		const slice = arr.slice(-period);
		return slice.length === 0
			? 0
			: slice.reduce((a, b) => a + b, 0) / slice.length;
	}

	private _smaAt(arr: number[], i: number, period: number): number {
		if (i < period - 1) return 0;
		const slice = arr.slice(i - period + 1, i + 1);
		return slice.reduce((a, b) => a + b, 0) / slice.length;
	}

	private _rsiAt(closes: number[], i: number, period: number): number {
		if (i < period) return 50;
		let gains = 0,
			losses = 0;
		for (let j = i - period + 1; j <= i; j++) {
			const diff = closes[j] - closes[j - 1];
			if (diff >= 0) gains += diff;
			else losses -= diff;
		}
		const avgGain = gains / period;
		const avgLoss = losses / period;
		if (avgLoss === 0) return 100;
		return +(100 - 100 / (1 + avgGain / avgLoss)).toFixed(2);
	}

	private _compositeScore(
		closes: number[],
		highs: number[],
		lows: number[],
		volumes: number[],
		i: number,
		strategy: AlgoBacktestConfig["strategy"],
	): number {
		if (i < 52) return 0; // need at least 52 bars for SMA-50 + warm-up

		const sma20 = this._smaAt(closes, i, 20);
		const sma50 = this._smaAt(closes, i, 50);
		const rsi14 = this._rsiAt(closes, i, 14);
		const vol5 = this._smaAt(volumes, i, 5);
		const vol20 = this._smaAt(volumes, i, 20);
		const volRatio = vol20 > 0 ? vol5 / vol20 : 1;
		const price20d = closes[Math.max(0, i - 20)];
		const mom20d = price20d > 0 ? (closes[i] - price20d) / price20d : 0;

		// Strategy scores
		const smaDiff = sma50 > 0 ? (sma20 - sma50) / sma50 : 0;
		const smaScore = Math.max(-1, Math.min(1, smaDiff * 20));
		let rsiScore = 0;
		if (rsi14 < 30) rsiScore = 1 - rsi14 / 30;
		else if (rsi14 > 70) rsiScore = -((rsi14 - 70) / 30);
		const momRaw = Math.max(-1, Math.min(1, mom20d / 0.15));
		const volBoost = volRatio > 1.3 ? 1.2 : volRatio < 0.7 ? 0.8 : 1.0;
		const momScore = momRaw * volBoost;

		switch (strategy) {
			case "sma_crossover":
				return smaScore;
			case "rsi":
				return rsiScore;
			case "momentum":
				return momScore;
			default:
				return smaScore * 0.4 + rsiScore * 0.3 + momScore * 0.3;
		}
	}

	/**
	 * Run a walk-forward backtest of the algo signal strategy using Alpaca historical bars.
	 * Max lookback: 2 years (free Alpaca tier).
	 * FASP-AI v1.0: result includes mandatory disclaimer. Not financial advice.
	 */
	async runBacktest(config: AlgoBacktestConfig): Promise<AlgoBacktestResult> {
		const startMs = Date.now();
		const symbol = config.symbol.toUpperCase();

		// Enforce 2-year max (free tier)
		const maxStart = new Date();
		maxStart.setFullYear(maxStart.getFullYear() - 2);
		const effectiveStart =
			config.startDate < maxStart.toISOString().split("T")[0]
				? maxStart.toISOString().split("T")[0]
				: config.startDate;

		logger.info("[AlgoBacktest] Starting", {
			symbol,
			effectiveStart,
			endDate: config.endDate,
		});

		// Fetch bars — add 60-day warm-up buffer before start
		const warmupStart = new Date(effectiveStart);
		warmupStart.setDate(warmupStart.getDate() - 65);

		const barsMap = await alpacaMarketDataService.getBars(
			symbol,
			"1Day",
			warmupStart.toISOString().split("T")[0],
			config.endDate,
			750, // ~2.5 years of trading days
		);

		const allBars = barsMap.get(symbol) || [];
		if (allBars.length < 60) {
			throw new Error(
				`Insufficient historical data for ${symbol}: only ${allBars.length} bars available`,
			);
		}

		// ── Parse bars into typed arrays ─────────────────────────────────────────
		type RawBar = {
			c?: number;
			close?: number;
			h?: number;
			high?: number;
			l?: number;
			low?: number;
			v?: number;
			volume?: number;
			timestamp?: string;
			t?: string;
		};
		const closes = allBars.map((b: RawBar) => b.c ?? b.close ?? 0);
		const highs = allBars.map((b: RawBar) => b.h ?? b.high ?? 0);
		const lows = allBars.map((b: RawBar) => b.l ?? b.low ?? 0);
		const volumes = allBars.map((b: RawBar) => b.v ?? b.volume ?? 0);
		const dates = allBars.map((b: RawBar) => {
			const ts = b.timestamp ?? b.t ?? "";
			return ts.split("T")[0];
		});

		// Find backtest window (after warm-up)
		const btStartIdx = dates.findIndex((d) => d >= effectiveStart);
		const btEndIdx = dates.findLastIndex
			? dates.findLastIndex((d) => d <= config.endDate)
			: dates.reduce((last, d, i) => (d <= config.endDate ? i : last), -1);
		if (btStartIdx < 0 || btEndIdx < 0 || btEndIdx <= btStartIdx) {
			throw new Error(
				`No trading data found for ${symbol} in date range ${effectiveStart}–${config.endDate}`,
			);
		}

		// ── Walk-forward simulation ───────────────────────────────────────────────
		const CONF_THRESHOLD = 0.6; // 60% confidence → actionable signal
		let capital = config.initialCapital;
		let peakCapital = capital;
		let inTrade = false;
		let tradeEntry = 0;
		let tradeDate = "";
		let tradeSignal: "buy" | "sell" = "buy";
		let maxDrawdown = 0;

		const trades: BacktestTrade[] = [];
		const equityCurve: EquityCurvePoint[] = [];
		const benchmarkStart = closes[btStartIdx];

		// Risk-adjusted position size (fraction of capital)
		const positionSize =
			config.riskProfile === "conservative"
				? 0.5
				: config.riskProfile === "moderate"
					? 0.75
					: config.riskProfile === "aggressive"
						? 0.9
						: 1.0; // very_aggressive = all-in

		for (let i = btStartIdx; i <= btEndIdx; i++) {
			const score = this._compositeScore(
				closes,
				highs,
				lows,
				volumes,
				i,
				config.strategy,
			);
			const absScore = Math.abs(score);
			const direction = score >= 0 ? "buy" : "sell";
			const isActionable = absScore >= CONF_THRESHOLD;

			// Exit logic: opposite signal while in trade
			if (inTrade) {
				const shouldExit =
					(tradeSignal === "buy" && direction === "sell" && isActionable) ||
					(tradeSignal === "sell" && direction === "buy" && isActionable) ||
					i === btEndIdx; // force exit at end

				if (shouldExit) {
					const exitPrice = closes[i];
					const grossReturn =
						tradeSignal === "buy"
							? (exitPrice - tradeEntry) / tradeEntry
							: (tradeEntry - exitPrice) / tradeEntry;

					const investedCapital = capital * positionSize;
					const pnlUsd = investedCapital * grossReturn;
					capital += pnlUsd;

					trades.push({
						entryDate: tradeDate,
						exitDate: dates[i],
						signal: tradeSignal,
						entryPrice: +tradeEntry.toFixed(4),
						exitPrice: +exitPrice.toFixed(4),
						returnPct: +(grossReturn * 100).toFixed(3),
						daysHeld: Math.max(
							1,
							dates[i] < tradeDate
								? 1
								: Math.round(
										(new Date(dates[i]).getTime() -
											new Date(tradeDate).getTime()) /
											86400000,
									),
						),
						pnlUsd: +pnlUsd.toFixed(2),
					});

					inTrade = false;
				}
			}

			// Entry logic: new actionable signal while not in trade
			if (!inTrade && isActionable && i < btEndIdx) {
				inTrade = true;
				tradeEntry = closes[i];
				tradeDate = dates[i];
				tradeSignal = direction;
			}

			// Equity curve point
			peakCapital = Math.max(peakCapital, capital);
			const drawdown =
				peakCapital > 0 ? ((capital - peakCapital) / peakCapital) * 100 : 0;
			maxDrawdown = Math.min(maxDrawdown, drawdown);

			equityCurve.push({
				date: dates[i],
				portfolioValue: +capital.toFixed(2),
				benchmarkValue: +(
					config.initialCapital *
					(closes[i] / benchmarkStart)
				).toFixed(2),
				drawdown: +drawdown.toFixed(3),
			});
		}

		// ── Summary stats ─────────────────────────────────────────────────────────
		const totalTrades = trades.length;
		const winning = trades.filter((t) => t.returnPct > 0);
		const losing = trades.filter((t) => t.returnPct <= 0);
		const winRate =
			totalTrades > 0 ? +((winning.length / totalTrades) * 100).toFixed(1) : 0;
		const totalReturn = +(
			((capital - config.initialCapital) / config.initialCapital) *
			100
		).toFixed(2);
		const benchmarkReturn = +(
			(closes[btEndIdx] / benchmarkStart - 1) *
			100
		).toFixed(2);
		const alpha = +(totalReturn - benchmarkReturn).toFixed(2);

		// CAGR
		const years = Math.max(
			0.1,
			(new Date(config.endDate).getTime() -
				new Date(effectiveStart).getTime()) /
				(365.25 * 86400000),
		);
		const cagr = +(
			((capital / config.initialCapital) ** (1 / years) - 1) *
			100
		).toFixed(2);

		// Sharpe Ratio (annualized, risk-free rate = 4.5%)
		const dailyReturns = equityCurve.slice(1).map((p, i) => {
			const prev = equityCurve[i].portfolioValue;
			return prev > 0 ? (p.portfolioValue - prev) / prev : 0;
		});
		const riskFreeDaily = 0.045 / 252;
		const excessReturns = dailyReturns.map((r) => r - riskFreeDaily);
		const meanExcess =
			excessReturns.reduce((a, b) => a + b, 0) / (excessReturns.length || 1);
		const stdExcess = Math.sqrt(
			excessReturns.reduce((a, r) => a + (r - meanExcess) ** 2, 0) /
				(excessReturns.length || 1),
		);
		const sharpeRatio =
			stdExcess > 0
				? +((meanExcess / stdExcess) * Math.sqrt(252)).toFixed(3)
				: 0;

		// Profit factor
		const grossProfit = winning.reduce((a, t) => a + t.pnlUsd, 0);
		const grossLoss = Math.abs(losing.reduce((a, t) => a + t.pnlUsd, 0));
		const profitFactor =
			grossLoss > 0
				? +(grossProfit / grossLoss).toFixed(3)
				: grossProfit > 0
					? 99.9
					: 0;

		const avgHoldDays =
			totalTrades > 0
				? +(trades.reduce((a, t) => a + t.daysHeld, 0) / totalTrades).toFixed(1)
				: 0;

		logger.info("[AlgoBacktest] Complete", {
			symbol,
			totalTrades,
			winRate,
			sharpeRatio,
			latency: Date.now() - startMs,
		});

		return {
			symbol,
			strategy: config.strategy,
			startDate: effectiveStart,
			endDate: config.endDate,
			initialCapital: config.initialCapital,
			summary: {
				totalTrades,
				winningTrades: winning.length,
				losingTrades: losing.length,
				winRate,
				totalReturn,
				benchmarkReturn,
				alpha,
				cagr,
				sharpeRatio,
				maxDrawdown: +Math.abs(maxDrawdown).toFixed(2),
				avgHoldDays,
				profitFactor,
				totalBars: btEndIdx - btStartIdx + 1,
			},
			equityCurve,
			trades,
			modelVersion: MODEL_VERSION,
			disclaimer:
				DISCLAIMER +
				" Backtested results are hypothetical and do NOT represent actual trading returns.",
			generatedAt: new Date().toISOString(),
		};
	}
}

export const algoSignalEngine = new AlgoSignalEngine();
export const algoBacktestEngine = new AlgoBacktestEngine();
