import { db } from "../db";
import { failSystemState } from "../../shared/schema/ai";
import { aiModelSelectionEngine } from "./model-selection";
import { aiGovernanceEngine } from "./ai-governance";
import {
	FailRequestContext,
	FailResponsePayload,
	ExplainabilitySchema,
} from "./fail-types";
import { GovernanceInput } from "./ai-governance/types";
import { aiScoringEngine } from "./scoring";
import { TrackedRecommendation } from "./scoring/types";

export class FAILOrchestrator {
	/**
	 * The Ultimate Gateway: Orchestrates the unified pipeline across AMSE, Quant, AAGE, and structures the ARSE feedback loop tail.
	 */
	async generateAdvisory(
		context: FailRequestContext,
	): Promise<FailResponsePayload> {
		const tracePath = [];

		try {
			// 10.2 Kill Switch Validation
			const isSystemDisabled = await this.checkKillSwitch();
			if (isSystemDisabled) {
				return {
					status: "BLOCKED",
					internal_routing_trace: ["FAIL_KILL_SWITCH_ACTIVE"],
				};
			}

			// Step 1: Execute AMSE (Model Selection)
			const selectionContext = {
				query_id: context.query_id,
				query_type: context.query_type,
				user_id: context.user_id,
				risk_level: context.risk_profile,
				latency_requirement: "high" as const,
				confidence_required: 0.85,
			};

			tracePath.push("[AMSE] Engaged");
			const modelTarget =
				await aiModelSelectionEngine.selectOptimalModel(selectionContext);

			if (
				modelTarget.fallback_triggered &&
				modelTarget.selected_model.includes("SEBI_BLOCK")
			) {
				tracePath.push(`[AMSE] Route Failed: ${modelTarget.reason}`);
				return { status: "BLOCKED", internal_routing_trace: tracePath };
			}
			tracePath.push(
				`[AMSE] Selected Model: ${modelTarget.selected_model} (Conf: ${modelTarget.confidence_target})`,
			);

			// Step 2: AI Execution (Mocking actual remote LLM call with a placeholder generated by the selected model framework)
			tracePath.push(
				`[AI Execution] Requesting generation from ${modelTarget.selected_model}...`,
			);

			const rawAiPayload = {
				recommendation:
					"Consider reallocating capital to fixed income and undervalued equity indices.",
				confidence_score: 0.88,
				factors_considered: ["interest rate hikes", "DCF compression metrics"],
				model_version: modelTarget.selected_model,
			};

			// Step 3: Quant-Backed Enforcement
			tracePath.push(
				"[Quant Validator] Enforcing independent numerical validation",
			);
			let quantData = {};
			if (
				context.requires_quant ||
				rawAiPayload.recommendation.includes("undervalued")
			) {
				// Placeholder for intrinsic value / DCF calculators defined elsewhere
				quantData = {
					valuation_method: "DCF",
					intrinsic_value: 145.2,
					market_price: 110.0,
					margin_of_safety: "24.2%",
				};
				tracePath.push("[Quant Validator] DCF Success");
			}

			// Step 4: Governance Dominance Rule (AAGE)
			tracePath.push("[AAGE] Submitting for compliance intercept");
			const aageInput: GovernanceInput = {
				user_id: context.user_id,
				query: context.input_query,
				ai_output: rawAiPayload,
				user_profile: {
					risk_profile: context.risk_profile,
					investment_horizon: context.investment_horizon,
					kyc_status: "verified",
					user_segment: context.user_segment,
				},
				trace_id: context.query_id,
			};

			const governanceCheck =
				await aiGovernanceEngine.validateAndResolve(aageInput);

			if (governanceCheck.decision === "BLOCK") {
				tracePath.push(
					`[AAGE] CRITICAL BLOCK: ${governanceCheck.final_output.reason}`,
				);
				return { status: "BLOCKED", internal_routing_trace: tracePath };
			}

			if (governanceCheck.decision === "MODIFY") {
				tracePath.push(`[AAGE] Mutated output. Append Risk & Disclaimers.`);
			}

			// Step 5: Structuring Explainability Schema (Format required by regulators)
			const finalStruct: ExplainabilitySchema = {
				recommendation:
					(governanceCheck.final_output as any).recommendation ||
					rawAiPayload.recommendation,
				confidence_score: rawAiPayload.confidence_score,
				reasoning: rawAiPayload.factors_considered,
				quant_validation: quantData,
				risk_summary: {
					volatility: 0.15, // Stubbed, comes from AAGE Risk metrics in real deployment
					drawdown_risk: 0.08,
					liquidity_risk: "high",
					warnings: governanceCheck.risk_flags || [],
				},
				model_version: rawAiPayload.model_version,
				timestamp: new Date().toISOString(),
			};

			// Background: Prime the Scoring Engine (ARSE) Tracker for future loops
			const trackedRec: TrackedRecommendation = {
				id: context.query_id,
				user_id: context.user_id,
				asset: "System_Array",
				type: "allocation",
				timestamp: new Date().toISOString(),
				model_version: rawAiPayload.model_version,
				expected_outcome: { risk_level: context.risk_profile },
			};

			tracePath.push("[PIPELINE COMPLETE] Regulated execution achieved.");

			return {
				status: "SUCCESS",
				explainable_payload: finalStruct,
				audit_id: governanceCheck.audit_id,
				internal_routing_trace: tracePath,
			};
		} catch (e: any) {
			console.error("[FAIL ORCHESTRATOR FAULT]", e);
			return {
				status: "DEGRADED_FALLBACK",
				internal_routing_trace: tracePath.concat(`Fault: ${e.message}`),
			};
		}
	}

	/**
	 * Evaluates if the `failSystemState` has enacted a global advisory blockade due to massive compliance cascades
	 */
	private async checkKillSwitch(): Promise<boolean> {
		try {
			const state = await db
				.select()
				.from(failSystemState)
				.where({ configKey: "GLOBAL_AI_KILL_SWITCH" })
				.limit(1);
			if (state.length > 0) {
				return state[0].isGloballyDisabled;
			}
			return false; // Safely default to open
		} catch {
			return false; // DB disconnected, default to fallback
		}
	}
}

export const failOrchestrator = new FAILOrchestrator();
