/**
 * IRIS Rebalance Orchestrator — FASP-AI-v3.0
 * ─────────────────────────────────────────────────────────────────────────────
 * Purpose : Generate AI rebalancing proposals for client MF portfolios held via
 *           IRIS/KFintech and execute them leg-by-leg after explicit advisor approval.
 *
 * Inputs  : PAN (client), modelPortfolioId (target allocation), advisorId (approver)
 * Outputs : { proposal_id, legs[], confidence_score, model_version, timestamp }
 * Edge cases:
 *   - IRIS not authenticated → propagates error; caller should surface to UI
 *   - Client has no KFintech holdings → returns needs_rebalance: false
 *   - Partial IRIS failures → legs marked 'failed'; proposal status = 'partial_failure'
 *   - Confidence < 60% → proposal flagged advisory_only; execution blocked
 *
 * FASP-AI advisory compliance:
 *   - AI NEVER executes trades autonomously
 *   - Every execution requires explicit advisor approval (role-gated)
 *   - All outputs include engine_version, confidence_score, timestamp, disclaimer
 *   - Structured audit log on every AI_ADVICE_GENERATED + IRIS_LEG_SUBMITTED event
 *
 * GCR: Drizzle ORM only — no raw SQL mutations.
 *      All writes include updated_at + source: "ai".
 */

import { db } from "../db";
import {
  rebalanceProposals,
  irisRebalanceExecutions,
} from "@shared/schema";
import { eq } from "drizzle-orm";
import { sql } from "drizzle-orm";
import { logger } from "../logger";
import { irisKfintechService } from "./iris-kfintech-service";
import { DriftDetectionEngine } from "./drift";
import type { AssetWeight } from "./drift";

const ENGINE_VERSION = "FASP-AI-v3.0";
const CONFIDENCE_EXECUTION_THRESHOLD = 60;

const DISCLAIMER =
  "Past performance is not indicative of future results. " +
  "This rebalancing proposal is generated by an AI Decision Support System. " +
  "Execution requires explicit advisor approval. Not financial advice. " +
  "Market conditions may change between proposal and execution. " +
  "SEBI-registered advisor oversight required.";

const driftEngine = new DriftDetectionEngine();

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface TradeLeg {
  legIndex:        number;
  legType:         "switch" | "redemption" | "purchase";
  fromIsin?:       string;
  toIsin?:         string;
  fromSchemeCode?: string;
  toSchemeCode?:   string;
  folioNo?:        string;
  amount:          number;
  rationale:       string;
}

export interface ClientRebalanceProposal {
  proposalId:           string;
  needsRebalance:       boolean;
  legs:                 TradeLeg[];
  driftSeverity:        "low" | "medium" | "high";
  largestDrift:         number;
  confidenceScore:      number;
  advisoryOnly:         boolean;
  engineVersion:        string;
  calculationTimestamp: string;
  disclaimer:           string;
  factorsConsidered:    string[];
}

interface IrisHolding {
  schemeCode?:   string;
  schemeName?:   string;
  isin?:         string;
  folioNo?:      string;
  units?:        number;
  currentValue?: number;
  assetClass?:   string;
  amcCode?:      string;
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

function parseHoldings(irisData: any): IrisHolding[] {
  const raw  = irisData?.data ?? irisData ?? [];
  const list = Array.isArray(raw) ? raw : (raw?.holdings ?? raw?.schemes ?? []);
  return list.map((h: any) => ({
    schemeCode:   h.schemeCode   ?? h.scheme_code ?? h.schemeId,
    schemeName:   h.schemeName   ?? h.scheme_name,
    isin:         h.isin         ?? h.ISIN,
    folioNo:      h.folioNo      ?? h.folio_no   ?? h.folioNumber,
    units:        Number(h.units ?? h.balance_units ?? 0),
    currentValue: Number(h.currentValue ?? h.current_value ?? h.marketValue ?? 0),
    assetClass:   (h.assetClass ?? h.asset_class ?? h.category ?? "other").toLowerCase(),
    amcCode:      h.amcCode ?? h.amc_code,
  }));
}

function computeAllocationWeights(holdings: IrisHolding[]): AssetWeight[] {
  const totalValue = holdings.reduce((s, h) => s + (h.currentValue ?? 0), 0);
  if (totalValue === 0) return [];
  const byClass: Record<string, number> = {};
  for (const h of holdings) {
    const cls = h.assetClass || "other";
    byClass[cls] = (byClass[cls] ?? 0) + (h.currentValue ?? 0);
  }
  return Object.entries(byClass).map(([asset, value]) => ({
    asset,
    weight: Math.round((value / totalValue) * 10000) / 100,
  }));
}

function buildTradeLegs(
  holdings:    IrisHolding[],
  targetAlloc: AssetWeight[],
  totalValue:  number,
): TradeLeg[] {
  const legs: TradeLeg[] = [];
  const byClass: Record<string, IrisHolding[]> = {};
  for (const h of holdings) {
    const cls = h.assetClass || "other";
    (byClass[cls] = byClass[cls] ?? []).push(h);
  }

  const overweight:  { asset: string; excess: number; holdings: IrisHolding[] }[] = [];
  const underweight: { asset: string; deficit: number }[] = [];

  for (const { asset, weight } of targetAlloc) {
    const classHoldings = byClass[asset] ?? [];
    const currentValue  = classHoldings.reduce((s, h) => s + (h.currentValue ?? 0), 0);
    const currentWeight = totalValue > 0 ? (currentValue / totalValue) * 100 : 0;
    const delta         = currentWeight - weight;
    if (Math.abs(delta) < 1) continue;
    if (delta > 0) overweight.push({ asset, excess: (delta / 100) * totalValue, holdings: classHoldings });
    else           underweight.push({ asset, deficit: (Math.abs(delta) / 100) * totalValue });
  }

  let legIdx = 0;

  // Leg 1: Switches (same AMC — T+1, preferred)
  for (const over of overweight) {
    const overH = over.holdings.sort((a, b) => (b.currentValue ?? 0) - (a.currentValue ?? 0))[0];
    if (!overH?.schemeCode) continue;
    for (const under of underweight) {
      if (under.deficit <= 0) continue;
      const switchAmt   = Math.min(over.excess, under.deficit);
      if (switchAmt < 500) continue;
      const underHoldings = byClass[under.asset] ?? [];
      const underH        = underHoldings[0];
      if (overH.amcCode && underH?.amcCode && overH.amcCode === underH.amcCode) {
        legs.push({ legIndex: legIdx++, legType: "switch", fromIsin: overH.isin, toIsin: underH.isin,
          fromSchemeCode: overH.schemeCode, toSchemeCode: underH.schemeCode, folioNo: overH.folioNo,
          amount: Math.round(switchAmt),
          rationale: `Switch ₹${Math.round(switchAmt).toLocaleString()} from ${over.asset} → ${under.asset} (AMC: ${overH.amcCode})` });
        over.excess   -= switchAmt;
        under.deficit -= switchAmt;
      }
    }
  }

  // Leg 2: Redemptions (cross-AMC overweight → cash)
  for (const over of overweight) {
    if (over.excess < 500) continue;
    const overH = over.holdings[0];
    if (!overH?.schemeCode) continue;
    legs.push({ legIndex: legIdx++, legType: "redemption", fromIsin: overH.isin,
      fromSchemeCode: overH.schemeCode, folioNo: overH.folioNo,
      amount: Math.round(over.excess),
      rationale: `Redeem ₹${Math.round(over.excess).toLocaleString()} from overweight ${over.asset} (${overH.schemeName ?? overH.schemeCode})` });
  }

  // Leg 3: Purchases (from redemption proceeds)
  for (const under of underweight) {
    if (under.deficit < 500) continue;
    legs.push({ legIndex: legIdx++, legType: "purchase", amount: Math.round(under.deficit),
      rationale: `Purchase ₹${Math.round(under.deficit).toLocaleString()} in ${under.asset} (from redemption proceeds — T+2)` });
  }

  return legs;
}

// ─── 1. generateClientRebalanceProposal ───────────────────────────────────────

export async function generateClientRebalanceProposal(
  pan:              string,
  modelPortfolioId: string,
  advisorId:        string,
): Promise<ClientRebalanceProposal> {
  const t0        = Date.now();
  const timestamp = new Date().toISOString();

  // Load model portfolio
  const mpRows = await db.execute(
    sql`SELECT id, allocation, drift_threshold FROM model_portfolios WHERE id = ${modelPortfolioId} LIMIT 1`,
  );
  const mp = ((mpRows as any).rows ?? mpRows)[0];
  if (!mp) throw new Error(`Model portfolio ${modelPortfolioId} not found`);

  const targetAlloc: AssetWeight[] = Array.isArray(mp.allocation)
    ? (mp.allocation as any[]).map((a: any) => ({
        asset:  (a.assetClass ?? a.asset ?? "").toLowerCase(),
        weight: Number(a.weight ?? a.percentage ?? 0),
      }))
    : [];
  if (targetAlloc.length === 0) throw new Error(`Model portfolio ${modelPortfolioId} has no allocation`);

  const driftThreshold = Number(mp.drift_threshold ?? 5);

  // Fetch IRIS holdings
  const irisRaw    = await irisKfintechService.getInvestmentDetails(pan);
  const holdings   = parseHoldings(irisRaw);
  const totalValue = holdings.reduce((s, h) => s + (h.currentValue ?? 0), 0);

  if (holdings.length === 0 || totalValue === 0) {
    return { proposalId: "", needsRebalance: false, legs: [], driftSeverity: "low", largestDrift: 0,
      confidenceScore: 0, advisoryOnly: true, engineVersion: ENGINE_VERSION,
      calculationTimestamp: timestamp, disclaimer: DISCLAIMER,
      factorsConsidered: ["No IRIS holdings found for this PAN"] };
  }

  // Drift analysis
  const currentAlloc  = computeAllocationWeights(holdings);
  const driftReport   = driftEngine.calculateDrift(
    { portfolio_id: modelPortfolioId, target_allocation: targetAlloc,
      rebalance_policy: { frequency: "drift_triggered", drift_threshold: driftThreshold, tax_aware: false } },
    currentAlloc,
  );

  if (!driftReport.has_drifted) {
    return { proposalId: "", needsRebalance: false, legs: [], driftSeverity: "low",
      largestDrift: driftReport.largest_drift, confidenceScore: 100, advisoryOnly: false,
      engineVersion: ENGINE_VERSION, calculationTimestamp: timestamp, disclaimer: DISCLAIMER,
      factorsConsidered: [`Portfolio within ${driftThreshold}% drift threshold`] };
  }

  // Build legs + compute confidence
  const legs            = buildTradeLegs(holdings, targetAlloc, totalValue);
  const largestDrift    = driftReport.largest_drift;
  const driftSeverity   = largestDrift > 15 ? "high" : largestDrift > 7 ? "medium" : "low";
  const confidenceScore = Math.max(0, Math.min(100, Math.round(90 - largestDrift)));
  const advisoryOnly    = confidenceScore < CONFIDENCE_EXECUTION_THRESHOLD;

  const factorsConsidered = [
    `Drift threshold: ${driftThreshold}%`, `Largest drift: ${largestDrift.toFixed(1)}%`,
    `Portfolio value: ₹${totalValue.toLocaleString()}`, `Holdings: ${holdings.length} schemes`,
    `Trade legs: ${legs.length}`, `Engine: ${ENGINE_VERSION}`,
  ];

  // Persist
  const [saved] = await db.insert(rebalanceProposals).values({
    portfolioId:            modelPortfolioId,
    clientPan:              pan,
    targetModelPortfolioId: modelPortfolioId,
    proposedBy:             ENGINE_VERSION,
    engineVersion:          ENGINE_VERSION,
    status:                 advisoryOnly ? "advisory_only" : "pending_advisor_review",
    substitutions:          legs as any,
    confidence:             confidenceScore,
    driftSeverity,
    disclaimer:             DISCLAIMER,
    source:                 "ai",
    updatedAt:              new Date(),
  }).returning();

  // Structured audit log (FASP-AI mandate)
  logger.info("[IrisRebalance] AI_ADVICE_GENERATED", {
    event: "AI_ADVICE_GENERATED", user_id: advisorId,
    client_pan: pan.slice(0, 3) + "***" + pan.slice(-2),
    proposal_id: saved.id, model_version: ENGINE_VERSION,
    confidence_score: confidenceScore, drift_severity: driftSeverity,
    legs_count: legs.length, advisory_only: advisoryOnly,
    latency_ms: Date.now() - t0, status: "success", timestamp,
  });

  return { proposalId: saved.id, needsRebalance: true, legs, driftSeverity, largestDrift,
    confidenceScore, advisoryOnly, engineVersion: ENGINE_VERSION, calculationTimestamp: timestamp,
    disclaimer: DISCLAIMER, factorsConsidered };
}

// ─── 2. executeApprovedProposal ────────────────────────────────────────────────

export async function executeApprovedProposal(
  proposalId: string,
  advisorId:  string,
): Promise<{ success: boolean; legsTotal: number; legsOk: number; legsFailed: number; irisOrderIds: string[] }> {
  const t0 = Date.now();

  const [proposal] = await db.select().from(rebalanceProposals)
    .where(eq(rebalanceProposals.id, proposalId));
  if (!proposal) throw new Error(`Proposal ${proposalId} not found`);
  if (proposal.status !== "pending_advisor_review")
    throw new Error(`Proposal not in pending_advisor_review (current: ${proposal.status})`);

  const clientPan = proposal.clientPan;
  if (!clientPan) throw new Error(`Proposal ${proposalId} missing client_pan`);

  const legs: TradeLeg[] = Array.isArray(proposal.substitutions)
    ? (proposal.substitutions as unknown as TradeLeg[]) : [];
  if (legs.length === 0) throw new Error("No trade legs in proposal");

  await db.update(rebalanceProposals)
    .set({ status: "executing", reviewedBy: advisorId, reviewedAt: new Date(), updatedAt: new Date() })
    .where(eq(rebalanceProposals.id, proposalId));

  let legsOk = 0, legsFailed = 0;
  const irisOrderIds: string[] = [];

  for (const leg of legs.sort((a, b) => a.legIndex - b.legIndex)) {
    const [execRow] = await db.insert(irisRebalanceExecutions).values({
      proposalId, clientPan, legIndex: leg.legIndex, legType: leg.legType,
      fromIsin: leg.fromIsin, toIsin: leg.toIsin,
      fromSchemeCode: leg.fromSchemeCode, toSchemeCode: leg.toSchemeCode,
      folioNo: leg.folioNo, amount: String(leg.amount),
      engineVersion: ENGINE_VERSION, source: "ai", updatedAt: new Date(),
    }).returning();

    const tLeg = Date.now();
    let irisOrderId: string | null = null;
    let lastError:   string | null = null;

    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        let irisResult: any;
        if (leg.legType === "switch") {
          irisResult = await irisKfintechService.placeSwitch({
            pan: clientPan, fromSchemeCode: leg.fromSchemeCode,
            toSchemeCode: leg.toSchemeCode, folioNo: leg.folioNo, amount: leg.amount });
        } else if (leg.legType === "redemption") {
          irisResult = await irisKfintechService.placeRedemption({
            pan: clientPan, schemeCode: leg.fromSchemeCode, folioNo: leg.folioNo, amount: leg.amount });
        } else {
          irisResult = await irisKfintechService.placeOrder({
            pan: clientPan, schemeCode: leg.toSchemeCode, amount: leg.amount });
        }

        irisOrderId = irisResult?.orderId ?? irisResult?.data?.orderId ?? null;
        await db.update(irisRebalanceExecutions)
          .set({ irisOrderId, irisStatus: "submitted", irisResponse: irisResult as any,
                 submittedAt: new Date(), updatedAt: new Date() })
          .where(eq(irisRebalanceExecutions.id, execRow.id));
        if (irisOrderId) irisOrderIds.push(irisOrderId);

        logger.info("[IrisRebalance] IRIS_LEG_SUBMITTED", {
          event: "IRIS_LEG_SUBMITTED", user_id: advisorId, proposal_id: proposalId,
          leg_index: leg.legIndex, leg_type: leg.legType, iris_order_id: irisOrderId,
          amount: leg.amount, attempt, latency_ms: Date.now() - tLeg, status: "success" });

        legsOk++;
        lastError = null;
        break;
      } catch (err: any) {
        lastError = err?.message ?? String(err);
        if (attempt < 3) await new Promise(r => setTimeout(r, 500 * 2 ** (attempt - 1)));
      }
    }

    if (lastError) {
      await db.update(irisRebalanceExecutions)
        .set({ irisStatus: "failed", errorMessage: lastError, updatedAt: new Date() })
        .where(eq(irisRebalanceExecutions.id, execRow.id));
      logger.error("[IrisRebalance] IRIS_LEG_FAILED", {
        event: "IRIS_LEG_FAILED", user_id: advisorId, proposal_id: proposalId,
        leg_index: leg.legIndex, error: lastError, retryable: false });
      legsFailed++;
    }
  }

  const finalStatus = legsFailed === 0 ? "executed" : legsOk === 0 ? "failed" : "partial_failure";
  await db.update(rebalanceProposals)
    .set({ status: finalStatus, executedAt: new Date(),
           executionNotes: `${legsOk}/${legs.length} legs succeeded. Advisor: ${advisorId}. Engine: ${ENGINE_VERSION}.`,
           updatedAt: new Date() })
    .where(eq(rebalanceProposals.id, proposalId));

  try {
    const { scheduleIrisPortfolioRefresh } = await import("./iris-portfolio-sync-service");
    scheduleIrisPortfolioRefresh(clientPan, advisorId);
  } catch { /* non-critical */ }

  logger.info("[IrisRebalance] REBALANCE_EXECUTED", {
    event: "REBALANCE_EXECUTED", user_id: advisorId, proposal_id: proposalId,
    legs_total: legs.length, legs_ok: legsOk, legs_failed: legsFailed,
    final_status: finalStatus, latency_ms: Date.now() - t0,
    status: finalStatus === "failed" ? "error" : "success" });

  return { success: finalStatus !== "failed", legsTotal: legs.length, legsOk, legsFailed, irisOrderIds };
}

// ─── 3. getExecutionStatus ────────────────────────────────────────────────────

export async function getExecutionStatus(proposalId: string) {
  const [proposal] = await db.select().from(rebalanceProposals)
    .where(eq(rebalanceProposals.id, proposalId));
  const legs = await db.select().from(irisRebalanceExecutions)
    .where(eq(irisRebalanceExecutions.proposalId, proposalId))
    .orderBy(irisRebalanceExecutions.legIndex);
  return { proposal: proposal ?? null, legs };
}
