// @ts-nocheck
/**
 * SEBI/RBI Regulatory Reporting Service
 * 
 * Provides regulatory compliance reporting for:
 * - SEBI (Securities and Exchange Board of India) - Securities market regulator
 * - RBI (Reserve Bank of India) - Banking and payment systems regulator
 * - FIU-IND (Financial Intelligence Unit) - AML/CFT reporting
 * 
 * Features:
 * - STR (Suspicious Transaction Report) generation and submission
 * - CTR (Cash Transaction Report) generation and submission
 * - Regulatory event queue management
 * - Report status tracking
 * - Audit trail for all regulatory submissions
 */

import { db } from '../db';
import { complianceAuditTrail, users, unlistedDeals, regulatoryAuditPacks } from '@shared/schema';
import { eq, and, gte, lte, desc, sql, or, isNull, inArray } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import { auditLogArchivalService } from './audit-log-archival';

export type ReportType = 'STR' | 'CTR' | 'SAR' | 'SFT' | 'OTHER';
export type ReportStatus = 'draft' | 'pending_review' | 'approved' | 'submitted' | 'acknowledged' | 'rejected' | 'cancelled';
export type RegulatoryAuthority = 'SEBI' | 'RBI' | 'FIU-IND' | 'ED' | 'IT';

export interface RegulatoryReport {
  reportId: string;
  reportType: ReportType;
  authority: RegulatoryAuthority;
  status: ReportStatus;
  userId?: string;
  dealId?: string;
  transactionIds: string[];
  amount: number;
  currency: string;
  suspicionIndicators: string[];
  riskScore: number;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  narrative: string;
  createdAt: Date;
  createdBy: string;
  reviewedBy?: string;
  reviewedAt?: Date;
  reviewNotes?: string;
  submittedAt?: Date;
  submittedBy?: string;
  referenceNumber?: string;
  acknowledgedAt?: Date;
  metadata: Record<string, any>;
}

export interface ReportableEvent {
  eventId: string;
  eventType: string;
  triggeredBy: string;
  userId?: string;
  dealId?: string;
  amount?: number;
  currency?: string;
  riskIndicators: string[];
  riskScore: number;
  requiresReporting: boolean;
  reportType?: ReportType;
  authority?: RegulatoryAuthority;
  autoGenerated: boolean;
  reportId?: string;
  createdAt: Date;
  processedAt?: Date;
  metadata: Record<string, any>;
}

const STR_RISK_THRESHOLD = 60;
const CTR_AMOUNT_THRESHOLD = 1000000;
const HIGH_VALUE_THRESHOLD = 5000000;

class RegulatoryReportingService {
  private reports: Map<string, RegulatoryReport> = new Map();
  private events: Map<string, ReportableEvent> = new Map();

  constructor() {
    this.loadReportsFromStorage();
  }

  private async loadReportsFromStorage(): Promise<void> {
    try {
      const storedReports = await db.select()
        .from(complianceAuditTrail)
        .where(eq(complianceAuditTrail.fieldChanged, 'regulatory_report'))
        .orderBy(desc(complianceAuditTrail.createdAt))
        .limit(1000);

      for (const record of storedReports) {
        const metadata = record.metadata as Record<string, any>;
        if (metadata?.reportId) {
          const report: RegulatoryReport = {
            reportId: metadata.reportId,
            reportType: metadata.reportType || 'OTHER',
            authority: metadata.authority || 'FIU-IND',
            status: metadata.status || 'draft',
            userId: record.userId,
            dealId: metadata.dealId,
            transactionIds: metadata.transactionIds || [],
            amount: metadata.amount || 0,
            currency: metadata.currency || 'INR',
            suspicionIndicators: metadata.suspicionIndicators || [],
            riskScore: metadata.riskScore || 0,
            riskLevel: metadata.riskLevel || 'low',
            narrative: metadata.narrative || '',
            createdAt: record.createdAt || new Date(),
            createdBy: metadata.createdBy || 'system',
            reviewedBy: metadata.reviewedBy,
            reviewedAt: metadata.reviewedAt ? new Date(metadata.reviewedAt) : undefined,
            reviewNotes: metadata.reviewNotes,
            submittedAt: metadata.submittedAt ? new Date(metadata.submittedAt) : undefined,
            submittedBy: metadata.submittedBy,
            referenceNumber: metadata.referenceNumber,
            acknowledgedAt: metadata.acknowledgedAt ? new Date(metadata.acknowledgedAt) : undefined,
            metadata: metadata.extra || {},
          };
          this.reports.set(report.reportId, report);
        }
      }
      console.log(`[Regulatory Reporting] Loaded ${this.reports.size} reports from storage`);
    } catch (error) {
      console.error('[Regulatory Reporting] Failed to load reports from storage:', error);
    }
  }

  private calculateRiskLevel(score: number): 'low' | 'medium' | 'high' | 'critical' {
    if (score >= 80) return 'critical';
    if (score >= 60) return 'high';
    if (score >= 30) return 'medium';
    return 'low';
  }

  async createSTR(params: {
    userId: string;
    dealId?: string;
    transactionIds: string[];
    amount: number;
    currency?: string;
    suspicionIndicators: string[];
    narrative: string;
    createdBy: string;
    metadata?: Record<string, any>;
  }): Promise<RegulatoryReport> {
    const reportId = `STR-${Date.now()}-${nanoid(6)}`;
    const riskScore = Math.min(params.suspicionIndicators.length * 15 + 30, 100);

    const report: RegulatoryReport = {
      reportId,
      reportType: 'STR',
      authority: 'FIU-IND',
      status: 'draft',
      userId: params.userId,
      dealId: params.dealId,
      transactionIds: params.transactionIds,
      amount: params.amount,
      currency: params.currency || 'INR',
      suspicionIndicators: params.suspicionIndicators,
      riskScore,
      riskLevel: this.calculateRiskLevel(riskScore),
      narrative: params.narrative,
      createdAt: new Date(),
      createdBy: params.createdBy,
      metadata: params.metadata || {},
    };

    this.reports.set(reportId, report);
    await this.persistReport(report, 'created');

    await auditLogArchivalService.archiveComplianceEvent({
      eventType: 'fiu_report',
      userId: params.userId,
      entityId: reportId,
      entityType: 'str_report',
      action: 'STR report created',
      details: {
        reportId,
        amount: params.amount,
        suspicionIndicators: params.suspicionIndicators,
      },
      riskLevel: report.riskLevel,
    });

    console.log(`[Regulatory Reporting] STR ${reportId} created for user ${params.userId}`);
    return report;
  }

  async createCTR(params: {
    userId: string;
    dealId?: string;
    transactionIds: string[];
    amount: number;
    currency?: string;
    narrative: string;
    createdBy: string;
    metadata?: Record<string, any>;
  }): Promise<RegulatoryReport> {
    const reportId = `CTR-${Date.now()}-${nanoid(6)}`;
    const riskScore = params.amount >= HIGH_VALUE_THRESHOLD ? 50 : 30;

    const report: RegulatoryReport = {
      reportId,
      reportType: 'CTR',
      authority: 'FIU-IND',
      status: 'draft',
      userId: params.userId,
      dealId: params.dealId,
      transactionIds: params.transactionIds,
      amount: params.amount,
      currency: params.currency || 'INR',
      suspicionIndicators: [],
      riskScore,
      riskLevel: this.calculateRiskLevel(riskScore),
      narrative: params.narrative,
      createdAt: new Date(),
      createdBy: params.createdBy,
      metadata: params.metadata || {},
    };

    this.reports.set(reportId, report);
    await this.persistReport(report, 'created');

    await auditLogArchivalService.archiveComplianceEvent({
      eventType: 'fiu_report',
      userId: params.userId,
      entityId: reportId,
      entityType: 'ctr_report',
      action: 'CTR report created',
      details: {
        reportId,
        amount: params.amount,
      },
      riskLevel: report.riskLevel,
    });

    console.log(`[Regulatory Reporting] CTR ${reportId} created for user ${params.userId}`);
    return report;
  }

  async submitForReview(reportId: string, submittedBy: string): Promise<RegulatoryReport> {
    const report = this.reports.get(reportId);
    if (!report) {
      throw new Error(`Report ${reportId} not found`);
    }

    if (report.status !== 'draft') {
      throw new Error(`Report ${reportId} is not in draft status`);
    }

    report.status = 'pending_review';
    this.reports.set(reportId, report);
    await this.persistReport(report, 'submitted_for_review');

    console.log(`[Regulatory Reporting] Report ${reportId} submitted for review by ${submittedBy}`);
    return report;
  }

  async approveReport(reportId: string, reviewedBy: string, reviewNotes?: string): Promise<RegulatoryReport> {
    const report = this.reports.get(reportId);
    if (!report) {
      throw new Error(`Report ${reportId} not found`);
    }

    if (report.status !== 'pending_review') {
      throw new Error(`Report ${reportId} is not pending review`);
    }

    report.status = 'approved';
    report.reviewedBy = reviewedBy;
    report.reviewedAt = new Date();
    report.reviewNotes = reviewNotes;
    this.reports.set(reportId, report);
    await this.persistReport(report, 'approved');

    await auditLogArchivalService.archiveComplianceEvent({
      eventType: 'fiu_report',
      userId: report.userId,
      entityId: reportId,
      entityType: `${report.reportType.toLowerCase()}_report`,
      action: `${report.reportType} report approved`,
      details: {
        reportId,
        reviewedBy,
        reviewNotes,
      },
      riskLevel: report.riskLevel,
    });

    console.log(`[Regulatory Reporting] Report ${reportId} approved by ${reviewedBy}`);
    return report;
  }

  async rejectReport(reportId: string, reviewedBy: string, reviewNotes: string): Promise<RegulatoryReport> {
    const report = this.reports.get(reportId);
    if (!report) {
      throw new Error(`Report ${reportId} not found`);
    }

    if (report.status !== 'pending_review') {
      throw new Error(`Report ${reportId} is not pending review`);
    }

    report.status = 'rejected';
    report.reviewedBy = reviewedBy;
    report.reviewedAt = new Date();
    report.reviewNotes = reviewNotes;
    this.reports.set(reportId, report);
    await this.persistReport(report, 'rejected');

    console.log(`[Regulatory Reporting] Report ${reportId} rejected by ${reviewedBy}`);
    return report;
  }

  async submitToAuthority(reportId: string, submittedBy: string): Promise<RegulatoryReport> {
    const report = this.reports.get(reportId);
    if (!report) {
      throw new Error(`Report ${reportId} not found`);
    }

    if (report.status !== 'approved') {
      throw new Error(`Report ${reportId} is not approved for submission`);
    }

    report.status = 'submitted';
    report.submittedAt = new Date();
    report.submittedBy = submittedBy;
    report.referenceNumber = `${report.authority}-${report.reportType}-${Date.now()}`;
    this.reports.set(reportId, report);
    await this.persistReport(report, 'submitted');

    await auditLogArchivalService.archiveComplianceEvent({
      eventType: 'fiu_report',
      userId: report.userId,
      entityId: reportId,
      entityType: `${report.reportType.toLowerCase()}_report`,
      action: `${report.reportType} report submitted to ${report.authority}`,
      details: {
        reportId,
        submittedBy,
        referenceNumber: report.referenceNumber,
        authority: report.authority,
      },
      riskLevel: report.riskLevel,
    });

    console.log(`[Regulatory Reporting] Report ${reportId} submitted to ${report.authority} with reference ${report.referenceNumber}`);
    return report;
  }

  async acknowledgeReport(reportId: string, referenceNumber?: string): Promise<RegulatoryReport> {
    const report = this.reports.get(reportId);
    if (!report) {
      throw new Error(`Report ${reportId} not found`);
    }

    if (report.status !== 'submitted') {
      throw new Error(`Report ${reportId} is not in submitted status`);
    }

    report.status = 'acknowledged';
    report.acknowledgedAt = new Date();
    if (referenceNumber) {
      report.referenceNumber = referenceNumber;
    }
    this.reports.set(reportId, report);
    await this.persistReport(report, 'acknowledged');

    console.log(`[Regulatory Reporting] Report ${reportId} acknowledged by authority`);
    return report;
  }

  async registerReportableEvent(params: {
    eventType: string;
    triggeredBy: string;
    userId?: string;
    dealId?: string;
    amount?: number;
    currency?: string;
    riskIndicators: string[];
    riskScore: number;
    metadata?: Record<string, any>;
  }): Promise<ReportableEvent> {
    const eventId = `EVT-${Date.now()}-${nanoid(6)}`;
    const requiresReporting = params.riskScore >= STR_RISK_THRESHOLD || 
                              !!(params.amount && params.amount >= CTR_AMOUNT_THRESHOLD);
    
    let reportType: ReportType | undefined;
    let authority: RegulatoryAuthority | undefined;

    if (params.riskScore >= STR_RISK_THRESHOLD) {
      reportType = 'STR';
      authority = 'FIU-IND';
    } else if (params.amount && params.amount >= CTR_AMOUNT_THRESHOLD) {
      reportType = 'CTR';
      authority = 'FIU-IND';
    }

    const event: ReportableEvent = {
      eventId,
      eventType: params.eventType,
      triggeredBy: params.triggeredBy,
      userId: params.userId,
      dealId: params.dealId,
      amount: params.amount,
      currency: params.currency || 'INR',
      riskIndicators: params.riskIndicators,
      riskScore: params.riskScore,
      requiresReporting,
      reportType,
      authority,
      autoGenerated: true,
      createdAt: new Date(),
      metadata: params.metadata || {},
    };

    this.events.set(eventId, event);

    if (requiresReporting && reportType && params.userId) {
      const report = reportType === 'STR' 
        ? await this.createSTR({
            userId: params.userId,
            dealId: params.dealId,
            transactionIds: params.dealId ? [params.dealId] : [],
            amount: params.amount || 0,
            currency: params.currency,
            suspicionIndicators: params.riskIndicators,
            narrative: `Auto-generated ${reportType} for ${params.eventType}`,
            createdBy: 'system',
            metadata: params.metadata,
          })
        : await this.createCTR({
            userId: params.userId,
            dealId: params.dealId,
            transactionIds: params.dealId ? [params.dealId] : [],
            amount: params.amount || 0,
            currency: params.currency,
            narrative: `Auto-generated ${reportType} for high-value transaction`,
            createdBy: 'system',
            metadata: params.metadata,
          });

      event.reportId = report.reportId;
      event.processedAt = new Date();
      this.events.set(eventId, event);
    }

    console.log(`[Regulatory Reporting] Registered event ${eventId}, requires reporting: ${requiresReporting}`);
    return event;
  }

  async getReport(reportId: string): Promise<RegulatoryReport | null> {
    return this.reports.get(reportId) || null;
  }

  async getAllReports(filters?: {
    status?: ReportStatus;
    reportType?: ReportType;
    authority?: RegulatoryAuthority;
    startDate?: Date;
    endDate?: Date;
    userId?: string;
  }): Promise<RegulatoryReport[]> {
    let reports = Array.from(this.reports.values());

    if (filters?.status) {
      reports = reports.filter(r => r.status === filters.status);
    }
    if (filters?.reportType) {
      reports = reports.filter(r => r.reportType === filters.reportType);
    }
    if (filters?.authority) {
      reports = reports.filter(r => r.authority === filters.authority);
    }
    if (filters?.startDate) {
      reports = reports.filter(r => r.createdAt >= filters.startDate!);
    }
    if (filters?.endDate) {
      reports = reports.filter(r => r.createdAt <= filters.endDate!);
    }
    if (filters?.userId) {
      reports = reports.filter(r => r.userId === filters.userId);
    }

    return reports.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  async getPendingReports(): Promise<RegulatoryReport[]> {
    return this.getAllReports({ status: 'pending_review' });
  }

  async getReportStats(): Promise<{
    total: number;
    byStatus: Record<ReportStatus, number>;
    byType: Record<ReportType, number>;
    byAuthority: Record<RegulatoryAuthority, number>;
    pendingCount: number;
    submittedLast30Days: number;
  }> {
    const reports = Array.from(this.reports.values());
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const byStatus: Record<ReportStatus, number> = {
      draft: 0,
      pending_review: 0,
      approved: 0,
      submitted: 0,
      acknowledged: 0,
      rejected: 0,
      cancelled: 0,
    };

    const byType: Record<ReportType, number> = {
      STR: 0,
      CTR: 0,
      SAR: 0,
      SFT: 0,
      OTHER: 0,
    };

    const byAuthority: Record<RegulatoryAuthority, number> = {
      SEBI: 0,
      RBI: 0,
      'FIU-IND': 0,
      ED: 0,
      IT: 0,
    };

    let submittedLast30Days = 0;

    for (const report of reports) {
      byStatus[report.status]++;
      byType[report.reportType]++;
      byAuthority[report.authority]++;

      if (report.submittedAt && report.submittedAt >= thirtyDaysAgo) {
        submittedLast30Days++;
      }
    }

    return {
      total: reports.length,
      byStatus,
      byType,
      byAuthority,
      pendingCount: byStatus.pending_review,
      submittedLast30Days,
    };
  }

  async getEventQueue(filters?: {
    requiresReporting?: boolean;
    processed?: boolean;
  }): Promise<ReportableEvent[]> {
    let events = Array.from(this.events.values());

    if (filters?.requiresReporting !== undefined) {
      events = events.filter(e => e.requiresReporting === filters.requiresReporting);
    }
    if (filters?.processed !== undefined) {
      events = events.filter(e => (e.processedAt !== undefined) === filters.processed);
    }

    return events.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  /**
   * Retrieves immutable evidence packs (Regulatory Audit Packs) for a specific report.
   * This is used during audits to prove compliance state at the time of each transaction.
   */
  async getEvidencePacksForReport(reportId: string): Promise<any[]> {
    const report = this.reports.get(reportId);
    if (!report || !report.transactionIds || report.transactionIds.length === 0) {
      return [];
    }

    try {
      const packs = await db
        .select()
        .from(regulatoryAuditPacks)
        .where(inArray(regulatoryAuditPacks.transactionId, report.transactionIds))
        .orderBy(desc(regulatoryAuditPacks.createdAt));
      
      return packs;
    } catch (error) {
      console.error(`[Regulatory Reporting] Failed to fetch evidence packs for report ${reportId}:`, error);
      return [];
    }
  }

  private async persistReport(report: RegulatoryReport, action: string): Promise<void> {
    try {
      await db.insert(complianceAuditTrail).values({
        userId: report.userId || 'system',
        action: `regulatory_${action}`,
        fieldChanged: 'regulatory_report',
        newValue: {
          reportId: report.reportId,
          reportType: report.reportType,
          status: report.status,
        },
        reason: `${report.reportType} report ${action}`,
        performedBy: report.createdBy,
        performedByRole: 'compliance_officer',
        riskImpact: report.riskLevel,
        complianceImpact: report.riskScore >= 60 ? 'major' : 'minor',
        metadata: {
          reportId: report.reportId,
          reportType: report.reportType,
          authority: report.authority,
          status: report.status,
          dealId: report.dealId,
          transactionIds: report.transactionIds,
          amount: report.amount,
          currency: report.currency,
          suspicionIndicators: report.suspicionIndicators,
          riskScore: report.riskScore,
          riskLevel: report.riskLevel,
          narrative: report.narrative,
          createdBy: report.createdBy,
          reviewedBy: report.reviewedBy,
          reviewedAt: report.reviewedAt?.toISOString(),
          reviewNotes: report.reviewNotes,
          submittedBy: report.submittedBy,
          submittedAt: report.submittedAt?.toISOString(),
          referenceNumber: report.referenceNumber,
          acknowledgedAt: report.acknowledgedAt?.toISOString(),
          extra: report.metadata,
        },
      });
    } catch (error) {
      console.error('[Regulatory Reporting] Failed to persist report:', error);
    }
  }
}

export const regulatoryReportingService = new RegulatoryReportingService();
