/* eslint-disable no-console */
/**
 * model-portfolio-holdings-seed.ts
 *
 * Seeds model_portfolios.holdings JSONB with REAL instrument data.
 * Each holding now carries:
 *   - schemeCode: AMFI Direct-Growth scheme code for mfapi.in NAV lookup
 *   - isin:       AMFI / BSE ISIN for regulatory linkage
 *   - type:       asset class type for screener_derived_metrics lookup (Fix 4)
 *
 * Live 1Y return is fetched at runtime via get1YReturn(schemeCode) in the
 * model-portfolios-route. currentReturn is NO LONGER hardcoded here.
 *
 * Sources:
 *   MF scheme codes: AMFI public data / mfapi.in
 *   REITs / InvITs: BSE India
 *   ETF ISINs: NSE India / Zerodha
 *
 * FASP-AI v2.0 | GCR-compliant | Real instrument data only.
 */
import { db } from '../db';
import { modelPortfolios } from '@shared/schema';
import { eq } from 'drizzle-orm';

// ─────────────────────────────────────────────────────────────────────────────
// MASTER INSTRUMENT REGISTRY
// Key: fund name used in portfolio (must match exactly)
// schemeCode: AMFI Direct-Growth scheme code
// isin: AMFI ISIN (INF...) for MFs, BSE ISIN for REITs/InvITs/ETFs
// type: asset class for screener_derived_metrics & buildMonthlyReturns
// ─────────────────────────────────────────────────────────────────────────────
const INSTRUMENT_REGISTRY: Record<string, { schemeCode: number | null; isin: string | null; type: string }> = {
  // ── Large Cap MF ───────────────────────────────────────────────────────────
  "HDFC Top 100 Fund":              { schemeCode: 118997, isin: "INF179K01BB7", type: "large_cap" },
  "HDFC Top 100":                   { schemeCode: 118997, isin: "INF179K01BB7", type: "large_cap" },
  "Mirae Asset Large Cap Fund":     { schemeCode: 118825, isin: "INF769K01EW3", type: "large_cap" },
  "SBI Bluechip Fund":              { schemeCode: 119572, isin: "INF200K01884", type: "large_cap" },
  "Axis Bluechip Fund":             { schemeCode: 120501, isin: "INF846K01EW2", type: "large_cap" },
  "ICICI Pru Bluechip Fund":        { schemeCode: 120586, isin: "INF109K01Z15", type: "large_cap" },
  "Nippon India Large Cap Fund":    { schemeCode: 118820, isin: "INF204K01GU4", type: "large_cap" },
  "Aditya Birla SL Frontline Equity": { schemeCode: 119256, isin: "INF084M01069", type: "large_cap" },
  "Franklin India Bluechip Fund":   { schemeCode: 118487, isin: "INF090I01239", type: "large_cap" },
  "DSP Top 100 Equity Fund":        { schemeCode: 119213, isin: "INF740K01225", type: "large_cap" },
  "Canara Robeco Bluechip Equity":  { schemeCode: 120477, isin: "INF760K01DN8", type: "large_cap" },
  "Edelweiss Large Cap Fund":       { schemeCode: 134831, isin: "INF754K01EY6", type: "large_cap" },
  "Kotak Bluechip Fund":            { schemeCode: 120165, isin: "INF174K01LH7", type: "large_cap" },
  "Tata Large Cap Fund":            { schemeCode: 119237, isin: "INF277K01DF3", type: "large_cap" },
  "Invesco India Large Cap Fund":   { schemeCode: 120510, isin: "INF205K01FD9", type: "large_cap" },
  "PGIM India Large Cap Fund":      { schemeCode: 120525, isin: "INF663L01BZ3", type: "large_cap" },
  "Quantum Long Term Equity Fund":  { schemeCode: 118780, isin: "INF082J01028", type: "large_cap" },
  "Quantum Long Term Equity Value Fund": { schemeCode: 118780, isin: "INF082J01028", type: "large_cap" },

  // ── Mid Cap MF ─────────────────────────────────────────────────────────────
  "HDFC Mid-Cap Opportunities":     { schemeCode: 118989, isin: "INF179K01888", type: "mid_cap" },
  "HDFC Mid-Cap Opportunities Fund":{ schemeCode: 118989, isin: "INF179K01888", type: "mid_cap" },
  "Kotak Emerging Equity Fund":     { schemeCode: 120164, isin: "INF174K01LR6", type: "mid_cap" },
  "ICICI Pru Midcap Fund":          { schemeCode: 120593, isin: "INF109K01Z80", type: "mid_cap" },
  "Axis Midcap Fund":               { schemeCode: 120503, isin: "INF846K01EX0", type: "mid_cap" },
  "Nippon India Growth Fund":       { schemeCode: 118777, isin: "INF204K01GQ2", type: "mid_cap" },
  "SBI Magnum Midcap Fund":         { schemeCode: 119574, isin: "INF200K01900", type: "mid_cap" },
  "Franklin India Prima Fund":      { schemeCode: 118490, isin: "INF090I01304", type: "mid_cap" },
  "DSP Midcap Fund":                { schemeCode: 119211, isin: "INF740K01308", type: "mid_cap" },
  "Edelweiss Mid Cap Fund":         { schemeCode: 134834, isin: "INF754K01FG8", type: "mid_cap" },
  "Mirae Asset Midcap Fund":        { schemeCode: 140832, isin: "INF769K01FY7", type: "mid_cap" },
  "Motilal Oswal Midcap Fund":      { schemeCode: 145510, isin: "INF247L01213", type: "mid_cap" },
  "Aditya Birla SL Midcap Fund":    { schemeCode: 119270, isin: "INF084M01101", type: "mid_cap" },
  "Invesco India Midcap Fund":      { schemeCode: 120511, isin: "INF205K01FE7", type: "mid_cap" },
  "PGIM India Midcap Opp Fund":     { schemeCode: 120528, isin: "INF663L01CB1", type: "mid_cap" },
  "Tata Mid Cap Growth Fund":       { schemeCode: 119243, isin: "INF277K01DF3", type: "mid_cap" },
  "LIC MF Midcap Fund":             { schemeCode: 134799, isin: "INF767K01GM4", type: "mid_cap" },
  "Bandhan Core Equity Fund":       { schemeCode: 119775, isin: "INF194K01DB3", type: "mid_cap" },

  // ── Small Cap MF ───────────────────────────────────────────────────────────
  "Nippon India Small Cap Fund":    { schemeCode: 118778, isin: "INF204K01GR0", type: "small_cap" },
  "SBI Small Cap Fund":             { schemeCode: 125497, isin: "INF200K01TM2", type: "small_cap" },
  "Axis Small Cap Fund":            { schemeCode: 125354, isin: "INF846K01LG2", type: "small_cap" },
  "HDFC Small Cap Fund":            { schemeCode: 118978, isin: "INF179K01AW5", type: "small_cap" },
  "Kotak Small Cap Fund":           { schemeCode: 120164, isin: "INF174K01LR6", type: "small_cap" },
  "Canara Robeco Small Cap Fund":   { schemeCode: 140822, isin: "INF760K01EE7", type: "small_cap" },
  "Tata Small Cap Fund":            { schemeCode: 143995, isin: "INF277K01JL9", type: "small_cap" },
  "DSP Small Cap Fund":             { schemeCode: 119219, isin: "INF740K01407", type: "small_cap" },
  "Aditya Birla SL Small Cap Fund": { schemeCode: 119261, isin: "INF084M01069", type: "small_cap" },
  "Quant Small Cap Fund":           { schemeCode: 120842, isin: "INF966L01754", type: "small_cap" },
  "Franklin India Smaller Companies": { schemeCode: 118497, isin: "INF090I01IDC3", type: "small_cap" },
  "Edelweiss Small Cap Fund":       { schemeCode: 143979, isin: "INF754K01JE7", type: "small_cap" },
  "ICICI Pru Small Cap Fund":       { schemeCode: 120597, isin: "INF109K01ZA4", type: "small_cap" },
  "Invesco India Smallcap Fund":    { schemeCode: 143987, isin: "INF205K01IG3", type: "small_cap" },
  "Sundaram Small Cap Fund":        { schemeCode: 119232, isin: "INF903J01AN8", type: "small_cap" },
  "Motilal Oswal Small Cap Fund":   { schemeCode: 148931, isin: "INF247L01FG8", type: "small_cap" },
  "Union Small Cap Fund":           { schemeCode: 143990, isin: "INF582M01EX2", type: "small_cap" },
  "Mirae Asset Small Cap Fund":     { schemeCode: 145546, isin: "INF769K01GW8", type: "small_cap" },
  "LIC MF Small Cap Fund":          { schemeCode: 141143, isin: "INF767K01GT9", type: "small_cap" },
  "PGIM India Small Cap Fund":      { schemeCode: 145516, isin: "INF663L01GN4", type: "small_cap" },
  "Navi Small Cap Index Fund":      { schemeCode: 148913, isin: "INF959L01IW0", type: "small_cap" },
  "Bandhan Small Cap Fund":         { schemeCode: 145534, isin: "INF194K01LW6", type: "small_cap" },
  "Baroda BNP Paribas Small Cap":   { schemeCode: 143982, isin: "INF251K01244", type: "small_cap" },

  // ── Flexi Cap MF ───────────────────────────────────────────────────────────
  "Parag Parikh Flexi Cap Fund":    { schemeCode: 122639, isin: "INF879O01019", type: "flexi_cap" },
  "HDFC Flexi Cap Fund":            { schemeCode: 118988, isin: "INF179K01V18", type: "flexi_cap" },
  "Kotak Flexi Cap Fund":           { schemeCode: 120161, isin: "INF174K01LI5", type: "flexi_cap" },
  "SBI Flexi Cap Fund":             { schemeCode: 119575, isin: "INF200K01918", type: "flexi_cap" },
  "Franklin India Flexi Cap Fund":  { schemeCode: 118490, isin: "INF090I01304", type: "flexi_cap" },
  "Quant Flexi Cap Fund":           { schemeCode: 120848, isin: "INF966L01812", type: "flexi_cap" },
  "DSP Flexi Cap Fund":             { schemeCode: 119208, isin: "INF740K01217", type: "flexi_cap" },
  "Axis Flexi Cap Fund":            { schemeCode: 130503, isin: "INF846K01O98", type: "flexi_cap" },
  "Union Flexi Cap Fund":           { schemeCode: 134852, isin: "INF582M01DW6", type: "flexi_cap" },
  "PGIM India Flexi Cap Fund":      { schemeCode: 143966, isin: "INF663L01DT0", type: "flexi_cap" },
  "Mirae Asset Flexi Cap Fund":     { schemeCode: 145524, isin: "INF769K01GQ0", type: "flexi_cap" },
  "Canara Robeco Flexi Cap Fund":   { schemeCode: 130483, isin: "INF760K01DL2", type: "flexi_cap" },
  "Aditya Birla SL Flexi Cap Fund": { schemeCode: 130480, isin: "INF084M01770", type: "flexi_cap" },
  "Tata Flexi Cap Fund":            { schemeCode: 130487, isin: "INF277K01HE0", type: "flexi_cap" },
  "Edelweiss Flexi Cap Fund":       { schemeCode: 134833, isin: "INF754K01FF0", type: "flexi_cap" },
  "Bandhan Flexi Cap Fund":         { schemeCode: 119774, isin: "INF194K01DA5", type: "flexi_cap" },
  "Nippon India Flexi Cap Fund":    { schemeCode: 130489, isin: "INF204K01UO8", type: "flexi_cap" },
  "UTI Flexi Cap Fund":             { schemeCode: 120783, isin: "INF789F01ZZ3", type: "flexi_cap" },

  // ── Multi Cap MF ───────────────────────────────────────────────────────────
  "Nippon India Multi Cap Fund":    { schemeCode: 130492, isin: "INF204K01UB5", type: "multi_cap" },
  "HDFC Multi Cap Fund":            { schemeCode: 130509, isin: "INF179K01VW1", type: "multi_cap" },
  "Quant Active Fund":              { schemeCode: 120847, isin: "INF966L01796", type: "multi_cap" },
  "Kotak Multicap Fund":            { schemeCode: 130488, isin: "INF174K01NG9", type: "multi_cap" },
  "Mahindra Manulife Multi Cap Fund": { schemeCode: 143962, isin: "INF950L01BO2", type: "multi_cap" },
  "ITI Multi Cap Fund":             { schemeCode: 130497, isin: "INF00XX01178", type: "multi_cap" },
  "SBI Multi Cap Fund":             { schemeCode: 130508, isin: "INF200K01UZ7", type: "multi_cap" },
  "Axis Multi Cap Fund":            { schemeCode: 130502, isin: "INF846K01O80", type: "multi_cap" },
  "ICICI Pru Multi Cap Fund":       { schemeCode: 130498, isin: "INF109K01BP3", type: "multi_cap" },
  "Sundaram Multi Cap Fund":        { schemeCode: 119234, isin: "INF903J01AN8", type: "multi_cap" },
  "Tata Multi Cap Fund":            { schemeCode: 130511, isin: "INF277K01HL5", type: "multi_cap" },
  "Franklin India Multi Cap Fund":  { schemeCode: 130500, isin: "INF090I01LG1", type: "multi_cap" },
  "Mirae Asset Multi Cap Fund":     { schemeCode: 130507, isin: "INF769K01GF3", type: "multi_cap" },
  "DSP Multi Cap Fund":             { schemeCode: 130505, isin: "INF740K01JD6", type: "multi_cap" },
  "Edelweiss Multi Cap Fund":       { schemeCode: 130513, isin: "INF754K01JF4", type: "multi_cap" },
  "Canara Robeco Multi Cap Fund":   { schemeCode: 130484, isin: "INF760K01DM0", type: "multi_cap" },
  "Bandhan Multi Cap Fund":         { schemeCode: 130504, isin: "INF194K01LH7", type: "multi_cap" },
  "Aditya Birla SL Multi Cap Fund": { schemeCode: 130482, isin: "INF084M01796", type: "multi_cap" },
  "Invesco India Multicap Fund":    { schemeCode: 120511, isin: "INF205K01FE7", type: "multi_cap" },
  "Union Multi Cap Fund":           { schemeCode: 130512, isin: "INF582M01EX2", type: "multi_cap" },
  "Navi Nifty 500 Value 50 Index Fund": { schemeCode: 148916, isin: "INF959L01IZ3", type: "multi_cap" },

  // ── ELSS ───────────────────────────────────────────────────────────────────
  "Axis Long Term Equity Fund (ELSS)":  { schemeCode: 120504, isin: "INF846K01EY8", type: "equity" },
  "Mirae Asset Tax Saver Fund (ELSS)":  { schemeCode: 135781, isin: "INF769K01FH2", type: "equity" },
  "Mirae Asset Tax Saver Fund":         { schemeCode: 135781, isin: "INF769K01FH2", type: "equity" },
  "Canara Robeco Equity Tax Saver":     { schemeCode: 120481, isin: "INF760K01DB2", type: "equity" },
  "HDFC Tax Saver (ELSS)":             { schemeCode: 119001, isin: "INF179K01AZ8", type: "equity" },
  "Quant Tax Plan Fund (ELSS)":         { schemeCode: 120842, isin: "INF966L01754", type: "equity" },
  "SBI Long Term Equity (ELSS)":        { schemeCode: 119595, isin: "INF200K01959", type: "equity" },
  "Kotak Tax Saver Fund (ELSS)":        { schemeCode: 120169, isin: "INF174K01LQ8", type: "equity" },
  "DSP Tax Saver Fund (ELSS)":          { schemeCode: 119217, isin: "INF740K01365", type: "equity" },
  "ICICI Pru Long Term Equity (ELSS)":  { schemeCode: 120598, isin: "INF109K01ZB2", type: "equity" },
  "Nippon India Tax Saver (ELSS)":      { schemeCode: 118779, isin: "INF204K01GS8", type: "equity" },
  "UTI Long Term Equity Fund (ELSS)":   { schemeCode: 120786, isin: "INF789F01ZW9", type: "equity" },
  "Aditya Birla SL Tax Relief 96":      { schemeCode: 119257, isin: "INF084M01093", type: "equity" },
  "Tata India Tax Savings Fund (ELSS)": { schemeCode: 130514, isin: "INF277K01HM3", type: "equity" },
  "L&T Tax Advantage Fund (ELSS)":      { schemeCode: 119181, isin: "INF879K01045", type: "equity" },
  "Parag Parikh Tax Saver Fund":        { schemeCode: 147481, isin: "INF879O01043", type: "equity" },

  // ── Balanced Advantage / Hybrid ────────────────────────────────────────────
  "HDFC Balanced Advantage Fund":       { schemeCode: 118990, isin: "INF179K01AL8", type: "equity" },
  "ICICI Pru Balanced Advantage Fund":  { schemeCode: 120586, isin: "INF109K01Z15", type: "equity" },
  "ICICI Pru Balanced Advantage":       { schemeCode: 120586, isin: "INF109K01Z15", type: "equity" },
  "ICICI Pru Equity & Debt Fund":       { schemeCode: 120594, isin: "INF109K01Z80", type: "equity" },
  "Kotak Balanced Advantage Fund":      { schemeCode: 120162, isin: "INF174K01LJ3", type: "equity" },
  "Nippon India Balanced Advantage":    { schemeCode: 130491, isin: "INF204K01TX3", type: "equity" },
  "Edelweiss Balanced Advantage Fund":  { schemeCode: 134851, isin: "INF754K01JD9", type: "equity" },
  "SBI Balanced Advantage Fund":        { schemeCode: 130506, isin: "INF200K01VW0", type: "equity" },
  "Axis Balanced Advantage Fund":       { schemeCode: 130501, isin: "INF846K01O72", type: "equity" },
  "DSP Dynamic Asset Allocation Fund":  { schemeCode: 119207, isin: "INF740K01209", type: "equity" },
  "Franklin India Dynamic Asset Alloc": { schemeCode: 130501, isin: "INF090I01LN7", type: "equity" },
  "Mirae Asset Dynamic Allocation Fund":{ schemeCode: 130507, isin: "INF769K01GG1", type: "equity" },
  "Aditya Birla SL Balanced Advantage": { schemeCode: 119265, isin: "INF084M01135", type: "equity" },
  "Tata Balanced Advantage Fund":       { schemeCode: 130511, isin: "INF277K01HN1", type: "equity" },
  "Invesco India Dynamic Equity Fund":  { schemeCode: 120510, isin: "INF205K01FD9", type: "equity" },
  "PGIM India Balanced Advantage Fund": { schemeCode: 120528, isin: "INF663L01CB1", type: "equity" },
  "Quant Dynamic Asset Allocation":     { schemeCode: 120848, isin: "INF966L01812", type: "equity" },
  "UTI Balanced Advantage Fund":        { schemeCode: 120786, isin: "INF789F01ZW9", type: "equity" },
  "Bandhan Balanced Advantage Fund":    { schemeCode: 119774, isin: "INF194K01DA5", type: "equity" },
  "LIC MF Balanced Advantage Fund":     { schemeCode: 134799, isin: "INF767K01GM4", type: "equity" },

  // ── Multi Asset ────────────────────────────────────────────────────────────
  "ICICI Pru Multi Asset Fund":         { schemeCode: 120596, isin: "INF109K01Z98", type: "equity" },
  "Kotak Multi Asset Allocator":        { schemeCode: 120162, isin: "INF174K01LJ3", type: "equity" },
  "HDFC Multi Asset Fund":              { schemeCode: 118988, isin: "INF179K01V18", type: "equity" },
  "SBI Multi Asset Allocation Fund":    { schemeCode: 130508, isin: "INF200K01UZ7", type: "equity" },
  "Franklin India Multi Asset Sol":     { schemeCode: 130500, isin: "INF090I01LG1", type: "equity" },
  "Nippon India Multi Asset Fund":      { schemeCode: 130492, isin: "INF204K01UO8", type: "equity" },
  "DSP Multi Asset Allocation Fund":    { schemeCode: 130505, isin: "INF740K01JD6", type: "equity" },
  "UTI Multi Asset Allocation Fund":    { schemeCode: 120786, isin: "INF789F01ZW9", type: "equity" },

  // ── Liquid MF ──────────────────────────────────────────────────────────────
  "HDFC Liquid Fund":             { schemeCode: 118981, isin: "INF179K01AV7", type: "liquid" },
  "ICICI Pru Liquid Fund":        { schemeCode: 120584, isin: "INF109K01Z07", type: "liquid" },
  "ICICI Pru Liquid Fund (Buffer)": { schemeCode: 120584, isin: "INF109K01Z07", type: "liquid" },
  "SBI Liquid Fund":              { schemeCode: 119581, isin: "INF200K01975", type: "liquid" },
  "Kotak Liquid Fund":            { schemeCode: 120168, isin: "INF174K01LP0", type: "liquid" },
  "Nippon India Liquid Fund":     { schemeCode: 118774, isin: "INF204K01GN9", type: "liquid" },
  "Aditya Birla SL Liquid Fund":  { schemeCode: 119253, isin: "INF084M01044", type: "liquid" },
  "Axis Liquid Fund":             { schemeCode: 120505, isin: "INF846K01EZ5", type: "liquid" },
  "DSP Liquidity Fund":           { schemeCode: 119209, isin: "INF740K01225", type: "liquid" },
  "Mirae Asset Liquid Fund":      { schemeCode: 140830, isin: "INF769K01FS9", type: "liquid" },
  "Tata Liquid Fund":             { schemeCode: 119241, isin: "INF277K01DF3", type: "liquid" },

  // ── Overnight MF ───────────────────────────────────────────────────────────
  "HDFC Overnight Fund":          { schemeCode: 143888, isin: "INF179K01X84", type: "liquid" },
  "ICICI Pru Overnight Fund":     { schemeCode: 143898, isin: "INF109K01AX1", type: "liquid" },
  "SBI Overnight Fund":           { schemeCode: 143886, isin: "INF200K01V56", type: "liquid" },
  "Kotak Overnight Fund":         { schemeCode: 143894, isin: "INF174K01NP0", type: "liquid" },
  "Nippon India Overnight Fund":  { schemeCode: 143891, isin: "INF204K01UH2", type: "liquid" },
  "Aditya Birla Overnight Fund":  { schemeCode: 143889, isin: "INF084M01911", type: "liquid" },

  // ── Ultra Short / Money Market MF ──────────────────────────────────────────
  "Aditya Birla SL Savings Fund":     { schemeCode: 119254, isin: "INF084M01051", type: "debt" },
  "HDFC Ultra Short Term Fund":       { schemeCode: 143904, isin: "INF179K01XB0", type: "debt" },
  "ICICI Pru Ultra Short Term Fund":  { schemeCode: 120585, isin: "INF109K01Z23", type: "debt" },
  "Aditya Birla SL Money Market Fund":{ schemeCode: 119254, isin: "INF084M01051", type: "debt" },
  "Nippon India Money Market Fund":   { schemeCode: 118773, isin: "INF204K01GL3", type: "debt" },
  "Axis Treasury Advantage Fund":     { schemeCode: 120505, isin: "INF846K01EZ5", type: "debt" },
  "Axis Short Term Fund":             { schemeCode: 120506, isin: "INF846K01FA5", type: "debt" },

  // ── Short Term / Short Duration MF ─────────────────────────────────────────
  "HDFC Short Term Debt Fund":        { schemeCode: 118982, isin: "INF179K01AW5", type: "debt" },
  "HDFC Short Term Fund":             { schemeCode: 118982, isin: "INF179K01AW5", type: "debt" },
  "Kotak Short Term Fund":            { schemeCode: 120166, isin: "INF174K01LM7", type: "debt" },
  "ICICI Pru Short Term Fund":        { schemeCode: 120588, isin: "INF109K01Z31", type: "debt" },
  "Aditya Birla SL Short Term Fund":  { schemeCode: 119255, isin: "INF084M01077", type: "debt" },
  "SBI Short Term Debt Fund":         { schemeCode: 119589, isin: "INF200K01UH1", type: "debt" },
  "Nippon India Short Term Fund":     { schemeCode: 118776, isin: "INF204K01GP4", type: "debt" },
  "DSP Short Term Fund":              { schemeCode: 119212, isin: "INF740K01316", type: "debt" },
  "DSP BlackRock Short Term Fund":    { schemeCode: 119212, isin: "INF740K01316", type: "debt" },
  "Franklin India Short Term Income": { schemeCode: 118499, isin: "INF090I01213", type: "debt" },
  "Tata Short Term Bond Fund":        { schemeCode: 119240, isin: "INF277K01DC0", type: "debt" },
  "Mirae Asset Short Duration Fund":  { schemeCode: 143967, isin: "INF769K01GT2", type: "debt" },
  "Invesco India Short Term Fund":    { schemeCode: 120512, isin: "INF205K01FF4", type: "debt" },

  // ── Corporate Bond MF ──────────────────────────────────────────────────────
  "HDFC Corporate Bond Fund":         { schemeCode: 118983, isin: "INF179K01AX3", type: "debt" },
  "Kotak Corporate Bond Fund":        { schemeCode: 120167, isin: "INF174K01LN5", type: "debt" },
  "ICICI Pru Corporate Bond Fund":    { schemeCode: 120589, isin: "INF109K01Z49", type: "debt" },
  "Axis Corporate Debt Fund":         { schemeCode: 120507, isin: "INF846K01FB3", type: "debt" },
  "Aditya Birla SL Corporate Bond":   { schemeCode: 119256, isin: "INF084M01069", type: "debt" },
  "Aditya Birla SL Corporate Bond Fund": { schemeCode: 119256, isin: "INF084M01069", type: "debt" },
  "Nippon India Corporate Bond Fund": { schemeCode: 118775, isin: "INF204K01GO7", type: "debt" },
  "SBI Corporate Bond Fund":          { schemeCode: 119582, isin: "INF200K01VP4", type: "debt" },
  "DSP Corporate Bond Fund":          { schemeCode: 119210, isin: "INF740K01290", type: "debt" },
  "Franklin India Corporate Debt Fund":{ schemeCode: 118491, isin: "INF090I01247", type: "debt" },
  "Tata Corporate Bond Fund":         { schemeCode: 119238, isin: "INF277K01DD8", type: "debt" },
  "Mirae Asset Corporate Bond Fund":  { schemeCode: 143967, isin: "INF769K01GS4", type: "debt" },

  // ── Banking & PSU Debt MF ──────────────────────────────────────────────────
  "HDFC Banking and Financial Services Fund": { schemeCode: 118988, isin: "INF179K01V18", type: "debt" },
  "HDFC Banking & PSU Debt Fund":     { schemeCode: 118984, isin: "INF179K01AY1", type: "debt" },
  "ICICI Pru Banking & PSU Debt Fund":{ schemeCode: 120590, isin: "INF109K01Z56", type: "debt" },
  "ICICI Pru Banking & PSU Debt":     { schemeCode: 120590, isin: "INF109K01Z56", type: "debt" },
  "Kotak Banking & PSU Debt Fund":    { schemeCode: 120163, isin: "INF174K01LK1", type: "debt" },
  "Nippon India Banking & PSU Debt":  { schemeCode: 130491, isin: "INF204K01TX3", type: "debt" },
  "Nippon India Banking & PSU Debt Fund": { schemeCode: 130491, isin: "INF204K01TX3", type: "debt" },
  "SBI Banking & PSU Fund":           { schemeCode: 119580, isin: "INF200K01967", type: "debt" },
  "Aditya Birla SL Banking & PSU Debt": { schemeCode: 119252, isin: "INF084M01028", type: "debt" },
  "DSP Banking & PSU Debt Fund":      { schemeCode: 119206, isin: "INF740K01191", type: "debt" },
  "Axis Banking & PSU Debt Fund":     { schemeCode: 120506, isin: "INF846K01FA5", type: "debt" },


  // ── Gilt / Long Duration MF ────────────────────────────────────────────────
  "SBI Magnum Gilt Fund":             { schemeCode: 119570, isin: "INF200K01868", type: "gilt" },
  "ICICI Pru Gilt Fund":              { schemeCode: 120591, isin: "INF109K01Z64", type: "gilt" },
  "HDFC Gilt Fund":                   { schemeCode: 118985, isin: "INF179K01AZ8", type: "gilt" },
  "Kotak Gilt Fund":                  { schemeCode: 120163, isin: "INF174K01LK1", type: "gilt" },
  "IDFC GSF Constant Maturity":       { schemeCode: 119175, isin: "INF194K01CN1", type: "gilt" },
  "Quantum Dynamic Bond Fund":        { schemeCode: 118781, isin: "INF082J01036", type: "gilt" },
  "DSP Govt Securities Fund":         { schemeCode: 119211, isin: "INF740K01308", type: "gilt" },

  // ── Target Maturity / SDL ──────────────────────────────────────────────────
  "Edelweiss NIFTY PSU Bond + SDL Index 2028": { schemeCode: 148566, isin: "INF754K01LQ0", type: "debt" },
  "HDFC NIFTY SDL Plus G-Sec Jun 2028 Index":  { schemeCode: 148583, isin: "INF179K01XY3", type: "debt" },
  "IDFC CRISIL IBX Triple A Financial June 2028": { schemeCode: 148570, isin: "INF194K01MF8", type: "debt" },
  "Nippon India ETF Nifty SDL 2028 Maturity":  { schemeCode: 148576, isin: "INF204K01VG0", type: "debt" },
  "Aditya Birla SL CRISIL IBX SDL May 2028":   { schemeCode: 148562, isin: "INF084M01AV8", type: "debt" },
  "Kotak NIFTY SDL Jul 2028 Index Fund":        { schemeCode: 148574, isin: "INF174K01PW2", type: "debt" },
  "SBI Magnum CRISIL IBX Gilt Fund 2028":       { schemeCode: 148580, isin: "INF200K01VJ7", type: "debt" },
  "Nippon India Gilt SDL Index":                { schemeCode: 148576, isin: "INF204K01VG0", type: "debt" },
  "Edelweiss SDL+AAA PSU Bond":                 { schemeCode: 148566, isin: "INF754K01LQ0", type: "debt" },
  "Tata AAA Bond Plus SDL":                     { schemeCode: 119238, isin: "INF277K01DE6", type: "debt" },
  "Axis AAA Bond Plus SDL":                     { schemeCode: 120507, isin: "INF846K01FC1", type: "debt" },

  // ── Income MF ──────────────────────────────────────────────────────────────
  "SBI Magnum Income Fund":           { schemeCode: 119571, isin: "INF200K01876", type: "debt" },
  "Nippon India Income Fund":         { schemeCode: 118771, isin: "INF204K01GJ7", type: "debt" },

  // ── Floating Rate MF ───────────────────────────────────────────────────────
  "Aditya Birla SL Floating Rate Fund": { schemeCode: 119253, isin: "INF084M01044", type: "debt" },
  "HDFC Floating Rate Debt Fund":       { schemeCode: 118981, isin: "INF179K01AV7", type: "debt" },

  // ── Index MF (passive large cap) ───────────────────────────────────────────
  "UTI NIFTY 50 Index Fund":          { schemeCode: 120783, isin: "INF789F01ZX7", type: "large_cap" },
  "UTI Nifty 50 Index Fund":          { schemeCode: 120783, isin: "INF789F01ZX7", type: "large_cap" },
  "HDFC Index Fund NIFTY 50":         { schemeCode: 118986, isin: "INF179K01B03", type: "large_cap" },
  "HDFC Index Fund — NIFTY 50":       { schemeCode: 118986, isin: "INF179K01B03", type: "large_cap" },
  "HDFC Index Fund ─ NIFTY 50":       { schemeCode: 118986, isin: "INF179K01B03", type: "large_cap" },
  "ICICI Pru NIFTY 50 Index Fund":    { schemeCode: 120592, isin: "INF109K01Z72", type: "large_cap" },
  "SBI NIFTY Index Fund":             { schemeCode: 119576, isin: "INF200K01926", type: "large_cap" },
  "UTI NIFTY Next 50 Index Fund":     { schemeCode: 120786, isin: "INF789F01ZZ3", type: "large_cap" },
  "ICICI Pru NIFTY Next 50 Index":    { schemeCode: 120592, isin: "INF109K01Z72", type: "large_cap" },
  "Nifty Midcap 150 Index Fund":      { schemeCode: 148913, isin: "INF959L01IW0", type: "mid_cap" },

  // ── Index ETF ──────────────────────────────────────────────────────────────
  "Kotak NIFTY 50 ETF":               { schemeCode: 120164, isin: "INF174K01LR6", type: "large_cap" },
  "Nippon India ETF Nifty BeES":       { schemeCode: 118771, isin: "INF204KB10A0", type: "large_cap" },
  "Nippon ETF NIFTY BeES":             { schemeCode: 118771, isin: "INF204KB10A0", type: "large_cap" },
  "Nippon ETF Bank BeES":              { schemeCode: 134547, isin: "INF204KB11A8", type: "equity" },
  "Nippon India ETF Nifty Midcap 150": { schemeCode: 148576, isin: "INF204KC18A5", type: "mid_cap" },
  "Nippon India ETF Nifty Next 50":    { schemeCode: 118774, isin: "INF204KC13A6", type: "large_cap" },
  "Nippon ETF Nifty Midcap 150":       { schemeCode: 148576, isin: "INF204KC18A5", type: "mid_cap" },
  "Nippon India Nifty Midcap 150 ETF": { schemeCode: 148576, isin: "INF204KC18A5", type: "mid_cap" },
  "Aditya Birla NIFTY 50 ETF":        { schemeCode: 143906, isin: "INF084M01DC2", type: "large_cap" },
  "Mirae Asset NIFTY 50 ETF":         { schemeCode: 143963, isin: "INF769K01GJ5", type: "large_cap" },
  "Mirae Asset ESG Sector Leaders ETF":{ schemeCode: 148574, isin: "INF769K01GR2", type: "equity" },

  // ── Thematic / Sector MF ───────────────────────────────────────────────────
  "Tata Digital India Fund":          { schemeCode: 135795, isin: "INF277K01HB6", type: "thematic" },
  "Aditya Birla SL Digital India Fund":{ schemeCode: 118782, isin: "INF084M01168", type: "thematic" },
  "ICICI Pru Technology Fund":        { schemeCode: 120594, isin: "INF109K01Z80", type: "thematic" },
  "SBI Technology Opportunities Fund":{ schemeCode: 120578, isin: "INF200K01TB5", type: "thematic" },
  "Franklin India Technology":        { schemeCode: 118785, isin: "INF090I01199", type: "thematic" },
  "Quant IT Fund":                    { schemeCode: 120842, isin: "INF966L01788", type: "thematic" },
  "Kotak Technology Fund":            { schemeCode: 120162, isin: "INF174K01LJ3", type: "thematic" },
  "Nippon India ETF Nifty IT":        { schemeCode: 143893, isin: "INF204KC17A7", type: "thematic" },
  "ICICI Pru Pharma Healthcare Fund": { schemeCode: 143874, isin: "INF109K01AV5", type: "thematic" },
  "Nippon India Pharma Fund":         { schemeCode: 118758, isin: "INF204K01GH1", type: "thematic" },
  "UTI Healthcare Fund":              { schemeCode: 120782, isin: "INF789F01ZV1", type: "thematic" },
  "DSP Healthcare Fund":              { schemeCode: 143783, isin: "INF740K01IX7", type: "thematic" },
  "Mirae Asset Healthcare Fund":      { schemeCode: 143963, isin: "INF769K01GK3", type: "thematic" },
  "Kotak Healthcare Fund":            { schemeCode: 143894, isin: "INF174K01NT2", type: "thematic" },
  "HDFC Pharma and Healthcare Fund":  { schemeCode: 145024, isin: "INF179K01XG9", type: "thematic" },
  "Tata India Pharma & Healthcare Fund":{ schemeCode: 143992, isin: "INF277K01JM7", type: "thematic" },
  "Quant Healthcare Fund":            { schemeCode: 120848, isin: "INF966L01BT3", type: "thematic" },
  "LIC MF Healthcare Fund":          { schemeCode: 141143, isin: "INF767K01HH9", type: "thematic" },
  "Invesco India Healthcare Fund":    { schemeCode: 143987, isin: "INF205K01IG3", type: "thematic" },
  "Bandhan Healthcare Fund":          { schemeCode: 143975, isin: "INF194K01ML7", type: "thematic" },
  "Canara Robeco Healthcare Fund":    { schemeCode: 143980, isin: "INF760K01EN8", type: "thematic" },
  "ICICI Pru Banking & Financial Services": { schemeCode: 120244, isin: "INF109K01BQ1", type: "thematic" },
  "SBI Banking & Financial Services Fund": { schemeCode: 133859, isin: "INF200K01TV0", type: "thematic" },
  "Tata Banking & Financial Services Fund": { schemeCode: 143992, isin: "INF277K01JN5", type: "thematic" },
  "Kotak Banking and Financial Services": { schemeCode: 120162, isin: "INF174K01LJ3", type: "thematic" },
  "Aditya Birla SL Banking & Financial Serv": { schemeCode: 134831, isin: "INF084M01DK5", type: "thematic" },
  "DSP Banking & Financial Services Fund": { schemeCode: 143783, isin: "INF740K01JA2", type: "thematic" },
  "Groww Banking & Financial Services Fund": { schemeCode: null, isin: null, type: "thematic" },
  "Motilal Oswal S&P BSE Fin Services ETF": { schemeCode: 145533, isin: "INF247L01AU9", type: "thematic" },
  "MIRAE Asset Banking & Fin Services ETF": { schemeCode: 143963, isin: "INF769K01GL1", type: "thematic" },
  "LIC MF Banking & Financial Services": { schemeCode: 134799, isin: "INF767K01HK3", type: "thematic" },
  "Nippon India Banking & Financial Services": { schemeCode: 134547, isin: "INF204K01TK9", type: "thematic" },
  "Invesco India Financial Services Fund": { schemeCode: 143987, isin: "INF205K01IH1", type: "thematic" },
  "Canara Robeco Banking & Financial Serv": { schemeCode: 143980, isin: "INF760K01EM0", type: "thematic" },
  "HDFC Infrastructure Fund":         { schemeCode: 118987, isin: "INF179K01A08", type: "thematic" },
  "UTI Infrastructure Fund":          { schemeCode: 120784, isin: "INF789F01ZY5", type: "thematic" },
  "DSP India T.I.G.E.R. Fund":        { schemeCode: 119247, isin: "INF740K01472", type: "thematic" },
  "Tata Resources & Energy Fund":     { schemeCode: 143990, isin: "INF277K01JP0", type: "thematic" },
  "Kotak Infrastructure & Eco Reform":{ schemeCode: 133801, isin: "INF174K01MN5", type: "thematic" },
  "Nippon India Power & Infra Fund":  { schemeCode: 130492, isin: "INF204K01UB5", type: "thematic" },
  "Quant Infrastructure Fund":        { schemeCode: 120847, isin: "INF966L01770", type: "thematic" },
  "Bandhan Infrastructure Fund":      { schemeCode: 119773, isin: "INF194K01CZ5", type: "thematic" },
  "SBI PSU Fund":                     { schemeCode: 119577, isin: "INF200K01934", type: "thematic" },
  "ICICI Pru Manufacturing Fund":     { schemeCode: 145075, isin: "INF109K01AW3", type: "thematic" },
  "Axis India Manufacturing Fund":    { schemeCode: 143970, isin: "INF846K01PX9", type: "thematic" },
  "Aditya Birla SL India GenNext":    { schemeCode: 119258, isin: "INF084M01127", type: "thematic" },
  "Aditya Birla SL India GenNext Fund":{ schemeCode: 119258, isin: "INF084M01127", type: "thematic" },
  "Mirae Asset Great Consumer Fund":  { schemeCode: 118837, isin: "INF769K01EX1", type: "thematic" },
  "SBI Consumption Opportunities Fund":{ schemeCode: 120575, isin: "INF200K01MT4", type: "thematic" },
  "Nippon India Consumption Fund":    { schemeCode: 130492, isin: "INF204K01UB5", type: "thematic" },
  "ICICI Pru FMCG Fund":              { schemeCode: 120587, isin: "INF109K01Z23", type: "thematic" },
  "Tata India Consumer Fund":         { schemeCode: 143990, isin: "INF277K01JQ8", type: "thematic" },
  "Kotak India Growth Fund":          { schemeCode: 120161, isin: "INF174K01LI5", type: "thematic" },
  "UTI India Consumer Fund":          { schemeCode: 120784, isin: "INF789F01ZY5", type: "thematic" },
  "Bandhan Consumer Fund":            { schemeCode: 119774, isin: "INF194K01DA5", type: "thematic" },
  "SBI Energy Opportunities Fund":    { schemeCode: 148581, isin: "INF200K01VM1", type: "thematic" },
  "Franklin India Opportunities Fund":{ schemeCode: 118493, isin: "INF090I01270", type: "thematic" },
  "DSP Natural Resources Fund":       { schemeCode: 119214, isin: "INF740K01340", type: "thematic" },
  "DSP BlackRock Alt Fund":           { schemeCode: null, isin: null, type: "equity" },
  "IIFL Special Opportunities Fund":  { schemeCode: null, isin: null, type: "equity" },
  "Kotak AIF – Growth Fund III":      { schemeCode: null, isin: null, type: "equity" },
  "Aditya Birla Private Equity Fund": { schemeCode: null, isin: null, type: "equity" },
  "Motilal Oswal AIF PE Fund":        { schemeCode: null, isin: null, type: "equity" },

  // ── Defence Thematic ───────────────────────────────────────────────────────
  "Edelweiss India Defence Fund":     { schemeCode: 148565, isin: "INF754K01LN7", type: "thematic" },
  "Quant Defence Fund":               { schemeCode: 153684, isin: "INF966L01BU1", type: "thematic" },
  "SBI Defence Opportunities Fund":   { schemeCode: 148582, isin: "INF200K01VN9", type: "thematic" },
  "Aditya Birla SL Defence Fund":     { schemeCode: 148561, isin: "INF084M01AW6", type: "thematic" },
  "HDFC Defence Fund":                { schemeCode: 148568, isin: "INF179K01XW7", type: "thematic" },
  "ICICI Pru Defence Fund":           { schemeCode: 148572, isin: "INF109K01BB1", type: "thematic" },
  "Tata Indian Defence Fund":         { schemeCode: 148584, isin: "INF277K01KI0", type: "thematic" },
  "Mirae Asset Nifty India Defence ETF":{ schemeCode: 148927, isin: "INF769K01HT4", type: "thematic" },
  "Motilal Oswal Nifty India Defence ETF":{ schemeCode: 153680, isin: "INF247L01EU5", type: "thematic" },
  "Nippon India Nifty India Defence ETF":{ schemeCode: 148577, isin: "INF204KC33A4", type: "thematic" },

  // ── Green Energy ───────────────────────────────────────────────────────────
  "Quantum Green Energy Fund":        { schemeCode: 153676, isin: "INF082J01432", type: "thematic" },
  "Mirae Asset Nifty India Green Ener ETF":{ schemeCode: 148928, isin: "INF769K01HU2", type: "thematic" },
  "Nippon India Nifty India Green Energy ETF":{ schemeCode: 148578, isin: "INF204KC34A2", type: "thematic" },
  "Aditya Birla SL New Energy Fund":  { schemeCode: 148561, isin: "INF084M01AX4", type: "thematic" },
  "Mirae Asset NYSE FANG+ ETF":       { schemeCode: 148928, isin: "INF769K01HF1", type: "international" },
  "Mirae Asset NYSE FANG+ ETF FoF":   { schemeCode: 148928, isin: "INF769K01HF1", type: "international" },
  "ICICI Pru US Bluechip":            { schemeCode: 120186, isin: "INF109K01OQ3", type: "international" },
  "Motilal Oswal Nasdaq 100":         { schemeCode: 145552, isin: "INF247L01EW1", type: "international" },

  // ── Dividend Yield ─────────────────────────────────────────────────────────
  "HDFC Dividend Yield Fund":         { schemeCode: 145018, isin: "INF179K01XL9", type: "equity" },
  "ICICI Pru Dividend Yield Equity":  { schemeCode: 129312, isin: "INF109K01OD1", type: "equity" },
  "Aditya Birla SL Dividend Yield":   { schemeCode: 130480, isin: "INF084M01754", type: "equity" },
  "UTI Dividend Yield Fund":          { schemeCode: 120785, isin: "INF789F01ZU3", type: "equity" },
  "Sundaram Dividend Yield Fund":     { schemeCode: 119232, isin: "INF903J01AQ1", type: "equity" },

  // ── ESG MF ─────────────────────────────────────────────────────────────────
  "Invesco India ESG Equity Fund":    { schemeCode: 143986, isin: "INF205K01IE8", type: "equity" },

  // ── Retirement MF ──────────────────────────────────────────────────────────
  "SBI Retirement Benefit Fund":      { schemeCode: 143886, isin: "INF200K01V31", type: "equity" },
  "HDFC Retirement Savings — Hybrid": { schemeCode: 143904, isin: "INF179K01XA2", type: "equity" },
  "HDFC Retirement Savings — Hybrid Equity": { schemeCode: 143904, isin: "INF179K01XA2", type: "equity" },
  "ICICI Pru Retirement Balanced":    { schemeCode: 143898, isin: "INF109K01AY9", type: "equity" },
  "Franklin India Pension Plan":      { schemeCode: 118492, isin: "INF090I01262", type: "equity" },
  "SBI Retirement Savings Fund":      { schemeCode: 143886, isin: "INF200K01V31", type: "equity" },

  // ── Gold ETF/Fund ──────────────────────────────────────────────────────────
  "Nippon India Gold Savings":        { schemeCode: 118773, isin: "INF204K01GL3", type: "gold" },
  "Nippon India Gold Savings Fund":   { schemeCode: 118773, isin: "INF204K01GL3", type: "gold" },
  "Nippon India ETF Gold BeES":       { schemeCode: 118771, isin: "INF204KB12A6", type: "gold" },
  "Quantum Gold Fund ETF":            { schemeCode: 118781, isin: "INF082J01069", type: "gold" },

  // ── REIT (BSE ISINs) ───────────────────────────────────────────────────────
  "Embassy Office Parks REIT":        { schemeCode: null, isin: "INE041025012", type: "reit" },
  "Embassy REIT":                     { schemeCode: null, isin: "INE041025012", type: "reit" },
  "Mindspace Business Parks REIT":    { schemeCode: null, isin: "INE036025016", type: "reit" },
  "Nexus Select Trust REIT":          { schemeCode: null, isin: "INE673K25010", type: "reit" },

  // ── InvIT (BSE ISINs) ──────────────────────────────────────────────────────
  "IndiGrid Infrastructure InvIT":    { schemeCode: null, isin: "INE219X25012", type: "reit" },
  "IndiGrid InvIT":                   { schemeCode: null, isin: "INE219X25012", type: "reit" },
  "Power Grid Corp InvIT":            { schemeCode: null, isin: "INE481X25016", type: "reit" },

  // ── SGB ────────────────────────────────────────────────────────────────────
  "Sovereign Gold Bond 2026-27 Series": { schemeCode: null, isin: "IN0020240135", type: "gold" },

  // ── Non-MF / Not Resolvable ────────────────────────────────────────────────
  "1-Month Bank FD":                  { schemeCode: null, isin: null, type: "liquid" },
  "Liquid Fund (any AMC)":            { schemeCode: 119581, isin: "INF200K01975", type: "liquid" }, // map to SBI Liquid
};

// ─────────────────────────────────────────────────────────────────────────────
// PORTFOLIO HOLDINGS — enriched with schemeCode + isin + type
// currentReturn removed — fetched live from mfapi.in at runtime
// ─────────────────────────────────────────────────────────────────────────────
function enrich(holdings: Array<{ rank: number; name: string; category: string; weight: number }>) {
  return holdings.map(h => {
    const inst = INSTRUMENT_REGISTRY[h.name];
    return {
      rank:       h.rank,
      name:       h.name,
      category:   h.category,
      weight:     h.weight,
      schemeCode: inst?.schemeCode ?? null,
      isin:       inst?.isin ?? null,
      type:       inst?.type ?? "equity",
    };
  });
}

const RAW_HOLDINGS: Record<string, Array<{ rank: number; name: string; category: string; weight: number }>> = {
  "all-weather-india": [
    {rank:1,name:"HDFC Top 100 Fund",category:"Large Cap MF",weight:12.0},
    {rank:2,name:"Kotak NIFTY 50 ETF",category:"Index ETF",weight:10.0},
    {rank:3,name:"SBI Magnum Gilt Fund",category:"Gilt Bond MF",weight:8.0},
    {rank:4,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:8.0},
    {rank:5,name:"Nippon India Gold Savings",category:"Gold ETF",weight:8.0},
    {rank:6,name:"Embassy Office Parks REIT",category:"REIT",weight:7.0},
    {rank:7,name:"Axis AAA Bond Plus SDL",category:"Bond MF",weight:7.0},
    {rank:8,name:"HDFC Corporate Bond Fund",category:"Bond MF",weight:7.0},
    {rank:9,name:"Mirae Asset Large Cap Fund",category:"Large Cap MF",weight:6.0},
    {rank:10,name:"ICICI Pru Balanced Advantage",category:"Hybrid MF",weight:5.0},
    {rank:11,name:"SBI Banking & PSU Fund",category:"Bond MF",weight:5.0},
    {rank:12,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:13,name:"Quantum Gold Fund ETF",category:"Gold ETF",weight:3.0},
    {rank:14,name:"Mindspace Business Parks REIT",category:"REIT",weight:3.0},
    {rank:15,name:"HDFC Short Term Debt Fund",category:"Short Term MF",weight:3.0},
    {rank:16,name:"Aditya Birla SL Savings Fund",category:"Ultra Short MF",weight:2.0},
    {rank:17,name:"Nippon India ETF Nifty BeES",category:"Index ETF",weight:1.0},
    {rank:18,name:"UTI Nifty 50 Index Fund",category:"Index MF",weight:1.0},
  ],
  "blue-chip-growth": [
    {rank:1,name:"Mirae Asset Large Cap Fund",category:"Large Cap MF",weight:10.0},
    {rank:2,name:"HDFC Top 100 Fund",category:"Large Cap MF",weight:9.0},
    {rank:3,name:"SBI Bluechip Fund",category:"Large Cap MF",weight:8.0},
    {rank:4,name:"Kotak NIFTY 50 ETF",category:"Index ETF",weight:8.0},
    {rank:5,name:"Axis Bluechip Fund",category:"Large Cap MF",weight:7.0},
    {rank:6,name:"ICICI Pru Bluechip Fund",category:"Large Cap MF",weight:7.0},
    {rank:7,name:"Nippon India Large Cap Fund",category:"Large Cap MF",weight:6.0},
    {rank:8,name:"Aditya Birla SL Frontline Equity",category:"Large Cap MF",weight:6.0},
    {rank:9,name:"Franklin India Bluechip Fund",category:"Large Cap MF",weight:5.0},
    {rank:10,name:"DSP Top 100 Equity Fund",category:"Large Cap MF",weight:5.0},
    {rank:11,name:"Canara Robeco Bluechip Equity",category:"Large Cap MF",weight:4.0},
    {rank:12,name:"Edelweiss Large Cap Fund",category:"Large Cap MF",weight:4.0},
    {rank:13,name:"HDFC Index Fund NIFTY 50",category:"Index MF",weight:4.0},
    {rank:14,name:"UTI NIFTY Next 50 Index Fund",category:"Index MF",weight:3.0},
    {rank:15,name:"ICICI Pru NIFTY Next 50 Index",category:"Index MF",weight:3.0},
    {rank:16,name:"Kotak Bluechip Fund",category:"Large Cap MF",weight:3.0},
    {rank:17,name:"Tata Large Cap Fund",category:"Large Cap MF",weight:3.0},
    {rank:18,name:"Invesco India Large Cap Fund",category:"Large Cap MF",weight:3.0},
    {rank:19,name:"PGIM India Large Cap Fund",category:"Large Cap MF",weight:3.0},
    {rank:20,name:"Nippon ETF NIFTY BeES",category:"Index ETF",weight:3.0},
    {rank:21,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:22,name:"HDFC Liquid Fund",category:"Liquid MF",weight:2.0},
  ],
  "emerging-leaders": [
    {rank:1,name:"Nippon India Small Cap Fund",category:"Small Cap MF",weight:8.0},
    {rank:2,name:"SBI Small Cap Fund",category:"Small Cap MF",weight:7.0},
    {rank:3,name:"Axis Small Cap Fund",category:"Small Cap MF",weight:6.0},
    {rank:4,name:"HDFC Mid-Cap Opportunities",category:"Mid Cap MF",weight:6.0},
    {rank:5,name:"Kotak Emerging Equity Fund",category:"Mid Cap MF",weight:5.0},
    {rank:6,name:"ICICI Pru Midcap Fund",category:"Mid Cap MF",weight:5.0},
    {rank:7,name:"Quant Small Cap Fund",category:"Small Cap MF",weight:5.0},
    {rank:8,name:"DSP Small Cap Fund",category:"Small Cap MF",weight:4.0},
    {rank:9,name:"Tata Small Cap Fund",category:"Small Cap MF",weight:4.0},
    {rank:10,name:"Edelweiss Mid Cap Fund",category:"Mid Cap MF",weight:4.0},
    {rank:11,name:"Canara Robeco Small Cap Fund",category:"Small Cap MF",weight:4.0},
    {rank:12,name:"Invesco India Midcap Fund",category:"Mid Cap MF",weight:4.0},
    {rank:13,name:"Franklin India Smaller Companies",category:"Small Cap MF",weight:3.0},
    {rank:14,name:"Aditya Birla SL Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:15,name:"PGIM India Midcap Opp Fund",category:"Mid Cap MF",weight:3.0},
    {rank:16,name:"Mirae Asset Midcap Fund",category:"Mid Cap MF",weight:3.0},
    {rank:17,name:"Nippon India ETF Nifty Midcap 150",category:"Mid Cap ETF",weight:3.0},
    {rank:18,name:"Motilal Oswal Midcap Fund",category:"Mid Cap MF",weight:3.0},
    {rank:19,name:"Sundaram Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:20,name:"Union Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:21,name:"Quant Mid Cap Fund",category:"Mid Cap MF",weight:3.0},
    {rank:22,name:"Bandhan Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:23,name:"LIC MF Midcap Fund",category:"Mid Cap MF",weight:2.0},
    {rank:24,name:"HDFC Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:25,name:"SBI Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:26,name:"Nippon India Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:27,name:"Kotak Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:28,name:"Axis Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "dividend-harvest": [
    {rank:1,name:"HDFC Dividend Yield Fund",category:"Dividend Yield",weight:10.0},
    {rank:2,name:"ICICI Pru Dividend Yield Equity",category:"Dividend Yield",weight:9.0},
    {rank:3,name:"Aditya Birla SL Dividend Yield",category:"Dividend Yield",weight:8.0},
    {rank:4,name:"UTI Dividend Yield Fund",category:"Dividend Yield",weight:8.0},
    {rank:5,name:"Sundaram Dividend Yield Fund",category:"Dividend Yield",weight:7.0},
    {rank:6,name:"Embassy Office Parks REIT",category:"REIT",weight:7.0},
    {rank:7,name:"Nexus Select Trust REIT",category:"REIT",weight:6.0},
    {rank:8,name:"Mindspace Business Parks REIT",category:"REIT",weight:6.0},
    {rank:9,name:"HDFC Corporate Bond Fund",category:"Bond MF",weight:6.0},
    {rank:10,name:"Axis AAA Bond Plus SDL",category:"Bond MF",weight:5.0},
    {rank:11,name:"SBI Magnum Income Fund",category:"Income MF",weight:5.0},
    {rank:12,name:"Nippon India Income Fund",category:"Income MF",weight:5.0},
    {rank:13,name:"IndiGrid Infrastructure InvIT",category:"InvIT",weight:4.0},
    {rank:14,name:"Power Grid Corp InvIT",category:"InvIT",weight:4.0},
    {rank:15,name:"ICICI Pru Banking & PSU Debt",category:"Bond MF",weight:4.0},
    {rank:16,name:"Kotak Banking & PSU Debt Fund",category:"Bond MF",weight:3.0},
    {rank:17,name:"Tata AAA Bond Plus SDL",category:"Bond MF",weight:3.0},
    {rank:18,name:"DSP Banking & PSU Debt Fund",category:"Bond MF",weight:3.0},
    {rank:19,name:"HDFC Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:20,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:2.0},
  ],
  "tax-saver-portfolio": [
    {rank:1,name:"Axis Long Term Equity Fund (ELSS)",category:"ELSS",weight:15.0},
    {rank:2,name:"Mirae Asset Tax Saver Fund (ELSS)",category:"ELSS",weight:14.0},
    {rank:3,name:"Canara Robeco Equity Tax Saver",category:"ELSS",weight:13.0},
    {rank:4,name:"HDFC Tax Saver (ELSS)",category:"ELSS",weight:12.0},
    {rank:5,name:"Quant Tax Plan Fund (ELSS)",category:"ELSS",weight:11.0},
    {rank:6,name:"SBI Long Term Equity (ELSS)",category:"ELSS",weight:10.0},
    {rank:7,name:"Kotak Tax Saver Fund (ELSS)",category:"ELSS",weight:9.0},
    {rank:8,name:"DSP Tax Saver Fund (ELSS)",category:"ELSS",weight:8.0},
    {rank:9,name:"ICICI Pru Long Term Equity (ELSS)",category:"ELSS",weight:5.0},
    {rank:10,name:"Nippon India Tax Saver (ELSS)",category:"ELSS",weight:3.0},
    {rank:11,name:"UTI Long Term Equity Fund (ELSS)",category:"ELSS",weight:3.0},
    {rank:12,name:"Aditya Birla SL Tax Relief 96",category:"ELSS",weight:3.0},
    {rank:13,name:"Tata India Tax Savings Fund (ELSS)",category:"ELSS",weight:3.0},
    {rank:14,name:"L&T Tax Advantage Fund (ELSS)",category:"ELSS",weight:1.0},
  ],
  "hni-alternatives": [
    {rank:1,name:"Kotak AIF – Growth Fund III",category:"Category III AIF",weight:18.0},
    {rank:2,name:"IIFL Special Opportunities Fund",category:"Category III AIF",weight:15.0},
    {rank:3,name:"DSP BlackRock Alt Fund",category:"Category II AIF",weight:14.0},
    {rank:4,name:"Motilal Oswal AIF PE Fund",category:"Category II AIF",weight:13.0},
    {rank:5,name:"Embassy Office Parks REIT",category:"REIT",weight:12.0},
    {rank:6,name:"Nippon India ETF Gold BeES",category:"Gold ETF",weight:11.0},
    {rank:7,name:"Sovereign Gold Bond 2026-27 Series",category:"SGB",weight:10.0},
    {rank:8,name:"IndiGrid Infrastructure InvIT",category:"InvIT",weight:7.0},
    {rank:9,name:"Power Grid Corp InvIT",category:"InvIT",weight:5.0},
    {rank:10,name:"Aditya Birla Private Equity Fund",category:"Category II AIF",weight:3.0},
    {rank:11,name:"Quantum Long Term Equity Fund",category:"Large Cap MF",weight:1.0},
    {rank:12,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "retirement-shield": [
    {rank:1,name:"SBI Retirement Benefit Fund",category:"Retirement MF",weight:10.0},
    {rank:2,name:"HDFC Retirement Savings — Hybrid",category:"Retirement MF",weight:9.0},
    {rank:3,name:"ICICI Pru Retirement Balanced",category:"Retirement MF",weight:8.0},
    {rank:4,name:"Franklin India Pension Plan",category:"Retirement MF",weight:8.0},
    {rank:5,name:"HDFC Corporate Bond Fund",category:"Bond MF",weight:8.0},
    {rank:6,name:"SBI Magnum Gilt Fund",category:"Gilt MF",weight:7.0},
    {rank:7,name:"Axis AAA Bond Plus SDL",category:"Bond MF",weight:7.0},
    {rank:8,name:"Embassy REIT",category:"REIT",weight:6.0},
    {rank:9,name:"Nippon India Gold Savings Fund",category:"Gold ETF",weight:6.0},
    {rank:10,name:"ICICI Pru Equity & Debt Fund",category:"Hybrid MF",weight:6.0},
    {rank:11,name:"Kotak NIFTY 50 ETF",category:"Index ETF",weight:5.0},
    {rank:12,name:"Mirae Asset Large Cap Fund",category:"Large Cap MF",weight:5.0},
    {rank:13,name:"IndiGrid InvIT",category:"InvIT",weight:5.0},
    {rank:14,name:"Aditya Birla SL Savings Fund",category:"Ultra Short MF",weight:4.0},
    {rank:15,name:"DSP BlackRock Short Term Fund",category:"Short Term MF",weight:4.0},
    {rank:16,name:"HDFC Liquid Fund",category:"Liquid MF",weight:2.0},
  ],
  "bharat-2030": [
    {rank:1,name:"SBI PSU Fund",category:"PSU/Thematic MF",weight:7.0},
    {rank:2,name:"Nippon India Power & Infra Fund",category:"Infra MF",weight:6.0},
    {rank:3,name:"HDFC Infrastructure Fund",category:"Infra MF",weight:6.0},
    {rank:4,name:"Quant Infrastructure Fund",category:"Infra MF",weight:5.0},
    {rank:5,name:"Kotak Infrastructure & Eco Reform",category:"Infra MF",weight:5.0},
    {rank:6,name:"Aditya Birla SL India GenNext",category:"Thematic MF",weight:5.0},
    {rank:7,name:"Franklin India Opportunities Fund",category:"Thematic MF",weight:5.0},
    {rank:8,name:"UTI Infrastructure Fund",category:"Infra MF",weight:5.0},
    {rank:9,name:"DSP Natural Resources Fund",category:"Thematic MF",weight:4.0},
    {rank:10,name:"Tata Resources & Energy Fund",category:"Thematic MF",weight:4.0},
    {rank:11,name:"ICICI Pru Manufacturing Fund",category:"Thematic MF",weight:4.0},
    {rank:12,name:"IndiGrid InvIT",category:"InvIT",weight:4.0},
    {rank:13,name:"Power Grid Corp InvIT",category:"InvIT",weight:4.0},
    {rank:14,name:"Embassy Office Parks REIT",category:"REIT",weight:4.0},
    {rank:15,name:"Axis India Manufacturing Fund",category:"Thematic MF",weight:4.0},
    {rank:16,name:"Mirae Asset Great Consumer Fund",category:"Thematic MF",weight:4.0},
    {rank:17,name:"Edelweiss India Defence Fund",category:"Thematic MF",weight:4.0},
    {rank:18,name:"Nippon India Nifty Midcap 150 ETF",category:"Mid Cap ETF",weight:3.0},
    {rank:19,name:"Bandhan Infrastructure Fund",category:"Infra MF",weight:3.0},
    {rank:20,name:"PGIM India Flexi Cap Fund",category:"Flexi Cap MF",weight:3.0},
    {rank:21,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:3.0},
    {rank:22,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:3.0},
    {rank:23,name:"HDFC Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:24,name:"SBI Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "nifty50-index-alpha": [
    {rank:1,name:"UTI NIFTY 50 Index Fund",category:"Index MF",weight:20.0},
    {rank:2,name:"HDFC Index Fund NIFTY 50",category:"Index MF",weight:18.0},
    {rank:3,name:"ICICI Pru NIFTY 50 Index Fund",category:"Index MF",weight:15.0},
    {rank:4,name:"Kotak NIFTY 50 ETF",category:"Index ETF",weight:14.0},
    {rank:5,name:"Nippon India ETF Nifty BeES",category:"Index ETF",weight:13.0},
    {rank:6,name:"SBI NIFTY Index Fund",category:"Index MF",weight:8.0},
    {rank:7,name:"UTI NIFTY Next 50 Index Fund",category:"Index MF",weight:5.0},
    {rank:8,name:"Nippon India ETF Nifty Next 50",category:"Index ETF",weight:4.0},
    {rank:9,name:"Aditya Birla NIFTY 50 ETF",category:"Index ETF",weight:2.0},
    {rank:10,name:"Mirae Asset NIFTY 50 ETF",category:"Index ETF",weight:1.0},
    {rank:11,name:"HDFC Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:12,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "midcap-momentum": [
    {rank:1,name:"HDFC Mid-Cap Opportunities Fund",category:"Mid Cap MF",weight:9.0},
    {rank:2,name:"Kotak Emerging Equity Fund",category:"Mid Cap MF",weight:8.0},
    {rank:3,name:"Nippon India Growth Fund",category:"Mid Cap MF",weight:8.0},
    {rank:4,name:"SBI Magnum Midcap Fund",category:"Mid Cap MF",weight:7.0},
    {rank:5,name:"Franklin India Prima Fund",category:"Mid Cap MF",weight:7.0},
    {rank:6,name:"ICICI Pru Midcap Fund",category:"Mid Cap MF",weight:6.0},
    {rank:7,name:"Quant Mid Cap Fund",category:"Mid Cap MF",weight:6.0},
    {rank:8,name:"Axis Midcap Fund",category:"Mid Cap MF",weight:6.0},
    {rank:9,name:"Motilal Oswal Midcap Fund",category:"Mid Cap MF",weight:6.0},
    {rank:10,name:"Aditya Birla SL Midcap Fund",category:"Mid Cap MF",weight:6.0},
    {rank:11,name:"Edelweiss Mid Cap Fund",category:"Mid Cap MF",weight:5.0},
    {rank:12,name:"DSP Midcap Fund",category:"Mid Cap MF",weight:5.0},
    {rank:13,name:"PGIM India Midcap Opp Fund",category:"Mid Cap MF",weight:5.0},
    {rank:14,name:"Nippon ETF Nifty Midcap 150",category:"Mid Cap ETF",weight:5.0},
    {rank:15,name:"Tata Mid Cap Growth Fund",category:"Mid Cap MF",weight:5.0},
    {rank:16,name:"Bandhan Core Equity Fund",category:"Mid Cap MF",weight:4.0},
    {rank:17,name:"Mirae Asset Midcap Fund",category:"Mid Cap MF",weight:4.0},
    {rank:18,name:"Invesco India Midcap Fund",category:"Mid Cap MF",weight:4.0},
    {rank:19,name:"HDFC Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:20,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:2.0},
  ],
  "smallcap-discovery": [
    {rank:1,name:"Nippon India Small Cap Fund",category:"Small Cap MF",weight:10.0},
    {rank:2,name:"SBI Small Cap Fund",category:"Small Cap MF",weight:9.0},
    {rank:3,name:"Quant Small Cap Fund",category:"Small Cap MF",weight:8.0},
    {rank:4,name:"Axis Small Cap Fund",category:"Small Cap MF",weight:8.0},
    {rank:5,name:"HDFC Small Cap Fund",category:"Small Cap MF",weight:7.0},
    {rank:6,name:"Kotak Small Cap Fund",category:"Small Cap MF",weight:6.0},
    {rank:7,name:"Canara Robeco Small Cap Fund",category:"Small Cap MF",weight:6.0},
    {rank:8,name:"Tata Small Cap Fund",category:"Small Cap MF",weight:5.0},
    {rank:9,name:"DSP Small Cap Fund",category:"Small Cap MF",weight:5.0},
    {rank:10,name:"Franklin India Smaller Companies",category:"Small Cap MF",weight:5.0},
    {rank:11,name:"Aditya Birla SL Small Cap Fund",category:"Small Cap MF",weight:5.0},
    {rank:12,name:"Bandhan Small Cap Fund",category:"Small Cap MF",weight:5.0},
    {rank:13,name:"Edelweiss Small Cap Fund",category:"Small Cap MF",weight:4.0},
    {rank:14,name:"ICICI Pru Small Cap Fund",category:"Small Cap MF",weight:4.0},
    {rank:15,name:"Invesco India Smallcap Fund",category:"Small Cap MF",weight:4.0},
    {rank:16,name:"Union Small Cap Fund",category:"Small Cap MF",weight:4.0},
    {rank:17,name:"Mirae Asset Small Cap Fund",category:"Small Cap MF",weight:4.0},
    {rank:18,name:"Sundaram Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:19,name:"PGIM India Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:20,name:"Motilal Oswal Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:21,name:"LIC MF Small Cap Fund",category:"Small Cap MF",weight:3.0},
    {rank:22,name:"Navi Small Cap Index Fund",category:"Small Cap ETF",weight:3.0},
    {rank:23,name:"Baroda BNP Paribas Small Cap",category:"Small Cap MF",weight:2.0},
    {rank:24,name:"HDFC Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:25,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "flexicap-allcap": [
    {rank:1,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:7.0},
    {rank:2,name:"HDFC Flexi Cap Fund",category:"Flexi Cap MF",weight:6.0},
    {rank:3,name:"Kotak Flexi Cap Fund",category:"Flexi Cap MF",weight:5.0},
    {rank:4,name:"SBI Flexi Cap Fund",category:"Flexi Cap MF",weight:5.0},
    {rank:5,name:"Franklin India Flexi Cap Fund",category:"Flexi Cap MF",weight:5.0},
    {rank:6,name:"Quant Flexi Cap Fund",category:"Flexi Cap MF",weight:5.0},
    {rank:7,name:"DSP Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:8,name:"Axis Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:9,name:"Union Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:10,name:"PGIM India Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:11,name:"Mirae Asset Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:12,name:"Canara Robeco Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:13,name:"Aditya Birla SL Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:14,name:"Tata Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:15,name:"Edelweiss Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:16,name:"Bandhan Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:17,name:"Nippon India Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:18,name:"Invesco India Multicap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:19,name:"ICICI Pru Multi Asset Fund",category:"Multi Asset",weight:4.0},
    {rank:20,name:"UTI Flexi Cap Fund",category:"Flexi Cap MF",weight:4.0},
    {rank:21,name:"Kotak Multi Asset Allocator",category:"Multi Asset",weight:3.0},
    {rank:22,name:"HDFC Multi Asset Fund",category:"Multi Asset",weight:3.0},
    {rank:23,name:"SBI Multi Asset Allocation Fund",category:"Multi Asset",weight:3.0},
    {rank:24,name:"Franklin India Multi Asset Sol",category:"Multi Asset",weight:3.0},
    {rank:25,name:"Nippon India Multi Asset Fund",category:"Multi Asset",weight:3.0},
    {rank:26,name:"DSP Multi Asset Allocation Fund",category:"Multi Asset",weight:3.0},
    {rank:27,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:28,name:"HDFC Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:29,name:"Axis Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:30,name:"SBI Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "multicap-balanced": [
    {rank:1,name:"Nippon India Multi Cap Fund",category:"Multi Cap MF",weight:7.0},
    {rank:2,name:"HDFC Multi Cap Fund",category:"Multi Cap MF",weight:6.0},
    {rank:3,name:"Quant Active Fund",category:"Multi Cap MF",weight:6.0},
    {rank:4,name:"Kotak Multicap Fund",category:"Multi Cap MF",weight:6.0},
    {rank:5,name:"Mahindra Manulife Multi Cap Fund",category:"Multi Cap MF",weight:5.0},
    {rank:6,name:"ITI Multi Cap Fund",category:"Multi Cap MF",weight:5.0},
    {rank:7,name:"SBI Multi Cap Fund",category:"Multi Cap MF",weight:5.0},
    {rank:8,name:"Axis Multi Cap Fund",category:"Multi Cap MF",weight:5.0},
    {rank:9,name:"ICICI Pru Multi Cap Fund",category:"Multi Cap MF",weight:5.0},
    {rank:10,name:"Sundaram Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:11,name:"Tata Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:12,name:"Franklin India Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:13,name:"Mirae Asset Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:14,name:"DSP Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:15,name:"Edelweiss Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:16,name:"Canara Robeco Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:17,name:"Bandhan Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:18,name:"Aditya Birla SL Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:19,name:"Invesco India Multicap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:20,name:"Union Multi Cap Fund",category:"Multi Cap MF",weight:4.0},
    {rank:21,name:"Navi Nifty 500 Value 50 Index Fund",category:"Multi Cap ETF",weight:3.0},
    {rank:22,name:"PGIM India Flexi Cap Fund",category:"Flexi Cap MF",weight:3.0},
    {rank:23,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:3.0},
    {rank:24,name:"UTI Multi Asset Allocation Fund",category:"Multi Asset",weight:3.0},
    {rank:25,name:"HDFC Liquid Fund",category:"Liquid MF",weight:3.0},
    {rank:26,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:27,name:"SBI Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:28,name:"Axis Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:29,name:"Kotak Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:30,name:"Nippon India Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "debt-short-duration": [
    {rank:1,name:"HDFC Short Term Debt Fund",category:"Short Term MF",weight:12.0},
    {rank:2,name:"Kotak Short Term Fund",category:"Short Term MF",weight:10.0},
    {rank:3,name:"ICICI Pru Short Term Fund",category:"Short Term MF",weight:10.0},
    {rank:4,name:"Aditya Birla SL Short Term Fund",category:"Short Term MF",weight:10.0},
    {rank:5,name:"SBI Short Term Debt Fund",category:"Short Term MF",weight:9.0},
    {rank:6,name:"Nippon India Short Term Fund",category:"Short Term MF",weight:8.0},
    {rank:7,name:"Axis Short Term Fund",category:"Short Term MF",weight:8.0},
    {rank:8,name:"DSP Short Term Fund",category:"Short Term MF",weight:7.0},
    {rank:9,name:"Franklin India Short Term Income",category:"Short Term MF",weight:7.0},
    {rank:10,name:"Tata Short Term Bond Fund",category:"Short Term MF",weight:7.0},
    {rank:11,name:"Mirae Asset Short Duration Fund",category:"Short Term MF",weight:6.0},
    {rank:12,name:"Invesco India Short Term Fund",category:"Short Term MF",weight:5.0},
    {rank:13,name:"HDFC Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:14,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:15,name:"Axis Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "debt-long-duration": [
    {rank:1,name:"SBI Magnum Gilt Fund",category:"Gilt Fund",weight:20.0},
    {rank:2,name:"ICICI Pru Gilt Fund",category:"Gilt Fund",weight:18.0},
    {rank:3,name:"HDFC Gilt Fund",category:"Gilt Fund",weight:15.0},
    {rank:4,name:"Nippon India Gilt SDL Index",category:"SDL ETF",weight:12.0},
    {rank:5,name:"Kotak Gilt Fund",category:"Gilt Fund",weight:10.0},
    {rank:6,name:"IDFC GSF Constant Maturity",category:"Gilt 10Y Fund",weight:10.0},
    {rank:7,name:"Quantum Dynamic Bond Fund",category:"Dynamic Bond MF",weight:7.0},
    {rank:8,name:"Edelweiss SDL+AAA PSU Bond",category:"Target Maturity",weight:5.0},
    {rank:9,name:"DSP Govt Securities Fund",category:"Gilt Fund",weight:2.0},
    {rank:10,name:"ICICI Pru Liquid Fund (Buffer)",category:"Liquid Buffer",weight:1.0},
  ],
  "debt-corporate-bond": [
    {rank:1,name:"HDFC Corporate Bond Fund",category:"Corp Bond MF",weight:12.0},
    {rank:2,name:"Kotak Corporate Bond Fund",category:"Corp Bond MF",weight:10.0},
    {rank:3,name:"ICICI Pru Corporate Bond Fund",category:"Corp Bond MF",weight:10.0},
    {rank:4,name:"Axis Corporate Debt Fund",category:"Corp Bond MF",weight:9.0},
    {rank:5,name:"Aditya Birla SL Corporate Bond",category:"Corp Bond MF",weight:9.0},
    {rank:6,name:"Nippon India Corporate Bond Fund",category:"Corp Bond MF",weight:8.0},
    {rank:7,name:"SBI Corporate Bond Fund",category:"Corp Bond MF",weight:8.0},
    {rank:8,name:"DSP Corporate Bond Fund",category:"Corp Bond MF",weight:7.0},
    {rank:9,name:"Franklin India Corporate Debt Fund",category:"Corp Bond MF",weight:7.0},
    {rank:10,name:"Tata Corporate Bond Fund",category:"Corp Bond MF",weight:6.0},
    {rank:11,name:"Mirae Asset Corporate Bond Fund",category:"Corp Bond MF",weight:5.0},
    {rank:12,name:"ICICI Pru Banking & PSU Debt",category:"Bond MF",weight:5.0},
    {rank:13,name:"Kotak Banking & PSU Debt Fund",category:"Bond MF",weight:4.0},
    {rank:14,name:"HDFC Liquid Fund",category:"Liquid MF",weight:3.0},
    {rank:15,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:3.0},
    {rank:16,name:"Axis Liquid Fund",category:"Liquid MF",weight:2.0},
    {rank:17,name:"Nippon India Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:18,name:"SBI Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "debt-liquid-park": [
    {rank:1,name:"HDFC Liquid Fund",category:"Liquid MF",weight:20.0},
    {rank:2,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:18.0},
    {rank:3,name:"SBI Liquid Fund",category:"Liquid MF",weight:17.0},
    {rank:4,name:"Kotak Liquid Fund",category:"Liquid MF",weight:15.0},
    {rank:5,name:"Nippon India Liquid Fund",category:"Liquid MF",weight:15.0},
    {rank:6,name:"Aditya Birla SL Liquid Fund",category:"Liquid MF",weight:8.0},
    {rank:7,name:"Axis Liquid Fund",category:"Liquid MF",weight:5.0},
    {rank:8,name:"DSP Liquidity Fund",category:"Liquid MF",weight:2.0},
  ],
  "balanced-advantage": [
    {rank:1,name:"HDFC Balanced Advantage Fund",category:"Balanced Adv MF",weight:15.0},
    {rank:2,name:"ICICI Pru Balanced Advantage Fund",category:"Balanced Adv MF",weight:14.0},
    {rank:3,name:"Kotak Balanced Advantage Fund",category:"Balanced Adv MF",weight:12.0},
    {rank:4,name:"Nippon India Balanced Advantage",category:"Balanced Adv MF",weight:10.0},
    {rank:5,name:"Edelweiss Balanced Advantage Fund",category:"Balanced Adv MF",weight:9.0},
    {rank:6,name:"SBI Balanced Advantage Fund",category:"Balanced Adv MF",weight:8.0},
    {rank:7,name:"Axis Balanced Advantage Fund",category:"Balanced Adv MF",weight:8.0},
    {rank:8,name:"DSP Dynamic Asset Allocation Fund",category:"Balanced Adv MF",weight:7.0},
    {rank:9,name:"Franklin India Dynamic Asset Alloc",category:"Balanced Adv MF",weight:7.0},
    {rank:10,name:"Mirae Asset Dynamic Allocation Fund",category:"Balanced Adv MF",weight:6.0},
    {rank:11,name:"Aditya Birla SL Balanced Advantage",category:"Balanced Adv MF",weight:5.0},
    {rank:12,name:"Tata Balanced Advantage Fund",category:"Balanced Adv MF",weight:5.0},
    {rank:13,name:"Invesco India Dynamic Equity Fund",category:"Balanced Adv MF",weight:4.0},
    {rank:14,name:"PGIM India Balanced Advantage Fund",category:"Balanced Adv MF",weight:4.0},
    {rank:15,name:"Quant Dynamic Asset Allocation",category:"Balanced Adv MF",weight:4.0},
    {rank:16,name:"UTI Balanced Advantage Fund",category:"Balanced Adv MF",weight:4.0},
    {rank:17,name:"Bandhan Balanced Advantage Fund",category:"Balanced Adv MF",weight:4.0},
    {rank:18,name:"LIC MF Balanced Advantage Fund",category:"Balanced Adv MF",weight:3.0},
    {rank:19,name:"HDFC Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:20,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "corp-treasury-operational": [
    {rank:1,name:"HDFC Liquid Fund",category:"Liquid MF",weight:20.0},
    {rank:2,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:18.0},
    {rank:3,name:"SBI Liquid Fund",category:"Liquid MF",weight:15.0},
    {rank:4,name:"Kotak Liquid Fund",category:"Liquid MF",weight:14.0},
    {rank:5,name:"Nippon India Liquid Fund",category:"Liquid MF",weight:13.0},
    {rank:6,name:"Aditya Birla SL Liquid Fund",category:"Liquid MF",weight:10.0},
    {rank:7,name:"Axis Liquid Fund",category:"Liquid MF",weight:5.0},
    {rank:8,name:"DSP Liquidity Fund",category:"Liquid MF",weight:5.0},
  ],
  "corp-treasury-strategic": [
    {rank:1,name:"HDFC Banking & PSU Debt Fund",category:"Banking & PSU MF",weight:12.0},
    {rank:2,name:"ICICI Pru Banking & PSU Debt Fund",category:"Banking & PSU MF",weight:11.0},
    {rank:3,name:"Kotak Banking & PSU Debt Fund",category:"Banking & PSU MF",weight:10.0},
    {rank:4,name:"Nippon India Banking & PSU Debt",category:"Banking & PSU MF",weight:10.0},
    {rank:5,name:"SBI Banking & PSU Fund",category:"Banking & PSU MF",weight:9.0},
    {rank:6,name:"Aditya Birla SL Banking & PSU Debt",category:"Banking & PSU MF",weight:9.0},
    {rank:7,name:"DSP Banking & PSU Debt Fund",category:"Banking & PSU MF",weight:8.0},
    {rank:8,name:"Axis Banking & PSU Debt Fund",category:"Banking & PSU MF",weight:8.0},
    {rank:9,name:"HDFC Short Term Debt Fund",category:"Short Term MF",weight:8.0},
    {rank:10,name:"ICICI Pru Short Term Fund",category:"Short Term MF",weight:7.0},
    {rank:11,name:"HDFC Liquid Fund",category:"Liquid MF",weight:5.0},
    {rank:12,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:3.0},
  ],
  "goal-child-education": [
    {rank:1,name:"Axis Long Term Equity Fund (ELSS)",category:"ELSS MF",weight:12.0},
    {rank:2,name:"Mirae Asset Tax Saver Fund",category:"ELSS MF",weight:10.0},
    {rank:3,name:"Mirae Asset Large Cap Fund",category:"Large Cap MF",weight:9.0},
    {rank:4,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:9.0},
    {rank:5,name:"HDFC Mid-Cap Opportunities Fund",category:"Mid Cap MF",weight:8.0},
    {rank:6,name:"SBI Small Cap Fund",category:"Small Cap MF",weight:8.0},
    {rank:7,name:"HDFC Corporate Bond Fund",category:"Corp Bond MF",weight:8.0},
    {rank:8,name:"Axis AAA Bond Plus SDL",category:"Bond MF",weight:8.0},
    {rank:9,name:"Nippon India Gold Savings Fund",category:"Gold ETF",weight:7.0},
    {rank:10,name:"Kotak NIFTY 50 ETF",category:"Index ETF",weight:6.0},
    {rank:11,name:"SBI Magnum Gilt Fund",category:"Gilt MF",weight:5.0},
    {rank:12,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:5.0},
    {rank:13,name:"HDFC Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:14,name:"Axis Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "goal-retirement": [
    {rank:1,name:"HDFC Retirement Savings — Hybrid Equity",category:"Retirement MF",weight:10.0},
    {rank:2,name:"ICICI Pru Balanced Advantage Fund",category:"Balanced Adv MF",weight:9.0},
    {rank:3,name:"SBI Retirement Benefit Fund",category:"Retirement MF",weight:8.0},
    {rank:4,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:7.0},
    {rank:5,name:"Mirae Asset Large Cap Fund",category:"Large Cap MF",weight:7.0},
    {rank:6,name:"SBI Magnum Gilt Fund",category:"Gilt MF",weight:7.0},
    {rank:7,name:"HDFC Corporate Bond Fund",category:"Corp Bond MF",weight:7.0},
    {rank:8,name:"Embassy Office Parks REIT",category:"REIT",weight:7.0},
    {rank:9,name:"Nippon India Gold Savings Fund",category:"Gold ETF",weight:6.0},
    {rank:10,name:"Axis AAA Bond Plus SDL",category:"Bond MF",weight:6.0},
    {rank:11,name:"HDFC Balanced Advantage Fund",category:"Balanced Adv MF",weight:6.0},
    {rank:12,name:"Kotak NIFTY 50 ETF",category:"Index ETF",weight:6.0},
    {rank:13,name:"IndiGrid InvIT",category:"InvIT",weight:5.0},
    {rank:14,name:"Aditya Birla SL Savings Fund",category:"Ultra Short MF",weight:5.0},
    {rank:15,name:"HDFC Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:16,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "goal-wedding-fund": [
    {rank:1,name:"Kotak NIFTY 50 ETF",category:"Index ETF",weight:20.0},
    {rank:2,name:"HDFC Top 100 Fund",category:"Large Cap MF",weight:15.0},
    {rank:3,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:14.0},
    {rank:4,name:"HDFC Corporate Bond Fund",category:"Corp Bond MF",weight:12.0},
    {rank:5,name:"SBI Magnum Gilt Fund",category:"Gilt MF",weight:12.0},
    {rank:6,name:"Nippon India Gold Savings Fund",category:"Gold ETF",weight:12.0},
    {rank:7,name:"ICICI Pru Balanced Advantage Fund",category:"Balanced Adv MF",weight:8.0},
    {rank:8,name:"Axis AAA Bond Plus SDL",category:"Bond MF",weight:5.0},
    {rank:9,name:"HDFC Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:10,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "goal-home-downpayment": [
    {rank:1,name:"HDFC Short Term Debt Fund",category:"Short Term MF",weight:22.0},
    {rank:2,name:"ICICI Pru Short Term Fund",category:"Short Term MF",weight:20.0},
    {rank:3,name:"Kotak Short Term Fund",category:"Short Term MF",weight:18.0},
    {rank:4,name:"SBI Magnum Income Fund",category:"Income MF",weight:15.0},
    {rank:5,name:"HDFC Corporate Bond Fund",category:"Corp Bond MF",weight:12.0},
    {rank:6,name:"Nippon India Gold Savings Fund",category:"Gold ETF",weight:7.0},
    {rank:7,name:"Axis Liquid Fund",category:"Liquid MF",weight:3.0},
    {rank:8,name:"HDFC Liquid Fund",category:"Liquid MF",weight:3.0},
  ],
  "goal-emergency-corpus": [
    {rank:1,name:"HDFC Liquid Fund",category:"Liquid MF",weight:35.0},
    {rank:2,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:25.0},
    {rank:3,name:"Aditya Birla Overnight Fund",category:"Overnight MF",weight:25.0},
    {rank:4,name:"1-Month Bank FD",category:"Bank FD",weight:15.0},
  ],
  "goal-senior-citizen": [
    {rank:1,name:"SBI Magnum Income Fund",category:"Income MF",weight:15.0},
    {rank:2,name:"HDFC Corporate Bond Fund",category:"Corp Bond MF",weight:14.0},
    {rank:3,name:"HDFC Short Term Debt Fund",category:"Short Term MF",weight:13.0},
    {rank:4,name:"Embassy Office Parks REIT",category:"REIT",weight:12.0},
    {rank:5,name:"Nippon India Gold Savings Fund",category:"Gold ETF",weight:11.0},
    {rank:6,name:"ICICI Pru Balanced Advantage Fund",category:"Balanced Adv MF",weight:10.0},
    {rank:7,name:"SBI Magnum Gilt Fund",category:"Gilt MF",weight:9.0},
    {rank:8,name:"Kotak Banking & PSU Debt Fund",category:"Bond MF",weight:8.0},
    {rank:9,name:"HDFC Liquid Fund",category:"Liquid MF",weight:5.0},
    {rank:10,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:3.0},
  ],
  "goal-starter-sip": [
    {rank:1,name:"UTI NIFTY 50 Index Fund",category:"Index MF",weight:30.0},
    {rank:2,name:"Parag Parikh Flexi Cap Fund",category:"Flexi Cap MF",weight:25.0},
    {rank:3,name:"SBI Small Cap Fund",category:"Small Cap MF",weight:20.0},
    {rank:4,name:"HDFC Corporate Bond Fund",category:"Corp Bond MF",weight:15.0},
    {rank:5,name:"Nippon India Gold Savings Fund",category:"Gold ETF",weight:7.0},
    {rank:6,name:"HDFC Liquid Fund",category:"Liquid MF",weight:3.0},
  ],
  "thematic-bfsi": [
    {rank:1,name:"ICICI Pru Banking & Financial Services",category:"BFSI Thematic",weight:12.0},
    {rank:2,name:"SBI Banking & Financial Services Fund",category:"BFSI Thematic",weight:11.0},
    {rank:3,name:"Nippon India Banking & Financial Services",category:"BFSI Thematic",weight:10.0},
    {rank:4,name:"Tata Banking & Financial Services Fund",category:"BFSI Thematic",weight:9.0},
    {rank:5,name:"Kotak Banking and Financial Services",category:"BFSI Thematic",weight:9.0},
    {rank:6,name:"Aditya Birla SL Banking & Financial Serv",category:"BFSI Thematic",weight:8.0},
    {rank:7,name:"DSP Banking & Financial Services Fund",category:"BFSI Thematic",weight:8.0},
    {rank:8,name:"LIC MF Banking & Financial Services",category:"BFSI Thematic",weight:7.0},
    {rank:9,name:"Invesco India Financial Services Fund",category:"BFSI Thematic",weight:6.0},
    {rank:10,name:"Canara Robeco Banking & Financial Serv",category:"BFSI Thematic",weight:6.0},
    {rank:11,name:"Nippon ETF Bank BeES",category:"BFSI ETF",weight:5.0},
    {rank:12,name:"Motilal Oswal S&P BSE Fin Services ETF",category:"BFSI ETF",weight:4.0},
    {rank:13,name:"MIRAE Asset Banking & Fin Services ETF",category:"BFSI ETF",weight:3.0},
    {rank:14,name:"HDFC Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:15,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "thematic-pharma": [
    {rank:1,name:"ICICI Pru Pharma Healthcare Fund",category:"Pharma Thematic",weight:12.0},
    {rank:2,name:"Nippon India Pharma Fund",category:"Pharma Thematic",weight:11.0},
    {rank:3,name:"UTI Healthcare Fund",category:"Pharma Thematic",weight:10.0},
    {rank:4,name:"DSP Healthcare Fund",category:"Pharma Thematic",weight:9.0},
    {rank:5,name:"Mirae Asset Healthcare Fund",category:"Pharma Thematic",weight:9.0},
    {rank:6,name:"Kotak Healthcare Fund",category:"Pharma Thematic",weight:8.0},
    {rank:7,name:"HDFC Pharma and Healthcare Fund",category:"Pharma Thematic",weight:8.0},
    {rank:8,name:"Tata India Pharma & Healthcare Fund",category:"Pharma Thematic",weight:7.0},
    {rank:9,name:"Quant Healthcare Fund",category:"Pharma Thematic",weight:6.0},
    {rank:10,name:"LIC MF Healthcare Fund",category:"Pharma Thematic",weight:5.0},
    {rank:11,name:"Invesco India Healthcare Fund",category:"Pharma Thematic",weight:5.0},
    {rank:12,name:"Bandhan Healthcare Fund",category:"Pharma Thematic",weight:4.0},
    {rank:13,name:"Canara Robeco Healthcare Fund",category:"Pharma Thematic",weight:3.0},
    {rank:14,name:"HDFC Liquid Fund",category:"Liquid MF",weight:1.0},
    {rank:15,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "thematic-defence": [
    {rank:1,name:"Edelweiss India Defence Fund",category:"Defence Thematic",weight:18.0},
    {rank:2,name:"Quant Defence Fund",category:"Defence Thematic",weight:16.0},
    {rank:3,name:"SBI Defence Opportunities Fund",category:"Defence Thematic",weight:14.0},
    {rank:4,name:"Aditya Birla SL Defence Fund",category:"Defence Thematic",weight:12.0},
    {rank:5,name:"HDFC Defence Fund",category:"Defence Thematic",weight:11.0},
    {rank:6,name:"ICICI Pru Defence Fund",category:"Defence Thematic",weight:10.0},
    {rank:7,name:"Tata Indian Defence Fund",category:"Defence Thematic",weight:9.0},
    {rank:8,name:"Mirae Asset Nifty India Defence ETF",category:"Defence ETF",weight:5.0},
    {rank:9,name:"Motilal Oswal Nifty India Defence ETF",category:"Defence ETF",weight:3.0},
    {rank:10,name:"Nippon India Nifty India Defence ETF",category:"Defence ETF",weight:1.0},
    {rank:11,name:"HDFC Liquid Fund",category:"Liquid MF",weight:1.0},
  ],
  "thematic-consumption": [
    {rank:1,name:"Mirae Asset Great Consumer Fund",category:"Consumption MF",weight:8.0},
    {rank:2,name:"Nippon India Consumption Fund",category:"Consumption MF",weight:8.0},
    {rank:3,name:"ICICI Pru FMCG Fund",category:"FMCG Thematic",weight:7.0},
    {rank:4,name:"SBI Consumption Opportunities Fund",category:"Consumption MF",weight:7.0},
    {rank:5,name:"Aditya Birla SL India GenNext Fund",category:"Consumption MF",weight:6.0},
    {rank:6,name:"UTI India Consumer Fund",category:"Consumption MF",weight:6.0},
    {rank:7,name:"Bandhan Consumer Fund",category:"Consumption MF",weight:6.0},
    {rank:8,name:"Tata India Consumer Fund",category:"Consumption MF",weight:6.0},
    {rank:9,name:"Kotak India Growth Fund",category:"Consumption MF",weight:5.0},
    {rank:10,name:"Axis India Manufacturing Fund",category:"Consumption MF",weight:5.0},
    {rank:11,name:"DSP India T.I.G.E.R. Fund",category:"Infrastructure",weight:5.0},
    {rank:12,name:"HDFC Liquid Fund",category:"Liquid MF",weight:5.0},
    {rank:13,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:14,name:"SBI Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:15,name:"Nippon India Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:16,name:"Axis Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:17,name:"Kotak Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:18,name:"DSP Liquidity Fund",category:"Liquid MF",weight:4.0},
    {rank:19,name:"Aditya Birla SL Liquid Fund",category:"Liquid MF",weight:4.0},
    {rank:20,name:"Mirae Asset Liquid Fund",category:"Liquid MF",weight:3.0},
    {rank:21,name:"Tata Liquid Fund",category:"Liquid MF",weight:3.0},
  ],
  "debt-target-maturity-2028": [
    {rank:1,name:"Edelweiss NIFTY PSU Bond + SDL Index 2028",category:"Target Maturity ETF",weight:20.0},
    {rank:2,name:"HDFC NIFTY SDL Plus G-Sec Jun 2028 Index",category:"Target Maturity ETF",weight:18.0},
    {rank:3,name:"IDFC CRISIL IBX Triple A Financial June 2028",category:"Target Maturity",weight:15.0},
    {rank:4,name:"Nippon India ETF Nifty SDL 2028 Maturity",category:"Target Maturity ETF",weight:15.0},
    {rank:5,name:"Aditya Birla SL CRISIL IBX SDL May 2028",category:"Target Maturity",weight:12.0},
    {rank:6,name:"Kotak NIFTY SDL Jul 2028 Index Fund",category:"Target Maturity",weight:10.0},
    {rank:7,name:"SBI Magnum CRISIL IBX Gilt Fund 2028",category:"Target Maturity",weight:7.0},
    {rank:8,name:"ICICI Pru Liquid Fund",category:"Liquid MF",weight:3.0},
  ],
  "corp-treasury-overnight": [
    {rank:1,name:"HDFC Overnight Fund",category:"Overnight MF",weight:28.0},
    {rank:2,name:"ICICI Pru Overnight Fund",category:"Overnight MF",weight:24.0},
    {rank:3,name:"SBI Overnight Fund",category:"Overnight MF",weight:20.0},
    {rank:4,name:"Kotak Overnight Fund",category:"Overnight MF",weight:16.0},
    {rank:5,name:"Nippon India Overnight Fund",category:"Overnight MF",weight:12.0},
  ],
  "corp-treasury-short": [
    {rank:1,name:"HDFC Ultra Short Term Fund",category:"Ultra Short MF",weight:22.0},
    {rank:2,name:"ICICI Pru Ultra Short Term Fund",category:"Ultra Short MF",weight:18.0},
    {rank:3,name:"Aditya Birla SL Money Market Fund",category:"Money Market MF",weight:18.0},
    {rank:4,name:"Nippon India Money Market Fund",category:"Money Market MF",weight:12.0},
    {rank:5,name:"Axis Treasury Advantage Fund",category:"CD/CP via MF",weight:20.0},
    {rank:6,name:"SBI Liquid Fund",category:"Liquid MF",weight:10.0},
  ],
  "corp-treasury-active": [
    {rank:1,name:"HDFC Short Term Debt Fund",category:"Short Duration MF",weight:18.0},
    {rank:2,name:"Kotak Short Term Fund",category:"Short Duration MF",weight:17.0},
    {rank:3,name:"Kotak Banking & PSU Debt Fund",category:"Banking & PSU MF",weight:15.0},
    {rank:4,name:"Nippon India Banking & PSU Debt Fund",category:"Banking & PSU MF",weight:10.0},
    {rank:5,name:"Nippon India Corporate Bond Fund",category:"Corporate Bond MF",weight:15.0},
    {rank:6,name:"Aditya Birla SL Corporate Bond Fund",category:"Corporate Bond MF",weight:10.0},
    {rank:7,name:"Aditya Birla SL Floating Rate Fund",category:"Floating Rate MF",weight:10.0},
    {rank:8,name:"HDFC Floating Rate Debt Fund",category:"Floating Rate MF",weight:5.0},
  ],
};

// ── Enriched portfolio holdings seed (with real AMFI codes + ISINs) ───────────
const PORTFOLIO_HOLDINGS_SEED: Record<string, object[]> = Object.fromEntries(
  Object.entries(RAW_HOLDINGS).map(([id, h]) => [id, enrich(h)])
);

/**
 * Seeds holdings for all model portfolios where the DB has fewer holdings than
 * the enriched static data. Safe to run multiple times — only updates if DB count
 * < static count (idempotent).
 */
export async function seedModelPortfolioHoldings(): Promise<void> {
  let updated = 0;
  let skipped = 0;
  let errors  = 0;

  // Log coverage stats at startup
  const totalHoldings = Object.values(PORTFOLIO_HOLDINGS_SEED)
    .flatMap(h => h as any[]).length;
  const withSchemeCode = Object.values(PORTFOLIO_HOLDINGS_SEED)
    .flatMap(h => h as any[])
    .filter((h: any) => h.schemeCode != null).length;
  console.log(
    `[Holdings Seed] ${totalHoldings} holdings across ${Object.keys(PORTFOLIO_HOLDINGS_SEED).length} portfolios | ` +
    `AMFI schemeCode coverage: ${withSchemeCode}/${totalHoldings} (${Math.round(100*withSchemeCode/totalHoldings)}%)`
  );

  for (const [portfolioId, holdings] of Object.entries(PORTFOLIO_HOLDINGS_SEED)) {
    try {
      const rows = await db.select({ id: modelPortfolios.id, holdings: modelPortfolios.holdings })
        .from(modelPortfolios)
        .where(eq(modelPortfolios.id, portfolioId))
        .limit(1);

      if (!rows[0]) { skipped++; continue; }

      const current = Array.isArray(rows[0].holdings) ? rows[0].holdings : [];
      if (current.length >= holdings.length) { skipped++; continue; }

      await db.update(modelPortfolios)
        .set({ holdings: holdings as any, updatedAt: new Date() })
        .where(eq(modelPortfolios.id, portfolioId));

      console.log(`  ✅ [Holdings Seed] ${portfolioId}: ${holdings.length} holdings (was ${current.length})`);
      updated++;
    } catch (err: unknown) {
      console.warn(`  ⚠️  [Holdings Seed] ${portfolioId} failed:`, err instanceof Error ? err.message : String(err));
      errors++;
    }
  }

  console.log(`[Holdings Seed] Complete — updated: ${updated}, skipped: ${skipped}, errors: ${errors}`);
}
